### ISSUE TITLE
[DragonAPI] Throwing Error in Console about Redstone Aresenal (no crash)

### ISSUE THREAD

**Issue by ranger135xp** [ReikaKalseki/Reika_Mods_Issues#348] opened 2015-10-19 10:49 UTC
I don't know if this is causing any bugs for sure, but DragonAPI is complaining in console upon initial load. It instructs to contact the mod author. I did so here:http://github.com/CoFH/Feedback/issues/877 If you can't read the image, let me know. CoFH says it's not their issue.
![dc587b7e-7394-11e5-9d00-fb9cde1de912](https://cloud.githubusercontent.com/assets/15115164/10575879/85b608cc-762d-11e5-853b-dd0f572bcac8.png)

**Comment by ljfa-ag** [comment] 2015-10-19 13:49
Duplicate of #316 
Should be fixed in the upcoming version

**Closed as completed by ljfa-ag** 2015-10-19 13:49 UTC
Labels: Duplicate
