### ISSUE TITLE
NullPointerException TinkerToolHandler

### ISSUE THREAD

**Issue by NachtRaben** [ReikaKalseki/Reika_Mods_Issues#383] opened 2015-11-08 07:55 UTC
Using most recent versions of rotarycraft, reactorcraft, electricraft, chromaticraft, tinkers construct, and Iguana Tinkers Tweaks for minecraft version 1.7.10 as of 11/17/2015.

Shift breaking a dirt block with any tinkers shortbow produces this stacktrace and instantly crashes.

http://hastebin.com/ugureqonir.avrasm

**Comment by OneEyeMaker** [comment] 2015-11-08 14:13
Please, use search before adding issue. 
Seems like a duplicate of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/318

**Closed as completed** 2015-11-08 19:42 UTC
Labels: Duplicate
