### ISSUE TITLE
instant client crash mining chromaticraft block

### ISSUE THREAD

**Issue by Morpheus1101** [ReikaKalseki/Reika_Mods_Issues#752] opened 2016-04-19 00:07 UTC
This occurs reguardless of dimension http://pastebin.com/vxX3C5S4

**Comment by ReikaKalseki** [comment] 2016-04-19 01:08
Duplicate of #262, #419, #717. I need more information, because everyone else just disappeared when asked.

**Comment by Morpheus1101** [comment] 2016-04-19 01:13
Only information is that if using a tinkers hammer and the chromaticraft block isnt the one being mined it'll mine perfectly fine, you just cant mine the  hromaticraft block directly otherwise once you do the game instantly crashes. I'll test it on a new world, sine this world was created b4 the addition of chromaticraft.

**Comment by Morpheus1101** [comment] 2016-04-19 01:30
Teating on a brand new world created with cromaticraft, mining works fine, so it would seem even going to a newly generated area after the addition of chromaticraft dosent work 100% and creation of a brand new world sadly is an absolute must. Energised Rock and Firaxite so far it crashes whilst mining, upon re-entering after the crash, the result of the mined block  is in your inventory

**Comment by ReikaKalseki** [comment] 2016-04-20 20:05
What tool you are using has no relevance.

**Comment by TomeWyrm** [comment] 2016-04-21 02:06
Yes, but the block break method used by tinkers hammers might be something to look at... assuming this is a duplicate of the issues I think it is, and honestly even if it isn't.

Obviously assuming this is reproducible.

**Comment by ReikaKalseki** [comment] 2016-04-21 05:29
It almost never is, and our last lead was "water flowing over", upon which the reporter promptly disappeared.

**Comment by Morpheus1101** [comment] 2016-04-21 05:43
Im willing an able to do any further testing you may think of, as i still have the world that has the issue.

All im able to do currently is continually reproduce the exact same crash using any sort of mining pick/hammer directly onto the  Chromaticraft block.  Taking into account that when this world was created  chromaticraft wasnt in it.

**Comment by ReikaKalseki** [comment] 2016-04-21 07:33
Try the same block in a different location.

**Comment by Morpheus1101** [comment] 2016-04-21 09:34
If i place Firaxite block down using creative and then break in survival, it dosent crash. Energised Rock when doin the same will cause crash. Mining either block thats been placed via worldgen will cause crash

**Comment by ReikaKalseki** [comment] 2016-04-21 13:03
And _that_ is entirely not my experience, and I have some 16K Chromic Dust in my ME system to prove it.

**Comment by Morpheus1101** [comment] 2016-04-21 13:21
Made a new world today with chromaticraft in it and finally found a chromaticraft block and once mined it also caused the for mentioned crash. This stage i was not able to see what the block was due to not being far enough along into chromaticraft.

Created a 2nd brand new world this time without using biomes'o'plenty and resulted in the same crash again

Creating a world using only chromaticraft and waila with no other mods and mining the unknown chromaticraft block is successful.

**Comment by ReikaKalseki** [comment] 2016-04-22 20:04
This makes no sense....

**Comment by Morpheus1101** [comment] 2016-04-22 21:57
When i have more time, i will strip out my mod pack and 1 by 1 re-add mods untill the crash occurs.

Mining Energised Rock gnerated during world gen dosent always cause a crash, when the rock is shining a specific color which is Blue i can mine it without a crash ... when it is Green and i mine it, it causes game to crash

**Comment by Morpheus1101** [comment] 2016-04-27 14:23
Further study into this, i also suspect other than Firaxite it could also be Fused Crystals considering that neither of those 2 are actually viewable untill a certain point through chromaticraft which only now am i able to see both. But mining any of the 3 directly causes b4 mentioned crash

**Comment by ReikaKalseki** [comment] 2016-04-27 19:01
None of them are viewable until a certain point.

**Comment by Davirus-Hash** [comment] 2016-05-20 16:19
Yup can confirm this bug. http://pastebin.com/QqA4DtsM

**Comment by ReikaKalseki** [comment] 2016-05-20 19:09
Again, under what conditions?

So far, the range of alleged causes is everything from what direction the player is facing to ores under water (or only flowing water) to it being a world that predates the installation of CC to light level to what tool is being used.

**Comment by Davirus-Hash** [comment] 2016-05-20 19:23
Hello Mr.Reika, Thank you for your fast reply im a big fan of your works. The crash is almost guaranteed, so i took a screenshot before mining a stone-texture-chromaticraft block. ( http://imgur.com/5hhtuNv ) . As expected it did crash. It doesnt affect the crystals though.

Edit: I'm using the underground biomes constract mod that is why some stones look different. also fastcraft enabled. I mined the ores surrounding the stone-texture-CC block, i got no problem. so i think its regardless the environment?. 

Edit 2: Update:

it also affects energizedrock (http://imgur.com/QPiKjsf) . This time i mined all the surrounding blocks and then finally mined the energized rock but it crashes.

Test 2: I mined it without touching its surrounding blocks and without any light source or water near it. Still crashes.

**Comment by ReikaKalseki** [comment] 2016-05-21 02:15
You answered few of the questions posed.

**Comment by TomeWyrm** [comment] 2016-05-21 04:19
I'm as lost as you are, Reika. I swear that I've done what Davirus-Hash did and it didn't crash. Unreproducible bugs are annoying.

**Comment by Davirus-Hash** [comment] 2016-05-21 10:13
As morpheus said it the crash isnt happening when no other mods are
installed. So its probably a conflict from another mod. Im so sorry for
wasting your time. I will try to find out what mod(s) is causing it just
like what morpheus said. Thank you for your time :) . You are really a busy
guy maintaning 3 BIG mods so thank for being there whenever your mods are
mentioned, you are everywhere. Thanks for making such great mods! Hope you
dont abondon it yet.

**Comment by ReikaKalseki** [comment] 2016-05-23 01:20
Is Glenn's Gases installed? A similar sort of issue was found [here](https://github.com/lawremi/PerFabricaAdAstra/issues/56).

**Comment by Morpheus1101** [comment] 2016-05-23 02:39
I removed Glenns gases an was able to mine quite a few of the chromaticraft blocks without any crashes and once re-adding in the latest verion of Glenns Gases an mined said blocks again, i recieved the crash.  http://pastebin.com/k9mDmDmE

**Comment by Davirus-Hash** [comment] 2016-05-23 12:44
Okay can confirm , just created a new world without glenns gases installed, i can now mine chromaticraft blocks without problem. Mr.Reika you really are amazing for finding this untracable mod conflict.

**Comment by ReikaKalseki** [comment] 2016-05-23 18:43
FINALLY.

**Closed as completed by ReikaKalseki** 2016-05-23 18:43 UTC
Labels: Duplicate, Fixed, Mod Interaction, Other Mod's End, World Corruption, Stupid Code

**Comment by TomeWyrm** [comment] 2016-05-23 20:28
What in the heck was happening with Glenn's Gases?

**Comment by Davirus-Hash** [comment] 2016-05-23 21:49
Also small note, removing it fixes the underground biomes construct's dense ores and block mechanics. I never knew that GG was that buggy i liked the dust mechanic though other than that the machines and pipes are already redundant because of other bigger tech mods. 
Forgive my butchered grammar.

**Comment by ReikaKalseki** [comment] 2016-05-23 23:00
@TomeWyrm https://github.com/lawremi/PerFabricaAdAstra/issues/56
