### ISSUE TITLE
[RotaryCraft] [Bug] [Dupe] Fermenter production dupe and stack amount glitch with yeast and silverwood leaves

### ISSUE THREAD

**Issue by prc94** [ReikaKalseki/Reika_Mods_Issues#1062] opened 2016-07-23 08:09 UTC
Fermenter when using silverwood leaves to make slag from yeast providing it by 64, if take half-stack (32) it continue working and make the 32+64 stack (96), and this causing dupe glitch with Thermal Dynamics: i`ve using the basic servo and basic itemduct, basic servo extracts items by 4 and it extracts 16 slags before fermenter makes new, when fermenter makes new it stacks in output slot by 108, i dont now why after fermenting and extracting 5 yeasts this way i get 25 stacks of the slag instead five.

**Comment by Builderb0y** [comment] 2016-07-24 21:40
Reika, NOTHING is set up to specifically handle stack sizes greater than the max. Arguing that bigger stacks shouldn't cause problems in other mods is like arguing that null entries in the ore dictionary or recipe lists shouldn't cause problems in other mods.

**Comment by ReikaKalseki** [comment] 2016-07-25 04:13
This is entirely different from an unexpected null; this is all about exact numeric values, which do not matter if handled formulaically.

**Comment by Builderb0y** [comment] 2016-07-26 00:48
Actually, the two do share a common principle: unexpected conditions lead to unexpected results. Granted, unexpected nulls are good at randomly throwing NPEs if a mod isn't specifically checking for them, but unexpected stack sizes can cause just as many problems if not specially handled.

The "dropping negative stack sizes on the ground" bug is a great example of this; simple rules like "decrement stack size by 1, and delete the item stack if its size is 0" can still duplicate items if you have a negative quantity of them (or more than 127, as that gets cast to a byte upon saving to NBT data, and therefore goes negative). There's a reason why there's a limit on the max stack size, and that every method of moving items from point A to point B in vanilla specifically checks to make sure it doesn't exceed that limit: not doing sanity checks on them has similar unexpected behaviors all over the place. Just because some mods's blocks can handle this formulaically does NOT imply that everything can, nor that doing so is a good idea.

**Comment by ReikaKalseki** [comment] 2016-08-03 19:02
Done for both the Fermenter and Grinder. Does anything else produce more than one item per cycle?

**Closed as completed by ReikaKalseki** 2016-08-03 19:02 UTC
Labels: Fixed, Other Mod's End

**Comment by Builderb0y** [comment] 2016-08-04 02:58
The casting table _sort of_ does, and was half-fixed a while ago. Last time I checked, it could still create large stacks as the output, but has special handling for attempting to push that stack to adjacent inventories because ejecting them normally can void items if the stack is too large. Given that it does not eject to conduits, I think this is worth fixing too.
