### ISSUE TITLE
temperature calculation for the fluid crystallizer makes little sense

### ISSUE THREAD

**Issue by Turmfalke2** [ReikaKalseki/Reika_Mods_Issues#509] opened 2015-12-26 21:15 UTC
hi,
So I wanted freeze some water into ice cubes, so I got my self a fluid crystallizer. For the freezer to work the I need to cool it down, my first idea was to place a piece of packed ice on top of it. As it turns out this is not good enough, the crystallizer only hits -2C and and the water is still fluid.
Putting another block of ice next to it did nothing, so I checked the code on how to achieve the required -3C. Turns out I had the replace the 2th block of ice with water, with that the crystallizer cools down to -17C.
I feel like this is very unintuitive, one would assume that the water has a higher temperature and is therefore worse than a second block of ice.

https://github.com/ReikaKalseki/RotaryCraft/blob/master/TileEntities/Processing/TileEntityCrystallizer.java#L193

**Comment by zemerick** [comment] 2015-12-26 22:17
It's not ideal, but it's Reikas intended behavior. For example, the Blast Furnace does this with Lava and Fire. I'm closing this, but will point Reika this way to see if he has anything more to add.

**Closed as completed by zemerick** 2015-12-26 22:17 UTC
Labels: Not a Bug, RotaryCraft
