### ISSUE TITLE
Not an issue per se, but saw this in the console during start up

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#376] opened 2015-11-02 22:55 UTC
[INpureCullingEngine]: The mod DragonAPI is registering items or blocks with bad registry names. Names should not contain multiple colons as it breaks the ability to do reverse-lookups through FML. Please tell whoever made this mod that this should be changed!

Not sure if that is in any way relevant, it was just in yellow at the end of the log after starting up my world.

**Comment by Duckfan77** [comment] 2015-11-03 02:10
Duplicate of #370

**Closed as completed** 2015-11-03 09:01 UTC
Labels: Duplicate
