### ISSUE TITLE
Why i sometimes crash when i open the GUI

### ISSUE THREAD

**Issue by syf097** [ReikaKalseki/Reika_Mods_Issues#250] opened 2015-09-12 13:44 UTC
i' sure my minecraft worked well before installing this mod.But now it sometimes crash when i open the GUI of the block in this mod.

Edit by CoolSquid:
Moved crash report to Gist.
https://gist.github.com/coolsquid/f81d7b0c108f18e191e0

**Comment by ReikaKalseki** [comment] 2015-09-12 18:08
Duplicate of #161.

**Closed as completed by ReikaKalseki** 2015-09-12 18:08 UTC
Labels: Duplicate, Can't Reproduce

**Comment by sig** [comment] 2016-10-26 10:33
I can confirm this. I figured out, though, that if i open a machine GUI with empty hand - crash won't happen. But if i dare to click on any RoC machine with something in hand - it becomes a lottery, where you have big chances to win a great prize of crashing the game :)
The modpack i playing is this one:
https://www.atlauncher.com/pack/ProjectDarkMatter
there's a listed version of every mod), including:
RotaryCraft V16d

**Comment by Aivech** [comment] 2016-10-27 14:23
What are you holding when you open the GUI and it crashes?

EDIT: Also, why are you posting in an issue over a year old?
