### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by Tsyklop** [ReikaKalseki/Reika_Mods_Issues#337] opened 2015-10-14 04:08 UTC
I try to look recipe "Steel Grate" from Catwalks 2 and game crash. 

Error - http://pastebin.com/a6mD1Ymu

DragonAPI 1.7.10 V9b, RotaryCraft 1.7.10 V9b, ReactorCraft 1.7.10 V9b

**Comment by ReikaKalseki** [comment] 2015-10-14 04:34
This is caused by PnC and should be fixed in v10.

**Closed as completed by ReikaKalseki** 2015-10-14 04:34 UTC
Labels: Fixed, Mod Interaction

**Comment by MJRLegends** [comment] 2015-12-08 23:17
when is v10 out?
