### ISSUE TITLE
RotaryCraft conflicting with "stable" unstable ingot's crafting [Related to other NBT recipe issues]

### ISSUE THREAD

**Issue by SoraZodia** [ReikaKalseki/Reika_Mods_Issues#73] opened 2015-05-19 10:38 UTC
RotaryCraft appears to be causing Extra Utilities's pseudo inversion sigil to produce the regular unstable ingot rather than their "stable" counterpart.

With DragonAPI+RotaryCraft+Extra Utilities+NEI+Walia:
![Imgur](http://i.imgur.com/XelNRoA.png)

With DragonAPI+Extra Utilities+NEI+Walia:
![Imgur](http://i.imgur.com/kr0ankw.png)

**Comment by ReikaKalseki** [comment] 2015-05-19 18:31
This is an issue whose type has been reported before, but without some input from @rwtema I have no indications as to the cause.

https://github.com/McJty/RFTools/issues/91#issuecomment-83113225

https://github.com/rwtema/extrautilities/issues/525#issuecomment-92196545

**Comment by ReikaKalseki** [comment] 2015-05-19 18:40
I have searched my code again. I have only 5 references to `CraftingManager.recipeList`, and all five are read-only.

**Comment by McJty** [comment] 2015-06-10 18:40
I just found out some thing that _might_ give a clue. There is something else in RFTools that is slightly failing when RotaryCraft is included and that's the in game manual where I show recipes for some of the RFTools machines. This code shows a recipe and tries to find the recipe like this:

```
private static IRecipe findRecipe(ItemStack item) {
    if (item == null) {
        return null;
    }
    List<IRecipe> recipes = CraftingManager.getInstance().getRecipeList();
    for (IRecipe recipe : recipes) {
        if (recipe instanceof ShapedRecipes) {
            ItemStack recipeOutput = recipe.getRecipeOutput();
            if (recipeOutput != null && recipeOutput.isItemEqual(item)) {
                return recipe;
            }
        }
    }
    return null;
}
```

Apparently with RotaryCraft included with RFTools this fails for some (not all) recipes. The items are craftable though so not 100% sure it is the same. Just adding this as a possible new clue and a code snippet that seems to be non-functional in this case.

**Comment by ReikaKalseki** [comment] 2015-06-11 00:03
WTF...

**Comment by SoraZodia** [comment] 2015-06-11 00:27
I was able to get the recipe working again via MineTweaker. Maybe this can be a clue to what's happening. 
Script:

```
import minetweaker.item.IIngredient;

val iron = <ore:ingotIron>;
val diamond = <ore:gemDiamond>;

val stableSigil = <ExtraUtilities:divisionSigil>.onlyWithTag({stable:1});
val unstableSigil = <ExtraUtilities:divisionSigil>;
val stableIngot = <ExtraUtilities:unstableingot:2>;

val unstableIngot = <ExtraUtilities:unstableingot>.withTag({display: {Lore: ["You go boom boom if", " use shift-click in a crafting window"]}, dimension:0, time:0});

var sigils = [unstableSigil.onlyWithTag({damage:1}), unstableSigil.onlyWithTag({damage:2}), unstableSigil.onlyWithTag({damage:3}), unstableSigil.onlyWithTag({damage:4}), unstableSigil.onlyWithTag({damage:5}), unstableSigil.onlyWithTag({damage:6}), unstableSigil.onlyWithTag({damage:7}), unstableSigil.onlyWithTag({damage:8}), unstableSigil.onlyWithTag({damage:9}), unstableSigil.onlyWithTag({damage:10}), unstableSigil.onlyWithTag({damage:11}), unstableSigil.onlyWithTag({damage:12}), unstableSigil.onlyWithTag({damage:13}), unstableSigil.onlyWithTag({damage:14}), unstableSigil.onlyWithTag({damage:15}), unstableSigil.onlyWithTag({damage:16}), unstableSigil.onlyWithTag({damage:17}), unstableSigil.onlyWithTag({damage:18}), unstableSigil.onlyWithTag({damage:19}), unstableSigil.onlyWithTag({damage:20}), unstableSigil.onlyWithTag({damage:21}), unstableSigil.onlyWithTag({damage:22}), unstableSigil.onlyWithTag({damage:23}), unstableSigil.onlyWithTag({damage:24}), unstableSigil.onlyWithTag({damage:25}), unstableSigil.onlyWithTag({damage:26}), unstableSigil.onlyWithTag({damage:27}), unstableSigil.onlyWithTag({damage:28}), unstableSigil.onlyWithTag({damage:29}), unstableSigil.onlyWithTag({damage:30}), unstableSigil.onlyWithTag({damage:31}), unstableSigil.onlyWithTag({damage:32}), unstableSigil.onlyWithTag({damage:33}), unstableSigil.onlyWithTag({damage:34}), unstableSigil.onlyWithTag({damage:35}), unstableSigil.onlyWithTag({damage:36}), unstableSigil.onlyWithTag({damage:37}), unstableSigil.onlyWithTag({damage:38}), unstableSigil.onlyWithTag({damage:39}), unstableSigil.onlyWithTag({damage:40}), unstableSigil.onlyWithTag({damage:41}), unstableSigil.onlyWithTag({damage:42}), unstableSigil.onlyWithTag({damage:43}), unstableSigil.onlyWithTag({damage:44}), unstableSigil.onlyWithTag({damage:45}), unstableSigil.onlyWithTag({damage:46}), unstableSigil.onlyWithTag({damage:47}), unstableSigil.onlyWithTag({damage:48}), unstableSigil.onlyWithTag({damage:49}), unstableSigil.onlyWithTag({damage:50}), unstableSigil.onlyWithTag({damage:51}), unstableSigil.onlyWithTag({damage:52}), unstableSigil.onlyWithTag({damage:53}), unstableSigil.onlyWithTag({damage:54}), unstableSigil.onlyWithTag({damage:55}), unstableSigil.onlyWithTag({damage:56}), unstableSigil.onlyWithTag({damage:57}), unstableSigil.onlyWithTag({damage:58}), unstableSigil.onlyWithTag({damage:59}), unstableSigil.onlyWithTag({damage:60}), unstableSigil.onlyWithTag({damage:61}), unstableSigil.onlyWithTag({damage:62}), unstableSigil.onlyWithTag({damage:63}), unstableSigil.onlyWithTag({damage:64}), unstableSigil.onlyWithTag({damage:65}), unstableSigil.onlyWithTag({damage:66}), unstableSigil.onlyWithTag({damage:67}), unstableSigil.onlyWithTag({damage:68}), unstableSigil.onlyWithTag({damage:69}), unstableSigil.onlyWithTag({damage:70}), unstableSigil.onlyWithTag({damage:71}), unstableSigil.onlyWithTag({damage:72}), unstableSigil.onlyWithTag({damage:73}), unstableSigil.onlyWithTag({damage:74}), unstableSigil.onlyWithTag({damage:75}), unstableSigil.onlyWithTag({damage:76}), unstableSigil.onlyWithTag({damage:77}), unstableSigil.onlyWithTag({damage:78}), unstableSigil.onlyWithTag({damage:79}), unstableSigil.onlyWithTag({damage:80}), unstableSigil.onlyWithTag({damage:81}), unstableSigil.onlyWithTag({damage:82}), unstableSigil.onlyWithTag({damage:83}), unstableSigil.onlyWithTag({damage:84}), unstableSigil.onlyWithTag({damage:85}), unstableSigil.onlyWithTag({damage:86}), unstableSigil.onlyWithTag({damage:87}), unstableSigil.onlyWithTag({damage:88}), unstableSigil.onlyWithTag({damage:89}), unstableSigil.onlyWithTag({damage:90}), unstableSigil.onlyWithTag({damage:91}), unstableSigil.onlyWithTag({damage:92}), unstableSigil.onlyWithTag({damage:93}), unstableSigil.onlyWithTag({damage:94}), unstableSigil.onlyWithTag({damage:95}), unstableSigil.onlyWithTag({damage:96}), unstableSigil.onlyWithTag({damage:97}), unstableSigil.onlyWithTag({damage:98}), unstableSigil.onlyWithTag({damage:99}), unstableSigil.onlyWithTag({damage:100}), unstableSigil.onlyWithTag({damage:101}), unstableSigil.onlyWithTag({damage:102}), unstableSigil.onlyWithTag({damage:103}), unstableSigil.onlyWithTag({damage:104}), unstableSigil.onlyWithTag({damage:105}), unstableSigil.onlyWithTag({damage:106}), unstableSigil.onlyWithTag({damage:107}), unstableSigil.onlyWithTag({damage:108}), unstableSigil.onlyWithTag({damage:109}), unstableSigil.onlyWithTag({damage:110}), unstableSigil.onlyWithTag({damage:111}), unstableSigil.onlyWithTag({damage:112}), unstableSigil.onlyWithTag({damage:113}), unstableSigil.onlyWithTag({damage:114}), unstableSigil.onlyWithTag({damage:115}), unstableSigil.onlyWithTag({damage:116}), unstableSigil.onlyWithTag({damage:117}), unstableSigil.onlyWithTag({damage:118}), unstableSigil.onlyWithTag({damage:119}), unstableSigil.onlyWithTag({damage:120}), unstableSigil.onlyWithTag({damage:121}), unstableSigil.onlyWithTag({damage:122}), unstableSigil.onlyWithTag({damage:123}), unstableSigil.onlyWithTag({damage:124}), unstableSigil.onlyWithTag({damage:125}), unstableSigil.onlyWithTag({damage:126}), unstableSigil.onlyWithTag({damage:127}), unstableSigil.onlyWithTag({damage:128}), unstableSigil.onlyWithTag({damage:129}), unstableSigil.onlyWithTag({damage:130}), unstableSigil.onlyWithTag({damage:131}), unstableSigil.onlyWithTag({damage:132}), unstableSigil.onlyWithTag({damage:133}), unstableSigil.onlyWithTag({damage:134}), unstableSigil.onlyWithTag({damage:135}), unstableSigil.onlyWithTag({damage:136}), unstableSigil.onlyWithTag({damage:137}), unstableSigil.onlyWithTag({damage:138}), unstableSigil.onlyWithTag({damage:139}), unstableSigil.onlyWithTag({damage:140}), unstableSigil.onlyWithTag({damage:141}), unstableSigil.onlyWithTag({damage:142}), unstableSigil.onlyWithTag({damage:143}), unstableSigil.onlyWithTag({damage:144}), unstableSigil.onlyWithTag({damage:145}), unstableSigil.onlyWithTag({damage:146}), unstableSigil.onlyWithTag({damage:147}), unstableSigil.onlyWithTag({damage:148}), unstableSigil.onlyWithTag({damage:149}), unstableSigil.onlyWithTag({damage:150}), unstableSigil.onlyWithTag({damage:151}), unstableSigil.onlyWithTag({damage:152}), unstableSigil.onlyWithTag({damage:153}), unstableSigil.onlyWithTag({damage:154}), unstableSigil.onlyWithTag({damage:155}), unstableSigil.onlyWithTag({damage:156}), unstableSigil.onlyWithTag({damage:157}), unstableSigil.onlyWithTag({damage:158}), unstableSigil.onlyWithTag({damage:159}), unstableSigil.onlyWithTag({damage:160}), unstableSigil.onlyWithTag({damage:161}), unstableSigil.onlyWithTag({damage:162}), unstableSigil.onlyWithTag({damage:163}), unstableSigil.onlyWithTag({damage:164}), unstableSigil.onlyWithTag({damage:165}), unstableSigil.onlyWithTag({damage:166}), unstableSigil.onlyWithTag({damage:167}), unstableSigil.onlyWithTag({damage:168}), unstableSigil.onlyWithTag({damage:169}), unstableSigil.onlyWithTag({damage:170}), unstableSigil.onlyWithTag({damage:171}), unstableSigil.onlyWithTag({damage:172}), unstableSigil.onlyWithTag({damage:173}), unstableSigil.onlyWithTag({damage:174}), unstableSigil.onlyWithTag({damage:175}), unstableSigil.onlyWithTag({damage:176}), unstableSigil.onlyWithTag({damage:177}), unstableSigil.onlyWithTag({damage:178}), unstableSigil.onlyWithTag({damage:179}), unstableSigil.onlyWithTag({damage:180}), unstableSigil.onlyWithTag({damage:181}), unstableSigil.onlyWithTag({damage:182}), unstableSigil.onlyWithTag({damage:183}), unstableSigil.onlyWithTag({damage:184}), unstableSigil.onlyWithTag({damage:185}), unstableSigil.onlyWithTag({damage:186}), unstableSigil.onlyWithTag({damage:187}), unstableSigil.onlyWithTag({damage:188}), unstableSigil.onlyWithTag({damage:189}), unstableSigil.onlyWithTag({damage:190}), unstableSigil.onlyWithTag({damage:191}), unstableSigil.onlyWithTag({damage:192}), unstableSigil.onlyWithTag({damage:193}), unstableSigil.onlyWithTag({damage:194}), unstableSigil.onlyWithTag({damage:195}), unstableSigil.onlyWithTag({damage:196}), unstableSigil.onlyWithTag({damage:197}), unstableSigil.onlyWithTag({damage:198}), unstableSigil.onlyWithTag({damage:199}), unstableSigil.onlyWithTag({damage:200}), unstableSigil.onlyWithTag({damage:201}), unstableSigil.onlyWithTag({damage:202}), unstableSigil.onlyWithTag({damage:203}), unstableSigil.onlyWithTag({damage:204}), unstableSigil.onlyWithTag({damage:205}), unstableSigil.onlyWithTag({damage:206}), unstableSigil.onlyWithTag({damage:207}), unstableSigil.onlyWithTag({damage:208}), unstableSigil.onlyWithTag({damage:209}), unstableSigil.onlyWithTag({damage:210}), unstableSigil.onlyWithTag({damage:211}), unstableSigil.onlyWithTag({damage:212}), unstableSigil.onlyWithTag({damage:213}), unstableSigil.onlyWithTag({damage:214}), unstableSigil.onlyWithTag({damage:215}), unstableSigil.onlyWithTag({damage:216}), unstableSigil.onlyWithTag({damage:217}), unstableSigil.onlyWithTag({damage:218}), unstableSigil.onlyWithTag({damage:219}), unstableSigil.onlyWithTag({damage:220}), unstableSigil.onlyWithTag({damage:221}), unstableSigil.onlyWithTag({damage:222}), unstableSigil.onlyWithTag({damage:223}), unstableSigil.onlyWithTag({damage:224}), unstableSigil.onlyWithTag({damage:225}), unstableSigil.onlyWithTag({damage:226}), unstableSigil.onlyWithTag({damage:227}), unstableSigil.onlyWithTag({damage:228}), unstableSigil.onlyWithTag({damage:229}), unstableSigil.onlyWithTag({damage:230}), unstableSigil.onlyWithTag({damage:231}), unstableSigil.onlyWithTag({damage:232}), unstableSigil.onlyWithTag({damage:233}), unstableSigil.onlyWithTag({damage:234}), unstableSigil.onlyWithTag({damage:235}), unstableSigil.onlyWithTag({damage:236}), unstableSigil.onlyWithTag({damage:237}), unstableSigil.onlyWithTag({damage:238}), unstableSigil.onlyWithTag({damage:239}), unstableSigil.onlyWithTag({damage:240}), unstableSigil.onlyWithTag({damage:241}), unstableSigil.onlyWithTag({damage:242}), unstableSigil.onlyWithTag({damage:243}), unstableSigil.onlyWithTag({damage:244}), unstableSigil.onlyWithTag({damage:245}), unstableSigil.onlyWithTag({damage:246}), unstableSigil.onlyWithTag({damage:247}), unstableSigil.onlyWithTag({damage:248}), unstableSigil.onlyWithTag({damage:249}), unstableSigil.onlyWithTag({damage:250}), unstableSigil.onlyWithTag({damage:251}), unstableSigil.onlyWithTag({damage:252}), unstableSigil.onlyWithTag({damage:253}), unstableSigil.onlyWithTag({damage:254}), unstableSigil.onlyWithTag({damage:255}), unstableSigil.onlyWithTag({damage:256})] as IIngredient[];

recipes.removeShaped(<ExtraUtilities:unstableingot>);
recipes.addShaped(stableIngot, [[iron], [stableSigil], [diamond]]);

for x, sil in sigils {

     recipes.addShaped(unstableIngot, [[iron], [sil], [diamond]]);
}
```

This is with Extra Utilities v1.2.6 with the stable ingot having a separate metadata (The crafting would still have return a unstable ingot if MineTweaker was not used).

The script will also work for Extra Utilities v1.2.4, with `val stableIngot = <ExtraUtilities:unstableingot:2>` changed to `val stableIngot = <ExtraUtilities:unstableingot>.withTag({stable:1,superstable:1})`

Upon further testing, I found that the Super Builder wand crafting along with the "empowered" unstable ingot tools added in v1.2.6 will work.

I was not able to specifically remove the recipe that involves only the unstable ingot and pseudo inversion sigil and had to remove the unstable ingot's recipe all together. Which resulted in the long array as I had to re-add the removed recipe.

**Comment by Ianaver** [comment] 2015-06-12 00:38
@SoraZodia try updating ExU since the actual stable ingots have been added as a separate item in 1.2.6 (current)

**Comment by MrGraphic** [comment] 2015-07-08 21:31
Looks like [copygirl/BetterStorage](https://github.com/copygirl/BetterStorage), [MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1442380-betterstorage-0-13-1-126-wip) is suffering from the same issue.
Without RotaryCraft output item ( lock ) get the same tag ( id:number ) as input item ( key ). With RC output items gets random numbers in tag as if they were jusr spawned not crafted. Code is very simple: [LockRecipe.java](https://github.com/copygirl/BetterStorage/blob/master/src/main/java/net/mcft/copy/betterstorage/item/recipe/LockRecipe.java).

**Comment by ReikaKalseki** [comment] 2015-07-08 21:56
It is consistent with what we already saw - something is going through the recipe tables and replacing every recipe object. I have no code to do this myself. The only thing I can think of is that Forge is doing it - I know for a fact it does this to enforce OreDict support, as it broke one of my recipe systems as soon as I put ink sacs in the recipe - possibly triggered by something in RC.

Check your log for anything like "replaced X ore recipes".

I found one line of code that may be responsible (a fairly late OreDict.initVanillaEntries which triggers the recipe replacement). Try v7b when it is released in a few minutes.
@SoraZodia, @McJty

**Comment by MrGraphic** [comment] 2015-07-09 00:04
So, downloaded .b versions. Started MC, crafted both key then lock and...bang! Both items have same tag as they should have!
I did looked also at MagicWood from EU and this one also work as expected. Can we assume that this nasty issue has been finally fixed ? ;)
Congrats man - I'm taking one cookie for myself for digging up ;).

Edit: Same for Stable/unstable ingots :).

**Comment by ReikaKalseki** [comment] 2015-07-09 01:20
FINALLY.

And Forge, fix your f***ing recipe handling. :P

**Closed as completed by ReikaKalseki** 2015-07-09 01:20 UTC
Labels: Fixed, Mod Interaction, RotaryCraft, @&#%?!

**Comment by Builderb0y** [comment] 2015-12-03 01:02
I think this needs to be re-opened, as the issue seems to be present again in V9b. Magical wood and unstable ingots have recipe issues with the same 3 mods installed as before (extra utilities, dragon API, and tinker's construct). I can also confirm the ore recipe replacement in the log files.

[18:45:33] [Client thread/INFO] [FML/]: Replaced 183 ore recipies
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: Replaced 19 ore recipies

**Comment by ReikaKalseki** [comment] 2015-12-03 06:42
What contexts do those lines exist in?

**Comment by Builderb0y** [comment] 2015-12-03 21:20
[18:45:33] [Client thread/INFO] [MinecraftForge/]: Attempting early MinecraftForge initialization
[18:45:33] [Client thread/INFO] [FML/]: MinecraftForge v10.13.4.1558 Initialized
**[18:45:33] [Client thread/INFO] [FML/]: Replaced 183 ore recipies**
[18:45:33] [Client thread/INFO] [MinecraftForge/]: Completed early MinecraftForge initialization
[18:45:33] [Client thread/DEBUG] [FML/]: File /Applications/MultiMC.app/Contents/MacOS/instances/test/minecraft/config/injectedDependencies.json not found. No dependencies injected
[18:45:33] [Client thread/DEBUG] [FML/]: Building injected Mod Containers 

Appears near the beginning of the log. Next one appears much farther down:

[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
**[18:46:01] [Client thread/INFO] [FML/DragonAPI]: Replaced 19 ore recipies**
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: Overriding the vanilla PotionTypes array to allow for potion IDs up to 255 (up from 31).
[18:46:02] [Client thread/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper/DragonAPI]: DragonAPI: Patching class net.minecraft.client.audio.SoundManager
[18:46:02] [Client thread/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper/DragonAPI]: DragonAPI: Successfully applied SOUNDEVENTS ASM handler 1!
[18:46:02] [Client thread/INFO] [Reika.DragonAPI.Libraries.Java.ReikaASMHelper/DragonAPI]: DragonAPI: Successfully applied SOUNDEVENTS ASM handler 2!

**Comment by ReikaKalseki** [comment] 2015-12-03 22:18
What comes before the lines of "****"?

**Comment by Builderb0y** [comment] 2015-12-03 22:29
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: fluxedcrystals not detected in the MC installation. No special action taken.
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: HungerOverhaul not detected in the MC installation. No special action taken.
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: chisel not detected in the MC installation. No special action taken.
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: CarpentersBlocks not detected in the MC installation. No special action taken.
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: HardcoreEnderExpansion not detected in the MC installation. No special action taken.
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: AgriCraft not detected in the MC installation. No special action taken.
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: LiteLoader not detected.
[18:46:01] [Client thread/INFO] [FML/DragonAPI]: DRAGONAPI: Optifine not detected.
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************
[18:46:01] [Client thread/WARN] [FML/DragonAPI]: ****************************************

**Comment by ReikaKalseki** [comment] 2015-12-04 03:09
OK, so this is shortly after the initialization of ModList...that is still very early....
