### ISSUE TITLE
Infinite XP Bug with magnetite ore and Mining well Plus

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#231] opened 2015-09-06 22:11 UTC
As the title states, I found a rather odd interaction between the Miningwellplus from the Quarryplus mod and magnetite ore.

I'm not even sure why this would be happening, as it only seems to happen with magnetite
Anyway here is a video that gives a better look at what's happening than my writing it out. 
https://youtu.be/QlAuhXE-Yyc

**Comment by ljfa-ag** [comment] 2015-09-06 22:36
Wow, this is hilarious ^^

The mining well must be querying the block's drops every tick, which will spawn XP even if the block isn't destroyed: https://github.com/ReikaKalseki/ReactorCraft/blob/master/Blocks/BlockReactorOre.java#L62

I guess getDrops is not supposed to have any side effects. Is there no possibility to achieve XP drops without a hack like this?

**Comment by ReikaKalseki** [comment] 2015-09-06 23:24
I know how to fix this, using removedByPlayer().

**Comment by Reignofmagic** [comment] 2015-09-07 00:51
Well I am glad you know how to fix it.. I almost want to use it, but it is so darn cheaty haha

**Comment by Reignofmagic** [comment] 2015-09-07 01:49
@ReikaKalseki 

After some further testing most of your ores have this interaction. I logged back onto my test world and had 1 fps instead of 200~ due to the amount of xp orbs

**Comment by ljfa-ag** [comment] 2015-09-07 09:20
I just tested it with Steve's Factory Manager: Place a magnetite ore in front of a block gate and then attach an itemduct (or anything that scans the block gate's inventory) to it.
The itemduct asks for the block gate's inventory and that will call getDrops on the block as well.

**Comment by TomeWyrm** [comment] 2015-09-07 16:29
Personal nitpick unrelated to the issue: His name is pronounced "Ray ka" not "Ree ka"

**Comment by ReikaKalseki** [comment] 2015-09-07 17:23
I wonder if this is the cause behind an issue with millions of XP orbs we saw with the Digital Miner on my 1.6.4 server for a couple hours...

**Comment by ReikaKalseki** [comment] 2015-09-07 19:16
Fixed in two mods.

**Closed as completed by ReikaKalseki** 2015-09-07 19:16 UTC
Labels: Fixed, Lag/FPS, ReactorCraft, ElectriCraft, Exploit, Stupid Code

**Comment by Reignofmagic** [comment] 2015-09-07 20:16
@TomeWyrm Ah, good to know. I shall remember this.

@ReikaKalseki Good to hear, glad it was a simple~ fix.
