### ISSUE TITLE
v11a: Reika.DragonAPI.Exception.WTFException: Someone did something really stupid:

### ISSUE THREAD

**Issue by Schadrach** [ReikaKalseki/Reika_Mods_Issues#643] opened 2016-02-25 12:20 UTC
After getting my server back up and running after #642, I grabbed some spare info fragments from a chest to get the new recipes, grabbed my chromic lexicon from a bibliocraft bookshelf, and the client crashed upon shift-right-clicking the lexicon:

http://pastebin.com/zkxYxNQk

Spawned in a new lexicon and it seemed to work without issue, it's just the existing one I had stashed in a bookshelf that triggers the crash. It was at 160/161 before the update to v11a, in case that is relevant.

**Comment by ReikaKalseki** [comment] 2016-02-25 21:08
You got a fragment mapped to an unobtainable lexicon entry (one of the two that come "premade" with the book). How?

**Comment by Schadrach** [comment] 2016-02-26 01:58
I honestly don't know.  It was my starter chromic lexicon, it was left in a bookcase before the update, after the update it triggered the crash.  It worked fine before the update, and crashed the moment I tried to open it to add fragments after.

I took a server backup before I updated, dunno if there might be anything in it that might enlighten you.

**Comment by ReikaKalseki** [comment] 2016-02-26 01:59
Maybe old books got corrupted?

**Comment by ReikaKalseki** [comment] 2016-03-02 08:45
Any more info?

**Comment by Schadrach** [comment] 2016-03-03 19:46
Nothing useful.  After I replaced the book, I've seen no further issues, and no one else has complained about it on my private server.

**Comment by ReikaKalseki** [comment] 2016-03-03 23:10
I am going to close this for now, since it may be a one-off error.

**Closed as completed by ReikaKalseki** 2016-03-03 23:10 UTC
Labels: Can't Reproduce, ChromatiCraft, Crash, @&#%?!

**Comment by PaladinOne** [comment] 2016-08-17 19:43
Necroing this because I just hit it. It seems to have been caused by some fragment getting corrupted in reeeeeally old books. (i.e. I had a book from v5a that I just tried to modify in v15a.) The book can still be opened and read, but attempting to sneak-rightclick open it to add additional Fragments results in this crash.

Edit:
Making a new book then pulling in all the old fragments via Recovery does not bug out the new book, so in the end there's probably nothing to do here.
