### ISSUE TITLE
Forestry 4.0 Compatibility

### ISSUE THREAD

**Issue by d-leb** [ReikaKalseki/Reika_Mods_Issues#287] opened 2015-09-28 03:05 UTC
Incompatibility between Forestry 4.0.0 and Dragon API 8g.

**Comment by ReikaKalseki** [comment] 2015-09-28 06:34
Seriously? Did you look at the closed issues? It was reported less than 12 hours ago (#285) and that in turn is a duplicate of #229.

Also, @TomeWyrm: I suspect these are going to grow ever more common. What am I supposed to do?

**Closed as completed by ReikaKalseki** 2015-09-28 06:34 UTC
Labels: Duplicate

**Comment by d-leb** [comment] 2015-09-28 11:24
Whoops. I apologize - It was late, only scanned the open issues.

EDIT: I'm a dolt. It didn't dawn on me just to type "Forestry" in the filter string before I made my issue post.

**Comment by ReikaKalseki** [comment] 2015-09-28 19:35
Well, you are far from alone...

**Comment by TomeWyrm** [comment] 2015-09-29 05:30
Not sure... this kind of thing is one of the biggest problem with major mods. Can you detect forestry 4, and disable all integration code for it?

**Comment by ReikaKalseki** [comment] 2015-09-29 07:06
Far from easily.

**Comment by TomeWyrm** [comment] 2015-09-29 07:10
Can you give a unique crash for mod integration mismatches? Like "You're using an unsupported mod version. Check the mod name on github to see if it's been reported"

You're not going to catch all of them, but if they DO post here, we can be safe in our position of "we TOLD you what was wrong. Please learn to read"

**Comment by d-leb** [comment] 2015-09-29 11:09
Not to throw in a wrench, but the reason why I posted here is because it was suggested on Forestry's Github to alert Reika of the issue. That's why some people may be jumping over here. It was less meant as "it's broke" and more of a PSA. 4.x is now in beta release, no longer dev only - so I expect all authors with integration to start being hounded by users. But you probably already know this and that 3.x is now feature frozen and will only be receiving bug fixes.

It ultimately comes down to the user (myself) not using the filter on GitHub and instead trying to eyeball the issue from a list of a few hundred. Is there a way to include a note to the user when creating an issue such as "BE SURE TO FILTER FOR YOUR ISSUE FIRST" as a reminder? It may useful for people who are half asleep.

As far as the debug messages, you are correct. The debug messages are the first think I check. Either the descriptive handled exception/log message or the stack trace. However, also correct, not everyone will read those. For users such as myself though, they are helpful and are welcome.

The second thing I looked for was a config option to disable the integration. I couldn't find any. If I did fine one, I probably wouldn't have even bothered posting here as Forestry is such a well known mod that you would have eventually made a release to include support for the 4.x version.

**Comment by ReikaKalseki** [comment] 2015-09-29 18:33
> Can you give a unique crash for mod integration mismatches? Like "You're using an unsupported mod version. Check the mod name on github to see if it's been reported"

Yes, but I do not expect that to go over well. Then again, seeing as it crashes _anyways_...
Also, I do not want to have to manually update the required version in the error, because I _will_ forget.

> Not to throw in a wrench, but the reason why I posted here is because it was suggested on Forestry's Github to alert Reika of the issue. That's why some people may be jumping over here. It was less meant as "it's broke" and more of a PSA. 4.x is now in beta release, no longer dev only - so I expect all authors with integration to start being hounded by users. But you probably already know this and that 3.x is now feature frozen and will only be receiving bug fixes.

The problem is that - from my testing - it appears that Forestry 4.x uses 3.5.x's API. So when I updated my API from 3.5.x to 3.6.x in v8 - something I was promised that I would not have to do, by the way - it broke 4.x as well.

_Worse_, another 4.x release is coming soon with major world damage and more API changes. So even if I update now, I will have to do so again in the next few weeks, and this time with half the player base refusing to go along.

> It ultimately comes down to the user (myself) not using the filter on GitHub and instead trying to eyeball the issue from a list of a few hundred. Is there a way to include a note to the user when creating an issue such as "BE SURE TO FILTER FOR YOUR ISSUE FIRST" as a reminder? It may useful for people who are half asleep.

It already does. When posting the issue, above your text box, there is a "read the readme" box with a link.

> The second thing I looked for was a config option to disable the integration. I couldn't find any. If I did fine one, I probably wouldn't have even bothered posting here as Forestry is such a well known mod that you would have eventually made a release to include support for the 4.x version.

This has two problems, mostly revolving around the fact that if I start giving config options to turn off mod integration, people are going to start asking for configs for _all_ of it:

The first is implementation. As it happens, bees are indeed something I could make selectively enableable because they are only referenced from the main mod classes (for initialization). However, most mod integration cannot be, as it is in the form of interfaces on machines/items/blocks, active running code in updateEntity() on machines, or similar. Yes, I could make the "isModLoaded()" checks version- specific, but that then requires I be intimately familiar with every mod's versions, which for [some 120 mods](https://github.com/ReikaKalseki/DragonAPI/blob/master/ModList.java#L28) is far from reasonable. On top of that it would require edits in some 1800+ places, few of which I remember. Good luck explaining this to someone demanding the ability to disable, say, AE integration, but who knows nothing about programming and thinks it works by writing plaintext "so when the user does X give them Y" into a text box.

The second is usage. Though I have no problem with people disabling modules due to version conflicts - they would not work anyways - I do not want them playing "pick and choose" outside of that. I went to great lengths to add all of this integration, and some 30% of my mods' content is integration-based. I do not want to resurrect - if in a different form - the old issue of "looks OP, disable it"/"don't care, disable it" that was so much of an issue with RotaryCraft machines. On top of that, if people start disabling modules left and right, it is going to cause users to get confused and start reporting "cannot harvest crop"/"item doesn't work"/etc type issues, and I am probably going to waste hours tracking down what I thought were API or version issues.

**Comment by d-leb** [comment] 2015-09-29 19:55
> It already does. When posting the issue, above your text box, there is a "read the readme" box with a link.

_hangs head_  I didn't notice the link. What I should do is make sure I don't make a post when I'm so tired that I practically need to face roll to hit the enter key.

Regarding the integration settings - yeah .. I can understand both angles - and even more of a nightmare when dealing with an ever growing/aging code base of your own ideas and adding integration of other APIs.

**Comment by TomeWyrm** [comment] 2015-09-30 03:38
_sigh_

Who is doing Forestry now? Because they need a yelling at if they don't have good reasons for reverting the API and then making a NEW one

**Comment by mezz** [comment] 2015-09-30 05:17
@ReikaKalseki  Forestry 4.0 is not using an older API. Forestry's API versioning is per-package using [SemVer](http://semver.org/) and is not tied to the mod version number.

There are many internal changes in this release, especially to wood items and multiblocks.
There are API changes as well (mainly removing deprecated things).
