### ISSUE TITLE
[CC] Crash on startup

### ISSUE THREAD

**Issue by Shahelion** [ReikaKalseki/Reika_Mods_Issues#592] opened 2016-01-20 23:40 UTC
The only thing that changed since the last successful startup was I updated Immersive Engineering and the two add-ons. But this says it's something with ChromatiCraft research so I have no idea.

https://gist.github.com/Zsashas/3b0670b157a2e1c73c03

**Comment by ReikaKalseki** [comment] 2016-01-21 05:01
Try removing mods; possible duplicate of #585.

**Comment by Shahelion** [comment] 2016-01-21 05:27
The next time it started up fine so I have no idea.

**Comment by Shahelion** [comment] 2016-01-21 06:46
I'm in the process of testing several mod updates. Each time I updated a mod, it crashes the first time then launches successfully after.

Mods that I've updated to latest versions:
Applied Energistics
~Thaumic Energistics
Immersive Engineering
~Immersive Integration
Aether II
~Gilded Games Utils
Botanical Addons
Avaritia

Absolutely no connection that I can see.

**Comment by ReikaKalseki** [comment] 2016-01-21 18:43
....

**Closed as completed** 2016-01-21 18:43 UTC
Labels: Mod Interaction, Can't Reproduce, API Versions

**Comment by Shahelion** [comment] 2016-01-22 00:24
Happened again after removing Vazkii's Ambience mod. Again, just once, then launched normally. It really does NOT like me adding or removing mods. (Did not happen when I added Ambience, however)

**Comment by ReikaKalseki** [comment] 2016-01-22 02:01
wtf...

**Comment by Shahelion** [comment] 2016-02-07 18:28
Did not happen with RFTools (likely because it didn't load fully due to missing CoFHLib) but once I added CoFHLib, it happened again. I guess it has to load far enough before it can crash.

**Comment by ReikaKalseki** [comment] 2016-02-07 20:28
Something in CC (possibly a mod interaction item) is failing to initialize.

**Comment by Shahelion** [comment] 2016-02-08 09:11
Definitely connected to the modlist changing, as I have only ever had this happen when adding or removing mods (happened again while removing the Zelda Sword Skills Addon). Maybe it's making it re-check the list of mods installed to look for compatibility, and that's where it fails? Then afterwards it already knows the list, so doesn't crash anymore.

Although, the only mod interactions that I know of with CC are Thaumcraft...stuff (so much stuff), Mystcraft and Twilight Forest progression, and Witchery and Ars Magica logs with dye trees (the rest are all disabled except vanilla). Also, the crash reports mention research, which seems to discard the logs being the cause.

Speaking of the logs, the list includes Force logs. Is that the Force trees from Dartcraft? Because that doesn't exist for 1.7.10.

**Comment by Aivech** [comment] 2016-02-08 11:44
He's using Applied Energistics rv3. I had the exact same crash.

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/599

Downgrade Applied Energistics to rv2.stable build 10 as well as Thaumic Energistics. I do not know what the correct version of Thaumic Energistics is, but if you are not against doing this kind of thing it can be found in the latest version of the Revolution|2 modpack on the ATLauncher.

AE2 rv2.stable build 10 can be found here: http://ae-mod.info/Downloads/

**Comment by Shahelion** [comment] 2016-02-13 04:39
After removing Thaumic Energistics (and several other mods that I never used to make room for something) this is the first time that another mod other than Chromaticraft has also had UCHE in the crash report. Gadomancy apparently also errored this time, but otherwise the crash report is the same.

Just thought it was interesting that it finally flagged another mod as erroring.

The mod in question: http://minecraft.curseforge.com/projects/gadomancy

**Comment by ReikaKalseki** [comment] 2016-02-13 10:11
What is Gadomancy?

**Comment by Aivech** [comment] 2016-02-13 19:34
It lets you mess with nodes, as well as open a special Eldritch portal that is guaranteed not to drop you in the void but once you enter, you cannot leave.

(It's another Thaumcraft addon)

**Comment by ReikaKalseki** [comment] 2016-02-13 21:09
I doubt that has an AE integration, making this rather more confusing.
