### ISSUE TITLE
DRAGONAPI ERROR: Detected invalid ME system when running Reika.ChromatiCraft.Magic.Artefact.UABombingEffects

### ISSUE THREAD

**Issue by KuroPeach** [ReikaKalseki/Reika_Mods_Issues#1995] opened 2018-11-19 13:26 UTC
[Log](https://paste.ubuntu.com/p/32QmqdJjYr/) , i cant find any Unknown Artefact at player ME systeam , Server logs are printing this [Log](https://paste.ubuntu.com/p/32QmqdJjYr/) very fast , seven hour will 14G , My cloud server hard drive is bursting . 
Use chc new , AE rv3 ,

**Comment by OvermindDL1** [comment] 2018-11-19 18:02
Huh, well this line is bugged (not Reika's fault, just because of how appeng is coded breaks the usual Java style):
https://github.com/ReikaKalseki/DragonAPI/blob/master/ModInteract/DeepInteract/MESystemReader.java#L111
```java
		isEmpty = nodes.isEmpty() || (nodes.size() == 1 && nodes.iterator().next() == node);
```
So conceptually this sets `isEmpty` to true if `nodes.isEmpty()` or if `nodes.size()==1` and `nodes.iterator().next() == node`, however appeng's iterator that this is iterating here is at https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv3-1.7.10/src/main/java/appeng/me/GridNodeIterator.java and as you can see in the constructor it *already* calls `hasNext()` and `next()` for whatever reason (this whole file is a whole lot of wtf'ery)...  So in essence the AppEng iterator is skipping the first element, and it's private so without reflection you can't access it anyway, so when `nodes.size()==1` then `nodes.iterator().next()` will *always* fail with an exception, so I'm not sure how this code ever worked on the latest 1.7.10 version of appeng (rv3).

Reika should probably calculate `isEmpty` some other way in other words because appeng is doing wtf'ery.

**Comment by KuroPeach** [comment] 2018-11-20 01:05
Oh, thank you, I don't understand very well, I will try rv2 later.

**Comment by ReikaKalseki** [comment] 2018-11-20 16:25
It usually *does* work; I strongly suspect the invalid ME systems do not correspond to "real, in-world" ones.

**Comment by KuroPeach** [comment] 2018-11-21 03:44
I failed, the rv2 version will still be crazy to print the log, he usually comes with the player online or offline, but sometimes not, now I can only set 4h to restart the server and clean up the log, forgive my bad English, Google is very awesome

**Comment by KuroPeach** [comment] 2018-12-04 06:56
I found out what is the problem, is the problem of AE2stuff's wireless access device, its record in the AE system will be inexplicably doubled, I used 2, I accidentally found it shows 8 in AE, and some The player's AE system used 12, but the display became more than 1000. So there are some fake AE systems.

**Comment by ReikaKalseki** [comment] 2018-12-04 17:26
That certainly sounds plausible. That is for them to fix.

**Comment by huntert98** [comment] 2019-01-20 23:12
Do we know explicitly what is causing this problem? I've had log files in excess of 200 GB and tons of lag. @Leaveleaf which item are you talking about causing the problem and did you find a solution? Thanks guys!

**Comment by Barhandar** [comment] 2019-03-06 08:03
>will always fail with an exception

Is it possible to check for said exception instead?

**Comment by BlueAgent** [comment] 2019-03-07 08:22
Both mods Applied Energistics 2 and AE2 stuff involved aren't being maintained on 1.7.10 anymore, so a bug fix on their end probably won't be released, realistically.
Could you please add an option to hide the exceptions from being logged?

**Comment by KuroPeach** [comment] 2019-03-07 08:54
Can't fix it, even if there is no reika mod, it will be have this problem. All I can do is stop the player from using the ‘AE2 stuff’ wireless connector.forgive my bad English

**Comment by OvermindDL1** [comment] 2019-03-08 15:29
@BlueAgent 	Point me to their public source and I could probably fix it.  If you could give an exact set of reproducible steps and a save that causes it then I could test it in the dev environment since it's pretty easy to get reika's mods working in dev for me.  Just hound me to do it, my free time is sporadic so you have to catch me at the right time.  ^.^;

**Comment by DracoScythem** [comment] 2019-03-08 17:27
The underlying issue with this is a unique "feature" of AE2s GridNodeIterator which (in violation of the Iterator interface spec) uses the `hasNext()` call to change the internal Iterator state, rendering https://github.com/ReikaKalseki/DragonAPI/blob/1b6cbcbeaf13fe15f4b75687c685ce89bc2a3514/ModInteract/DeepInteract/MESystemReader.java#L113 
> isEmpty = nodes.isEmpty() || (nodes.size() == 1 && nodes.iterator().next() == node);

invalid (the `next()` call can fail even though the Iterator isn't exhausted).

A functionally identical replacement that accomodates for that behavior would be
> GridNodeIterator iterator = nodes.iterator();
> isEmpty = !iterator.hasNext() || (iterator.next() == node && nodes.size() == 1);

**This assumes MESystemReader.isEmpty isn't set in a similar fashion elsewhere!** (If it is, those calls might require changes as well, but that'd have to be checked in-workspace)

**Comment by OvermindDL1** [comment] 2019-03-08 23:32
@DracoScythem Yeah that's what I gathered in https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1995#issuecomment-439986499 too, it's very unusual what appeng is doing...  o.O

**Comment by BlueAgent** [comment] 2019-03-11 16:20
@OvermindDL1 The issue is on AE2's side like @DracoScythem mentioned and you're apparantly aware of. AE2 isn't even accepting pull requests for 1.7.10 though, so it's unlikely your fix would be released officially. Given all that, not sure how having Reika's mods in a dev environment would be useful for this issue since there's nothing to fix on Reika's end, just a request to hide the exception from logging as an option. If @DracoScythem 's suggested changes work it'd be great as well. Anything that stops log files from growing huge and reducing disk I/O is good enough for me.

Mod List:
- ae2stuff-rv3-0.5.1.9-mc1.7.10
- appliedenergistics2-rv3-beta-6
- bdlib-1.9.4.109-mc1.7.10
- ChromatiCraft 1.7.10 V22d
- DragonAPI 1.7.10 V22d
- forge-1.7.10-10.13.4.1614
- ReactorCraft 1.7.10 V22a
- RotaryCraft 1.7.10 V22d

Steps to reproduce:
1. Teleport 1k blocks away from spawn
2. In one chunk, place a creative cell, ME chest (with unknown artefact and/or waste stored inside) and a wireless connector.
3. In second chunk place another wireless connector and bind them together.
4. Unload the chunks gradually by moving in the direction chunk 1 to chunk 2.
5. Return and check that the connectors are logically duplicated with a network tool.
6. Break the connectors followed by the ME chest.
7. The exception should start being logged till the creative cell is broken or server is restarted.

[Video Demonstration](https://youtu.be/OU5tUsbb8qE)

**Comment by OvermindDL1** [comment] 2019-03-11 19:39
> so it's unlikely your fix would be released officially.

Officially or not, would still fix it for the people that look for it.

> not sure how having Reika's mods in a dev environment would be useful for this issue since there's nothing to fix on Reika's end

Makes it trivial to replicate the exact error so I can also verify a fix at the same time without needing to wait for rebuilds and reloads and so forth.

**Comment by BlueAgent** [comment] 2019-03-12 03:34
> Officially or not, would still fix it for the people that look for it.

The people that are actively looking but don't want to use unofficial builds would have no resolution. If AE2 and/or AE2Stuff was still being developed for 1.7.10 then reporting it to them would be best (although the AE2Stuff bug was reported, wasn't ever fixed for 1.7.10 though). A bandaid fix or hiding logs on Reika's side is basically the only hope right now for a solution that sticks to official sources.

> Makes it trivial to replicate the exact error so I can also verify a fix at the same time without needing to wait for rebuilds and reloads and so forth.

I could see that for Draco's suggested fix, or any fix on DragonAPI for that matter. I too have Reika's mods in a dev environment. Wrongly assumed by fix you meant the core issue that you mentioned with AE2 breaking contract.

Anyways a reproducible setup was demonstrated in my previous message as requested. Hope that helps.

**Comment by OvermindDL1** [comment] 2019-03-12 14:13
> Anyways a reproducible setup was demonstrated in my previous message as requested. Hope that helps.

Always a good first step.  However, do need the appeng repo, not motivated enough to decompile it and setup a workspace considering I pretty much just play factorio anymore.  ^.^;

**Comment by Thorinair** [comment] 2019-06-18 21:52
Any update on this? I just had this start happening to me, yet noone seems to use wireless on the server...

**Comment by ReikaKalseki** [comment] 2019-06-19 15:41
I am pretty sure I implemented Draco's code change above for the next version.

**Comment by Thorinair** [comment] 2019-06-22 20:26
I have actually found another way to cause this error to appear. I am aware that a fix is coming, but I still figured it might be worth mentioning. This is the situation on my server where I have observed it:

1) I have the RotaryCraft Worktable touching an ME Smart Cable.
2) If I go away from my base for some time and then return, the error will start appearing
3) Another "instance" of this error will be added to the output for every leaving and returning (double spam, tripple spam, etc)
4) Chunk loading doesnt seem to help fix the problem

I have fixed it by simply moving the Worktable 1 block away so it no longer touches the cable. The work table is now placed on a diagonal block from it.

**Comment by ReikaKalseki** [comment] 2019-06-23 01:00
wtf...

**Comment by Aivech** [comment] 2019-08-18 02:08
I am getting this error as well. I do not have any functional ME system running, though I do have a controller and some blocks placed, and some AE2stuff processing blocks (crystal growth chamber and advanced inscriber) connected to an energy acceptor attached to an RF cable.) 

Notably, it started happening for no obvious reason at some point after getting the multiblock casting progress (may not be related)

**Comment by ReikaKalseki** [comment] 2019-08-19 00:00
It is not related, no.

**Comment by ReikaKalseki** [comment] 2019-10-01 01:11
Fixed...again.

**Closed as completed by ReikaKalseki** 2019-10-01 01:11 UTC
Labels: Bug, Fixed, Other Mod's End
