### ISSUE TITLE
Chromaticraft creates a strange pixel noise in far away block rendering

### ISSUE THREAD

**Issue by midorlo** [ReikaKalseki/Reika_Mods_Issues#1158] opened 2016-10-16 11:21 UTC
Summary: 

Hard to describe. The block rendering differs when chromaticraft is loaded. There is a strange pixel noise present that really disturbs me from keeping a visual focus. (Edit for clearance: Nothing you could actually oversee). A screenshot won't really help here since the pixel noise affects the moving screen only. Disabling Chromaticraft solves the issue. DragonAPI does not cause the issue when used alone.

Complete Modlist to Minecraft 1.7.10: 
- Forge 1614
- DragonAPI V16D
- Chromaticraft V16D

Setup:
- i5-6500
- RX470
- Win10, Java8x64

OS, Drivers and JRE are at current versions in stable branches. No "optimizers" and comparable crapware running (Besides Curse spawning the MCLauncher). Nothing done to Crimson. Using default MCOptions (and tried various variants)

**Comment by ReikaKalseki** [comment] 2016-10-16 18:17
When CC is installed, FastCraft disables mipmapping.

**Comment by Builderb0y** [comment] 2016-10-16 22:35
AFAIK fastcraft only disables it when a mod adds a texture that's smaller than 16x16. (specifically it limits mipmapping to whatever level compresses the "smallest" texture to 1x1), so if a mod registers a texture that's 4x4, then fast craft limits mipmapping to 2 levels. Does CC have any textures that are smaller than 16x16?

**Comment by midorlo** [comment] 2016-10-17 02:24
There is no fastcraft present in my test. It's Minecraft, Forge, DragonAPI and Chromaticraft.

**Comment by ReikaKalseki** [comment] 2016-10-17 07:54
> Does CC have any textures that are smaller than 16x16?

Yes, a 1x1.

**Comment by Builderb0y** [comment] 2016-10-17 23:13
I would suggest scaling that one up to 16x16 to see if that fixes it.

**Comment by ReikaKalseki** [comment] 2016-10-18 00:18
I see no reason to make a flat-color image 16x16, especially when fastcraft is entirely the cause of this issue.

**Comment by TheGuyRunningSouth** [comment] 2016-10-18 00:18
Didn't OP say that they don't have fastcraft installed?

**Comment by ReikaKalseki** [comment] 2016-10-18 00:31
Then...I have no idea. Because every past report has, and once someone even found a log message where FastCraft said it was doing exactly that.

**Comment by midorlo** [comment] 2016-10-18 08:02
Trying to make my error report more accessible: 

https://gfycat.com/MarvelousClumsyFirebelliedtoad

In this html5 video I demonstrate the visual glitch. Notice the pixel noise on the leafes. Loaded mods are only DragonAPI and Chromaticraft. Setup as described. No other mods have ever touched the filetree of the testpack (aka. there are no leftover asms from Fastcraft, Optifine aso.)

https://gfycat.com/OblongPlumpLabradorretriever

This is a reference video. Loaded mods are DragonAPI only. Notice the pixel noise being gone. The very little pixel noise left comes from video encoding. The is no actual pixel noise when playing live.

In both videos, I also showoff to be using the default minecraft video settings. (Please excuse everything to be a little dark. I just taught myself howto record, demux and where to publish a desktop recording for the sake of this bugreport.)

Furthermore I was yet able to reproduce the problem on another system (basically just a different GPU):
i5-6500, R9-260, 8G-DDR4, Win10x64, JRE8x64; Updated in stable branches; No crapware etc. running;

**Comment by HellFirePvP** [comment] 2016-10-18 10:41
@Builderb0y did you actually test that yesterday with the changed texture?

**Comment by Builderb0y** [comment] 2016-10-18 23:56
> @Builderb0y did you actually test that yesterday with the changed texture?

I did. Scaling the texture up to 16x does indeed fix it.

> someone even found a log message where FastCraft said it was doing exactly that.

Perhaps it's vanilla mipmapping code that's breaking and fastcraft is just logging it?

**Comment by midorlo** [comment] 2016-10-19 14:16
@Builderb0y , may you share your workaround with me?

**Comment by ReikaKalseki** [comment] 2016-10-19 19:26
It will be in the next version.

**Comment by Builderb0y** [comment] 2016-10-20 03:45
> @Builderb0y , may you share your workaround with me?

Sure. https://www.dropbox.com/s/i7oito7hb74i9lj/mipmapfix.zip?dl=0

**Closed as completed** 2017-01-18 22:13 UTC
Labels: ChromatiCraft
