### ISSUE TITLE
Probbably an issue with DragonAPI and Forestry 4.0

### ISSUE THREAD

**Issue by Filvandrel** [ReikaKalseki/Reika_Mods_Issues#285] opened 2015-09-27 16:35 UTC
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 27.09.15 17:27
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError
at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.AbstractMethodError
at forestry.apiculture.genetics.BeeHelper.registerMutation(BeeHelper.java:244)
at Reika.DragonAPI.ModInteract.Bees.BeeSpecies.addBreeding(BeeSpecies.java:313)
at Reika.DragonAPI.ModInteract.Bees.BeeSpecies.addBreeding(BeeSpecies.java:294)
at Reika.RotaryCraft.RotaryCraft.postload(RotaryCraft.java:510)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 617981240 bytes (589 MB) / 1474916352 bytes (1406 MB) up to 9650569216 bytes (9203 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn125M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 172 mods loaded, 172 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJ mcp{9.05} Minecraft Coder Pack 
UCHIJ FML{7.10.99.99} Forge Mod Loader 
UCHIJ Forge{10.13.4.1492} Minecraft Forge 
UCHIJ appliedenergistics2-core{rv2-stable-10} AppliedEnergistics2 Core 
UCHIJ CodeChickenCore{1.0.6.43} CodeChicken Core 
UCHIJ ivtoolkit{IvToolkit} 1.2 
UCHIJ Micdoodlecore{} Micdoodle8 Core 
UCHIJ NotEnoughItems{1.0.4.107} Not Enough Items 
UCHIJ OpenComputers|Core{1.5.18.36} OpenComputers (Core) 
UCHIJ technomCore{0.12.0A} Technomancy Core 
UCHIJ ThaumicTinkerer-preloader{0.1} Thaumic Tinkerer Core 
UCHIJ WitchingGadgetsCore{1.1.9} Witching Gadgets Core 
UCHIJ OpenModsCore{0.8} OpenModsCore 
UCHIJ {000} CoFH ASM 
UCHIJ {0} DragonAPI ASM Data Initialization 
UCHIJ debug{1.0} debug 
UCHIJ battlegear2{1.7.10} Mine & Blade Battlegear 2 - Bullseye 
UCHIJ bspkrsCore{6.15} bspkrsCore 
UCHIJ ArmorStatusHUD{1.28} ArmorStatusHUD 
UCHIJ StatusEffectHUD{1.27} StatusEffectHUD 
UCHIJ Baubles{1.0.1.10} Baubles 
UCHIJ adventurebackpack{1.7.10-0.8b} Adventure Backpack 
UCHIJ AgriCraft{1.7.10-1.4.0-beta-3} AgriCraft 
UCHIJ AncientWarfare{2.4.112-beta-MC1.7.10} Ancient Warfare Core 
UCHIJ CoFHCore{1.7.10R3.0.3} CoFH Core 
UCHIJ BuildCraft|Core{7.1.3} BuildCraft 
UCHIJ AncientWarfareAutomation{2.4.112-beta-MC1.7.10} Ancient Warfare Automation 
UCHIJ AncientWarfareNEIPlugin{2.4.112-beta-MC1.7.10} Ancient Warfare NEI Plugin 
UCHIJ AncientWarfareNpc{2.4.112-beta-MC1.7.10} Ancient Warfare NPCs 
UCHIJ AncientWarfareStructure{2.4.112-beta-MC1.7.10} Ancient Warfare Structures 
UCHIJ appliedenergistics2{rv2-stable-10} Applied Energistics 2 
UCHIJ AquaTweaks{1.0} AquaTweaks 
UCHIJ asielib{0.4.2} asielib 
UCHIJ ATG{0.10.0} Alternate Terrain Generation 
UCHIJ MineFactoryReloaded{1.7.10R2.8.0} MineFactory Reloaded 
UCHIJ Thaumcraft{4.2.3.5} Thaumcraft 
UCHIJ MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} MFR Compat: Thaumcraft 
UCHIJ Waila{1.5.10} Waila 
UCHIJ Automagy{0.26.3} Automagy 
UCHIJ betterstorage{0.13.1.126} BetterStorage 
UCHIJ BiblioCraft{1.11.2} BiblioCraft 
UCHIJ ThermalFoundation{1.7.10R1.2.0} Thermal Foundation 
UCHIJ ThermalExpansion{1.7.10R4.0.3B1} Thermal Expansion 
UCHIJ BigReactors{0.4.3A} Big Reactors 
UCHIJ Mantle{1.7.10-0.3.2.jenkins188} Mantle 
UCHIJ Natura{2.2.0} Natura 
UCHIE BiomesOPlenty{2.1.0} Biomes O' Plenty 
UCHIJ AWWayofTime{v1.3.3} Blood Magic: Alchemical Wizardry 
UCHIJ qmunitylib{1.0} QmunityLib 
UCHIJ bluepower{0.2.962} Blue Power 
UCHIJ Botania{r1.7-223} Botania 
UCHIJ BuildCraft|Builders{7.1.3} BC Builders 
UCHIJ BuildCraft|Transport{7.1.3} BC Transport 
UCHIJ BuildCraft|Energy{7.1.3} BC Energy 
UCHIJ BuildCraft|Silicon{7.1.3} BC Silicon 
UCHIJ BuildCraft|Robotics{7.1.3} BC Robotics 
UCHIJ BuildCraft|Factory{7.1.3} BC Factory 
UCHIJ IC2{2.2.763-experimental} IndustrialCraft 2 
UCHIJ Forestry{4.0.0.27} Forestry for Minecraft 
UCHIJ BuildCraft|Compat{7.0.12} BuildCraft Compat 
UCHIJ CarpentersBlocks{3.3.7} Carpenter's Blocks 
UCHIJ ChickenChunks{1.3.4.17} ChickenChunks 
UCHIJ Railcraft{9.7.0.0} Railcraft 
UCHIJ TwilightForest{2.3.7} The Twilight Forest 
UCHIJ UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} Universal Electricity 
UCHIJ ForgeMultipart{1.2.0.345} Forge Multipart 
UCHIJ chisel{2.5.1.44} Chisel 2 
UCHIJ ComputerCraft{1.74} ComputerCraft 
UCHIJ Mystcraft{0.12.3.00} Mystcraft 
UCHIJ ExtraUtilities{1.2.11} Extra Utilities 
UCHIJ ImmersiveEngineering{0.5.4} Immersive Engineering 
UCHIJ TConstruct{1.7.10-1.8.7.build979} Tinkers' Construct 
UCHIJ DragonAPI{1.0} DragonAPI 
UCHIJ eplus{1.7.10-3.0.1} Enchanting Plus 
UCHIJ endercore{1.7.10-0.1.0.24_beta} EnderCore 
UCHIJ EnderIO{1.7.10-2.3.0.415_beta} Ender IO 
UCHIJ EnderStorage{1.4.7.36} EnderStorage 
UCHIJ ExtraTiC{1.4.5} ExtraTiC 
UCHIJ factorization.notify{1.0} Factorization Notification System 
UCHIJ factorization.dimensionalSlice{0.8.95} Factorization Dimensional Slices 
UCHIJ factorization{0.8.95} Factorization 
UCHIJ factorization.misc{0.8.95} Factorization Miscellaneous Nonsense 
UCHIJ farseek{1.0.9} Farseek 
UCHIJ FastCraft{1.21} FastCraft 
UCHIJ Steamcraft{0.28.10} Flaxbeard's Steam Power 
UCHIJ GalacticraftCore{3.0.12} Galacticraft Core 
UCHIJ GalacticraftMars{3.0.12} Galacticraft Planets 
UCHIJ GraviSuite{1.7.10-2.0.3} Graviation Suite 
UCHIJ Growthcraft{2.1.0a} Growthcraft 
UCHIJ Growthcraft|Cellar{2.1.0a} Growthcraft Cellar 
UCHIJ Growthcraft|Apples{2.1.0} Growthcraft Apples 
UCHIJ Growthcraft|Bamboo{2.1.0} Growthcraft Bamboo 
UCHIJ Growthcraft|Bees{2.1.0} Growthcraft Bees 
UCHIJ Growthcraft|Fishtrap{2.1.0a} Growthcraft Fishtrap 
UCHIJ Growthcraft|Grapes{2.1.0} Growthcraft Grapes 
UCHIJ Growthcraft|Hops{2.1.0} Growthcraft Hops 
UCHIJ Growthcraft|Rice{2.1.0a} Growthcraft Rice 
UCHIJ guideapi{1.7.10-1.0.1-20} Guide-API 
UCHIJ IC2NuclearControl{2.2.5a-GoingForTheKill} Nuclear Control 2 
UCHIJ immersiveintegration{0.5.4} Immersive Integration 
UCHIJ inventorytweaks{1.58-147-645ca10} Inventory Tweaks 
UCHIJ IronChest{6.0.62.742} Iron Chest 
UCHIJ JABBA{1.2.1} JABBA 
UCHIJ journeymap{@JMVERSION@} JourneyMap 
UCHIJ magicalcrops{1.7.2 - 0.1 ALPHA} Magical Crops 
UCHIJ malisiscore{1.7.10-0.12.9} MalisisCore 
UCHIJ malisisdoors{1.7.10-1.10} Malisis' Doors 
UCHIJ Mekanism{8.1.7} Mekanism 
UCHIJ MekanismGenerators{8.1.7} MekanismGenerators 
UCHIJ MekanismTools{8.1.7} MekanismTools 
UCHIJ ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} Resonant Engine 
UCHIJ MFFS{@MAJOR@.@MINOR@.@REVIS@} Modular Force Field System 
UCHIJ MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} MFR Compat: Applied Energistics
UCHIJ MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} MFR Compat: Atum 
UCHIJ MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} MFR Compat: BackTools 
UCHIJ MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} MFR Compat: BuildCraft 
UCHIJ MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} MFR Compat: Chococraft 
UCHIJ MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} MFR Compat: ExtraBiomes 
UCHIJ MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} MFR Compat: Forestry 
UCHIJ MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} MFR Compat: ForgeMicroblock 
UCHIJ MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} MFR Compat: IC2 
UCHIJ MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} MFR Compat: Mystcraft 
UCHIJ MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} MFR Compat ProjectRed 
UCHIJ MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} MFR Compat: Railcraft 
UCHIJ MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} MFR Compat: Sufficient Biomes 
UCHIJ MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} MFR Compat: Thermal Expansion 
UCHIJ MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} MFR Compat: Tinkers' Construct 
UCHIJ MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} MFR Compat: TwilightForest 
UCHIJ MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} MFR Compat: Vanilla 
UCHIJ MineFactoryReloaded|CompatMagicalCrops{1.0beta} MFR Compat: MagicalCrops 
UCHIJ MineTweaker3{3.0.9B} MineTweaker 3 
UCHIJ testdummy{1.0} MmmMmmMmmMmm 
UCHIJ NEIPlugins{1.1.0.11-unofficial} NEI Plugins Unofficial 
UCHIJ NetherOres{1.7.10R2.3.1RC1} Nether Ores 
UCHIJ OpenMods{0.8} OpenMods 
UCHIJ OpenBlocks{1.4.4} OpenBlocks 
UCHIJ OpenComputers{1.5.18.36} OpenComputers 
UCHIJ openglasses{1.0.43} OC Glasses 
UCHIJ openmodularturrets{2.1.4-183} Open Modular Turrets 
UCHIJ PneumaticCraft{1.11.11-133} PneumaticCraft 
UCHIJ ProjectE{1.7.10-PE1.9.2} ProjectE 
UCHIJ quiverchevsky{b100} QuiverBow 
UCHIJ RedstoneArsenal{1.7.10R1.1.1} Redstone Arsenal 
UCHIE RotaryCraft{1.0} RotaryCraft 
UCHIJ SGCraft{1.9.0} Greg's SG Craft 
UCHIJ StevesCarts{2.0.0.b18} Steve's Carts 2 
UCHIJ StevesFactoryManager{A93} Steve's Factory Manager 
UCHIJ StorageDrawers{1.7.10-1.6.2} Storage Drawers 
UCHIJ streams{0.1.5} Streams 
UCHIJ thaumcraftneiplugin{1.7.10-1.6a} Thaumcraft NEI Plugin 
UCHIJ thaumicenergistics{0.8.10.10} Thaumic Energistics 
UCHIJ ThaumicTinkerer{unspecified} Thaumic Tinkerer 
UCHIJ ThaumicExploration{0.6.0} Thaumic Exploration 
UCHIJ ThaumicHorizons{1.1.5} Thaumic Horizons 
UCHIJ ThermalDynamics{1.7.10R1.1.0} Thermal Dynamics 
UCHIJ TiCTooltips{1.1.11b} TiC Tooltips 
UCHIJ TMechworks{0.2.14.100} Tinkers' Mechworks 
UCHIJ Translocator{1.1.1.14} Translocator 
UCHIJ TravellersGear{1.16.5} Traveller's Gear 
UCHIJ witchery{0.24.1} Witchery 
UCHIJ WitchingGadgets{1.1.9} Witching Gadgets 
UCHIJ WR-CBE|Core{1.4.1.9} WR-CBE Core 
UCHIJ WR-CBE|Addons{1.4.1.9} WR-CBE Addons 
UCHIJ WR-CBE|Logic{1.4.1.9} WR-CBE Logic 
UCHIJ yegamolchattels{1.1.2} Ye Gamol Chattels 
UCHIJ McMultipart{1.2.0.345} Minecraft Multipart Plugin 
UCHIJ MrTJPCoreMod{1.1.0.31} MrTJPCore 
UCHIJ aobd{2.8.3} Another One Bites The Dust 
UCHIJ denseores{1.0} Dense Ores 
UCHIJ IguanaTweaksTConstruct{1.7.10-2.1.5.140} Iguana Tinker Tweaks 
UCHIJ technom{0.12.0A} Technomancy 
UCHIJ ForgeMicroblock{1.2.0.345} Forge Microblocks 
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1062.1004' Renderer: 'AMD Radeon R9 200 Series'
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: all safe
CoFHCore: -[1.7.10]3.0.3-303
AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
MineFactoryReloaded: -[1.7.10]2.8.0-104
ThermalFoundation: -[1.7.10]1.2.0-102
ThermalExpansion: -[1.7.10]4.0.3B1-218
Mantle Environment: Environment healthy.
TConstruct Environment: Environment healthy.
NetherOres: -[1.7.10]2.3.1RC1-18
RedstoneArsenal: -[1.7.10]1.1.1-89
ThermalDynamics: -[1.7.10]1.1.0-161
Stencil buffer state: Function set: GL30, pool: forge, bits: 8
AE2 Integration: IC2:ON, RotaryCraft:ON, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:ON

**Comment by ReikaKalseki** [comment] 2015-09-27 17:26
Duplicate of #229. And do not post unspoilered logs.

**Closed as completed** 2015-09-27 17:25 UTC
Labels: Duplicate
