### ISSUE TITLE
ReactorCraft.TileEntities.PowerGen.TileEntityTurbineCore.intakeSteam throwing NullPointerExeption when using Optifine

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#2147] opened 2019-08-05 08:13 UTC
Sadly i was unable to upload the whole log because it is a couple of gigabytes big so i hat to copy only the error messages related to this. https://pastebin.com/mfx0WwBY
I also tried a multiple Optifine versions for this.

**Comment by OvermindDL1** [comment] 2019-08-05 20:28
Hmm, it's referencing this line of code:
https://github.com/ReikaKalseki/ReactorCraft/blob/d4aeb8ea71f498f7800c08455ccfbf416ef66029/TileEntities/PowerGen/TileEntityTurbineCore.java#L449
```
				double r = te.getRadius()*2.4-2;
```
The only object on that line is the `te`, and there is no null check on the TE, and considering how things can be accessed out-of-band because networking, I could easily see this being an issue, with or without optifine (though optifine can definitely make it worse because of threading).

First thing to note, you are using an older version of Reactorcraft.  Second, this is still an issue in the latest version, though of course it is extremely unlikely, though still possible, to happen without optifine.

**Comment by ghost** [comment] 2019-08-06 12:49
I am using Reactorcraft v22a which is the latest version (atleast on curse). I also cloned the github source of reactorcraft and tried a simple Null check 
<code>
if(te!=null){
</code>
<code>
double r = te.getRadius()*2.4-2;
</code>
<code>
				for (int n = 0; n < 2; n++) {
</code>
<code>
					double v = ReikaRandomHelper.getRandomBetween(0.03125, 0.25);
</code>
<code>
					double dx = x+0.5+dir.offsetX*i;
</code>
<code>
					double dy = y+0.5;
</code>
<code>
					double dz = z+0.5+dir.offsetZ*i;
</code>
<code>
					dy = ReikaRandomHelper.getRandomPlusMinus(dy, r);
</code>
<code>
					if (dir.offsetX != 0) {
</code>
<code>
						dz = ReikaRandomHelper.getRandomPlusMinus(dz, r);
</code>
<code>
					}
</code>
<code>
					else if (dir.offsetZ != 0) {
</code>
<code>
						dx = ReikaRandomHelper.getRandomPlusMinus(dx, r);
</code>
<code>
					}
</code>
<code>
					ReikaParticleHelper.CLOUD.spawnAt(world, dx, dy, dz, dir.offsetX*v, 0, dir.offsetZ*v);
}				}
</code>
which fixed the problem of the chat being spammed with the error messages which made the use of the angular transducer virtualy impossible (of course its not pretty and does only fix the symptoms and no particles where appearing because the code for that did not get executed but thats ok for me)

**Comment by ReikaKalseki** [comment] 2019-08-06 17:35
That is what is called a bandaid fix that does not address the underlying problem, namely the null return value.

I am dubious it is network-related, and if it only happens on the client, it might be *chunk* related. However, that requires the chunks be *just* on the edge of the player's render distance.

**Comment by ghost** [comment] 2019-08-06 18:15
Note: it happend even if i stood right in front of the Turbine.
It Seems to happen preferedly when building a Single Staged Turbine. I ran the Same save on a Local Server and on the Server Side no exeptions occured.

**Comment by ReikaKalseki** [comment] 2019-08-07 23:52
It is possible there is an actual bug here, though so far what it might be eludes me.

**Comment by habnabit** [comment] 2019-12-16 22:07
So, this is the issue I was going to file, but I've done some more tracing on it. It's the same as #2098, in fact. No optifine is involved at all in my testing.

I initially encountered it on my client when I walked away from a turbine that was still loaded on a remote server. I can reproduce it in single-player standing in the same chunk as the turbine, though. The cause seems to be when `TileEntityTurbineCore::updateEntity` is called on a turbine entity before `readSyncTag` is called *but only when the turbine is facing certain directions*. I don't know minecraft modding very well, but here's what I've pieced together with a debugger. Let's assume the turbine is a 5-length multiblock north/south oriented, and each block to the east and west of the turbine is empty.

https://github.com/ReikaKalseki/ReactorCraft/blob/899bf8ff8951fc556bcd0cecd9947cc4dde351bf/TileEntities/PowerGen/TileEntityTurbineCore.java#L248-L251

Block metadata (private field `pseudometa`; parameter `int meta`) starts at 0 and is never updated, so `getSteamMovement` is always `WEST`. `updateEntity` calls `getIOSides`, which correspondingly sets `{read,write}{x,y,z}` assuming east/west orientation. The `stage` is therefore calculated as 0 since east/west is empty.

https://github.com/ReikaKalseki/ReactorCraft/blob/899bf8ff8951fc556bcd0cecd9947cc4dde351bf/TileEntities/PowerGen/TileEntityTurbineCore.java#L397-L398

 `updateEntity` reaches this line:

https://github.com/ReikaKalseki/ReactorCraft/blob/899bf8ff8951fc556bcd0cecd9947cc4dde351bf/TileEntities/PowerGen/TileEntityTurbineCore.java#L164

`readSurroundings` reaches this line, because `stage` is still 0:

https://github.com/ReikaKalseki/ReactorCraft/blob/899bf8ff8951fc556bcd0cecd9947cc4dde351bf/TileEntities/PowerGen/TileEntityTurbineCore.java#L500

`intakeSteam` tries to get its sibling `TileEntityTurbineCore` instances, but the space is empty (leading to the `NullPointerExeption`). In cases like #2098, the space might be occupied by some other entity (leading to the `ClassCastException`).

https://github.com/ReikaKalseki/ReactorCraft/blob/899bf8ff8951fc556bcd0cecd9947cc4dde351bf/TileEntities/PowerGen/TileEntityTurbineCore.java#L447-L450

Confusingly (to me), this loop doesn't use the variable `i` when getting the tile entity. That means any 1-length turbines (also including these uninitialized ones) will always fail. If `x + dir.offsetX` was instead `x + (i * dir.offsetX)` then I think it would be fine for all turbines (still including these uninitialized ones).

---

I think there's two bugs here, ultimately.

1. Sometimes `updateEntity` is called on a `TileEntityTurbineCore` that isn't properly initialized from NBT. I don't know why; maybe that's more obvious for someone more familiar with modding.
2. Unrelatedly, `intakeSteam` fetches sibling tile entities incorrectly. It's most obvious with 1-length turbines, and aforementioned bug will coincidentally turn some N-length turbines into N 1-length turbines. This coincidence surfaces what would otherwise be a pretty rare bug since 1-length turbines in active use are pretty rare.

---

Initially I was worried that there was some sort of desync between `this.pseudometa` and the `int meta` parameter, so I logged `String.format("%d %d %d %d %d %d", this.getTileEntityAge(), x, y, z, meta, this.getPseudoMeta())` at this line:

https://github.com/ReikaKalseki/ReactorCraft/blob/899bf8ff8951fc556bcd0cecd9947cc4dde351bf/TileEntities/PowerGen/TileEntityTurbineCore.java#L447

The results, which show the uninitialized age as well:

```
0 -197 9 2190 0 0
0 -197 9 2190 0 0
58346 -197 9 2190 1 1
0 -197 9 2190 0 0
58365 -197 9 2190 1 1
0 -197 9 2190 0 0
58387 -197 9 2190 1 1
0 -197 9 2190 1 1
58409 -197 9 2190 1 1
0 -197 9 2190 1 1
58438 -197 9 2190 1 1
58446 -197 9 2190 1 1
```

Puzzlingly, you can see sometimes the age isn't set but the meta is right.

**Comment by habnabit** [comment] 2019-12-16 22:09
Alas; I hoped those snippets would show up inline, but apparently only if the issue is on the source repo.

**Comment by ReikaKalseki** [comment] 2019-12-17 01:37
Your first 'bug' should not be possible at all. Tiles should NEVER fail to load their NBT before being ticked, and in the event of an exception getting thrown, the game crashes, or if the appropriate Forge option is set, the tile is removed.

**Comment by habnabit** [comment] 2019-12-17 03:28
Is there any other reason the tile entity age would flicker between 0 and a sensible value for the same coordinates? It's possible it's interactions between mods; I haven't narrowed that down just yet.

**Comment by ReikaKalseki** [comment] 2019-12-18 03:01
That implies it is getting "synced" from an empty NBT tag, which would make this very closely related to the "spamming block updates around R(e)C/CC TileEntities causes everything to freak out" issue that has been present since 1.5.2, as loss of NBT data is what causes said freakouts.

**Comment by habnabit** [comment] 2019-12-18 21:21
Sure, "should". But.. it's happened enough that there's a note in your FAQ about the problem. Detecting uninitialized data would be easier with java 8's `Optional<T>` but sadly that's not available for minecraft yet. (Of course, scala has this already, but you're doing pure java, so..)

Anyway, were you going to fix the other bug mentioned? I'd make a PR but I have no idea how to build any of these mods for testing purposes.

**Comment by OvermindDL1** [comment] 2019-12-20 15:40
> Sure, "should". But.. it's happened enough that there's a note in your FAQ about the problem. Detecting uninitialized data would be easier with java 8's Optional<T> but sadly that's not available for minecraft yet. (Of course, scala has this already, but you're doing pure java, so..)

Kotlin does it better, it bakes optional into the type system, so if something is `blah` then it can't be null, if it's `blah?` then it can be null and needs to be tested, just like `Optional<blah>`, except without the overhead of a wrapper `Optional<blah>` object.

**Comment by habnabit** [comment] 2019-12-24 21:48
Yeah, I expected that this is probably not the right moment to pitch a scala or kotlin rewrite. 🙃

Java has problems, but there's a separate concrete issue which can be fixed simply.

**Comment by habnabit** [comment] 2021-04-15 00:53
Was this fixed in https://github.com/ReikaKalseki/ReactorCraft/commit/bf8ccd10be7b885558f4e662da8c587fb2d3e0d7 ?

**Comment by ReikaKalseki** [comment] 2021-04-16 23:04
As it happens, yes.

**Closed as completed by ReikaKalseki** 2021-04-16 23:04 UTC
Labels: Fixed, ReactorCraft, @&#%?!
