### ISSUE TITLE
Crash with Chromaticraft (NoClassDefFoundError TileEntityRift)

### ISSUE THREAD

**Issue by Milii20** [ReikaKalseki/Reika_Mods_Issues#2599] opened 2020-06-26 17:15 UTC
https://pastebin.com/mBTB0J6s

Greetings, i recently was making some personal use modpacks, and i found a "Contact Reika immediately!"

Every mod is V26b, and i redownloaded every mod again, just in case, but still crashing.
It is probably some incompatibility, but i cant find what it is.
if you need any other log or information, please let me know.

Thank you in advance!

**Comment by Milii20** [comment] 2020-06-29 00:14
A little bit of an update, i narrowed it down somehow to two mods:
CD4017BE_lib-1.7.10-2.7.4b
and
immibis-core-59.1.4
Taking those two mods out, allows the modpack to start with chromaticraft, which makes no sense, since both mods were on my older modpack along with chromaticraft, and were working fine.
Also tried with Chromaticraft V25, with the same crash, so my best guess is that something was messing some transformers somewhere, but for the time being, i will leave this open, just in case i missed something out

Thank you!

**Comment by ReikaKalseki** [comment] 2020-06-29 04:21
You have some sort of API versioning issue; one of those mods is probably doing something weird with one of the (great many) APIs the rifts use.

**Comment by OvermindDL1** [comment] 2020-06-29 21:18
@Milii20 If you can post direct download links to those two mods I can take a look at what API's they are including that they shouldn't be?

**Comment by Milii20** [comment] 2020-06-29 21:28
for sure!
CD4017BE_lib
download:   https://www.curseforge.com/minecraft/mc-mods/cd4017be-library/download/2425228
CurseForge: https://www.curseforge.com/minecraft/mc-mods/cd4017be-library
source:        https://github.com/CD4017BE/CD4017BE_lib/tree/master-1.7.10

and immibis core
download:   http://immibis.com/mcmoddl/files/immibis-core-59.1.4.jar
WebPage:    http://immibis.com/mcmoddl/
sadly i cant find the source code for this one

Thank you very much for your time!

**Comment by OvermindDL1** [comment] 2020-06-29 21:33
Don't need the source, just the jar's you are using.  :-)

Got the immibis jar but the CD4017BE_lib jar is failing to download:
```zsh
➜ wget https://www.curseforge.com/minecraft/mc-mods/cd4017be-library/download/2425228
--2020-06-29 15:32:58--  https://www.curseforge.com/minecraft/mc-mods/cd4017be-library/download/2425228
Resolving www.curseforge.com (www.curseforge.com)... 104.19.146.132, 104.19.147.132, 2606:4700::6813:9384, ...
Connecting to www.curseforge.com (www.curseforge.com)|104.19.146.132|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-06-29 15:32:58 ERROR 403: Forbidden
```
Why am I forbidden?

**Comment by OvermindDL1** [comment] 2020-06-29 21:35
As for the immibis jar I'm not seeing any thirdparty API's with it, so I doubt it's the problem.  Based on the above given information I would bet money that the `CD4017BE_lib` mod is the broken one.  If you can get me a working link then I can confirm or deny that.

**Comment by Milii20** [comment] 2020-06-29 21:37
hm, maybe it's a curseforge thing, let me upload it for 1 hour to my google drive

https://drive.google.com/u/0/uc?id=1f8TjrXQAthaz6700G4QWR1UOhoR0EnM_&export=download

That's CD4017BE_lib

**Comment by Milii20** [comment] 2020-06-29 21:42
also, aparently curseforge doesnt like wget

**Comment by OvermindDL1** [comment] 2020-06-29 21:55
That link seemed to be a webpage instead of a jar but I redirected it from my phone (I don't have a GUI available currently except on my phone, sooo....), which did download a jar from the same URL (wtf with serving a webpage one way but a file the other, are their programmers really that stupid at google drive?).

And holy crap, yep, that mod contains multiple third-party API's that it should *not* be including!

Let's see, the IC2 API is in there when it *absolutely* should not be, however it looks like it matches official so it "shouldn't" be the issue.

The COFH API is... not matching, I bet that's the one that is broken.

It also contains the OpenComputers API... which also doesn't match the official one, so that one is also an issue.

So that mod is broken to begin with, however you 'might' be able to get it working by opening the jar for CD4017BE_lib in a zip program and entirely delete the directories of `li` and `cofh` (and `ic2` too really but that's optional, and since you don't have IC2 it might break this mod if you remove it if they didn't program their API accesses correctly so try leaving it in to start with).

> also, aparently curseforge doesnt like wget

Pretty garbage programmers there if not, lol.  It's all standard HTTP, nothing fancy or special at all, so they would really exceptionally have to royally screw up for that not to work, but based on what I've heard about their competency to begin with, eh...  ^.^;

**Comment by Milii20** [comment] 2020-06-29 22:08
Did it and now it works, thank you very much!

**Comment by OvermindDL1** [comment] 2020-06-29 22:10
> Did it and now it works, thank you very much!

Awesome!  That does prove it was that mod including out of date API's that were breaking things, it would have broken other mods as well based on mod loading order and all sorts of other things.  Including third-party API's is always always always the wrong thing to do.  I'll go ahead and close this then.  Thanks for confirming!  :-)

**Closed as completed by OvermindDL1** 2020-06-29 22:10 UTC
Labels: Mod Interaction, Other Mod's End, Classloading, API Versions
