### ISSUE TITLE
Dragonapi crashing on MultiMC

### ISSUE THREAD

**Issue by LukaPix** [ReikaKalseki/Reika_Mods_Issues#1186] opened 2016-11-01 11:22 UTC
I get this REALLY weird error when trying to start minecraft on multimc with DragonAPI installed ...

Modlist in Log
http://pastebin.com/1fqYQPGH

**Comment by Aivech** [comment] 2016-11-01 13:48
Thaumic Infusion for 1.7.10 is not compatible with DragonAPI. In addition, the Thaumic Infusion author (TheDrunkMafia) has requested that people not use the 1.7.10 version of Thaumic Infusion. See https://github.com/TheDrunkMafia/ThaumicInfusion/issues/81.

Duplicate of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1003 & https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1079

**Comment by ReikaKalseki** [comment] 2016-11-01 20:08
and #895 #995 #1094

**Closed as completed** 2016-11-01 20:08 UTC
Labels: Duplicate
