### ISSUE TITLE
SMP Crash with BOP + Chromaticraft v14a when generating world

### ISSUE THREAD

**Issue by Morpheus1101** [ReikaKalseki/Reika_Mods_Issues#907] opened 2016-06-02 10:34 UTC
http://pastebin.com/bzfQAbW1

**Comment by ReikaKalseki** [comment] 2016-06-02 12:12
Duplicate of [your own issue](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/908)!

**Closed as completed by ReikaKalseki** 2016-06-02 12:12 UTC
Labels: Duplicate
