### ISSUE TITLE
chromaticraft and applied gtnh

### ISSUE THREAD

**Issue by aldro01** [ReikaKalseki/Reika_Mods_Issues#3099] opened 2022-11-16 18:15 UTC
hi, I wanted to ask if there is a way to fix the problem of chromaticraft with applied energistc gtnh, beacuse if you place a cable to another cable attached to the applied network the game takes you to the initial loading screen

**Comment by ReikaKalseki** [comment] 2023-07-03 22:28
What?

**Comment by MalTeeez** [comment] 2023-07-04 05:44
Duplicate of #2977

**Closed as completed** 2023-07-04 21:21 UTC
Labels: Duplicate, Needs Info, ChromatiCraft
