### ISSUE TITLE
Chromaticraft java.lang.ArrayIndexOutOfBoundsException: 9 crash on start v11a

### ISSUE THREAD

**Issue by Adraxas** [ReikaKalseki/Reika_Mods_Issues#640] opened 2016-02-24 01:36 UTC
[fml-client-latest.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/143765/fml-client-latest.txt)

getting [this](http://pastebin.com/X5B9EDBz) crash on startup

**Comment by ReikaKalseki** [comment] 2016-02-24 02:05
Forge's EnumHelper is failing to operate. Check your logs for errors related to EnumHelper.

**Comment by Adraxas** [comment] 2016-02-24 03:00
I searched but couldn't find anything related to EnumHelper

**Comment by novasolarius** [comment] 2016-02-24 17:13
Not sure if it helps, but this also happens with only Forge, DragonAPI and CC.

EDIT: And with both the latest and recommended Forge versions for 1.7.10. Could this be related to Java 8 perhaps?

**Comment by ReikaKalseki** [comment] 2016-02-24 21:06
I hope not, but all I am using is native Forge code, and it works for others on my pack that are using Java 8.

**Comment by novasolarius** [comment] 2016-02-24 22:53
I'm sorry to say it but ChromatiCraft works fine when running Java 7, at least on my end. Java 8 however crashes with and without the Java argument.

**Comment by dabaer** [comment] 2016-02-24 23:45
Initially I was certain it was another mod causing this so I never made an issue (although i could find no trace of it) because I only get this crash in tandem with other mods, never with just forge and these mods. I'll keep digging around and see what I come up with.

**Comment by zemerick** [comment] 2016-02-25 01:16
I'm using Java 8 u45 just fine with RoC, ReC, ChCr, ElC, Geostrata.

**Comment by TomeWyrm** [comment] 2016-02-25 01:54
I can use J8 and Reikas mods just fine. No I'm not going to go grab my JVM version just for this :-p

**Comment by Aivech** [comment] 2016-02-25 02:59
@TomeWyrm What are your java arguments? I don't know what to put, so I just did a max RAM and the G1GC.

**Comment by dabaer** [comment] 2016-02-25 04:18
@zemerick  @TomeWyrm please post your mod lists (assuming you are running with non-reika mods).

**Comment by zemerick** [comment] 2016-02-25 06:18
Mines a pretty extensive and ever changing list. Roughly started with infinity.

Reika also tests with a fairly extensive set.

For a start, I would compare with the OPs mods, and remove stuff you don't both have. Then, start pulling out half at a time and seeing if it still crashes. I would start with things that affect other code, not just add stuff. ( For example, "Threaded Lighting" in the case of the OP. ) That's a stretch, but this new.

Also out of curiosity, what J8 update version does everyone have? I see OP has 66 while I have 45.

**Comment by novasolarius** [comment] 2016-02-25 06:22
J8_66 here. My modlist consists of Forge, DragonAPI and ChromatiCraft. That's literally it.

**Comment by dabaer** [comment] 2016-02-25 07:17
Having picked and pulled all of these mods apart, I have seen a crash between electricraft and railcraft (new in v11), an issue between chromaticraft and biomesoplenty (chromaticraft seems to believe there are only 127 biome id's available (AIC tells me there are 255), and when i assign higher id's to it, it wraps around to 0 and throws conflicts with the biomes there).

Also on the menu is the root issue we we're trying to find in the first place, when used in conjunction forestry and biomesoplenty, (and another mod i've not found) chromaticraft doth glean our original crash.

Here's our original crash (well mine anyway): https://gist.github.com/dabaer/0841a981f7204af7b046
Here is where we have biome ID conflicts from above 128:
https://gist.github.com/dabaer/9ce62af392519d0f6d17
https://gist.github.com/dabaer/fa19eb14d4cf4223a06e
Here railcraft makes a cameo: https://gist.github.com/dabaer/bbc61c0260feb49e0014
More of me narrowing down the list: https://gist.github.com/dabaer/efc8bcf7d14ce0079912
We also have forestry making a special appearance: https://gist.github.com/dabaer/57a507616c72811f92a6
A bit of a change in the railcraft crash when I played around with combinations: https://gist.github.com/dabaer/57db5f83ea1e11b6ca7d

It's safe to say pandora's box is open here :D

Edit: My crash-reports folder has 60 files in it from today @_@

**Comment by Adraxas** [comment] 2016-02-25 08:11
Why do i seem to find all the fun issues.

**Comment by Adraxas** [comment] 2016-02-25 08:26
@dabaer the forestry and railcraft crashes both seem to be caused by missing buildcraft somehow
`Caused by: java.lang.NoClassDefFoundError: buildcraft/api/tools/IToolWrench
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more
Caused by: java.lang.ClassNotFoundException: buildcraft.api.tools.IToolWrench
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 42 more`

**Comment by dabaer** [comment] 2016-02-25 09:33
@Adraxas it's weird though, buildcraft isn't a hard dependancy, and they operate fine alone

**Comment by Adraxas** [comment] 2016-02-25 11:41
Speaking of weird. the issue suddenly stopped happening for meas i tried to narrow down the issue

**Comment by ReikaKalseki** [comment] 2016-02-25 21:10
The RailCraft, Biome ID, and Forestry issues are not relevant here, and none of them are on my end.

**Comment by dabaer** [comment] 2016-02-25 22:13
It's hard to say at this point, but I highly suspect forestry. As soon as I removed it the OPs error went away and brought me into the ID wrap around issue with Chromaticraft. Since you say it's not on your end, shall I assume that Chromaticraft shouldn't otherwise have an issue with biome IDs above 127?

**Comment by ReikaKalseki** [comment] 2016-02-25 22:17
You cannot have IDs that are the same as another ID +/- 128, as that triggers a vanilla bug.

**Comment by dabaer** [comment] 2016-02-25 22:21
Apologies for bringing this off topic a bit, but can you please elaborate? Biome ID 128 is the same as Biome ID 0? Or in my case 213 is the same as 85?

**Comment by dabaer** [comment] 2016-02-25 22:38
Oh hold on this is new as of v11... in v10d i'm able to assign biome IDs above 127 to chromaticraft without issue.

**Comment by ReikaKalseki** [comment] 2016-02-26 01:11
Again, unrelated, and not a bug. This issue is about the EnumHelper failure.

**Comment by Adraxas** [comment] 2016-02-26 07:14
It gets even weirder. It's happening again.

**Comment by ReikaKalseki** [comment] 2016-02-26 09:03
It is not a transient issue.

**Comment by novasolarius** [comment] 2016-02-26 09:11
Did anybody find out anything new? Or is our knowledge still limited to "EnumHelper crashes and we know FA of the cause"?

**Comment by e3r** [comment] 2016-02-26 15:42
Here is another log for the same exception, if it's of any help: https://paste.ee/p/NsCsl

Edit:
Just DragonAPI and Chromaticraft start up fine for me.
I have tried to test with the mods overlapping between OP's log and mine, a few at a time, but I wasn't able to reproduce it that way. (Could be I missed a couple, though.)

**Comment by Paxaxx** [comment] 2016-02-26 16:33
I Aslo have been dealing with this error post updating to v11. Id like to dig into it more but I think it does have to do with the enum helper but i think what is triggering it is dragonAPI adding a sound from cromaticraft that doesn't exist. But I may be wrong as I have not looked inside the code.

[crash-2016-02-26_10.26.48-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/148568/crash-2016-02-26_10.26.48-client.txt)

@dabaer 

The vanilla bug isnt really a bug its is just that vanilla minecraft uses both the biome slots (as of 1.7.10) 1-40 and then in the slots starting at 128 it have variations for some of the biomes in the 1-40 these are like plains = id 1
plains M =id 128 
sunflower plains = id 129

This means that when you are assigning biome ids you need to keep in mind that minecraft has reserved both 1-40 and 128-168.

Source:http://minecraft.gamepedia.com/Biome

**Comment by ReikaKalseki** [comment] 2016-02-26 17:45
> what is triggering it is dragonAPI adding a sound from cromaticraft that doesn't exist.

Entirely and obviously untrue.

**Comment by TomeWyrm** [comment] 2016-02-27 03:06
> This means that when you are assigning biome ids you need to keep in mind that minecraft has reserved both 1-40 and 128-168.

No, this means that when using biome ID's unless the lower ID'd biome will NEVER spawn in a non-custom dimension (think Twilight Forest), you only have 0-128 to work with unless you want to use another biome as a "technical" biome.

**Comment by Adraxas** [comment] 2016-02-27 03:12
@TomeWyrm @Paxaxx If you want to discuss that issue. could you please open a separate issue. this one is about the EnumHelper crash.

**Comment by Faeryfox** [comment] 2016-02-27 08:20
removed mods directory, created new one then put there only Reika's mods (DA CC RoC ReC EC)
game started fine. then deleted this new mod directory and bring back old one. issue gone, game works.

**Comment by ReikaKalseki** [comment] 2016-02-27 08:27
Try adding mods. I want to know what is causing it.

**Comment by Faeryfox** [comment] 2016-02-27 08:44
all my mods already there, and this issue not appeared anymore. mb your mods have first-start parameters wrote somewhere, or something... i'm have second comp with minecraft installed, if this issue present there then i'm try delete mods one by one

**Comment by Faeryfox** [comment] 2016-02-27 12:05
got it. Hardcore Ender Expansion v1.8.4 replaced music system. updating it to actual version 1.8.5 solved this problem

**Comment by novasolarius** [comment] 2016-02-27 12:38
Yeah, they mentioned this on the MCF thread too.

**Comment by aking4125** [comment] 2016-02-27 13:29
Sorry but not for me. Even with Hardcore Ender Expansion 1.8.5. Still crashing. 
[crash-2016-02-26_19.37.48-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/149343/crash-2016-02-26_19.37.48-client.txt)

Server works though.

**Comment by dabaer** [comment] 2016-02-27 14:33
@Paxaxx @TomeWyrm Yeah, no, this affected the entire 128-255 range.

@Faeryfox @aking4125 yeah, my HEE was already at 1.8.5 before updating to v11a.

@ReikaKalseki I cannot shake the fact that this crash only happens to me with Forestry installed. Forestry and BOP (because of the aforementioned biomes issue) to the side and everything is tickety boo. But when it's _just_ v11a and forestry I get a different forestry only crash as you saw in my list of crash reports. Maybe it's entirely a forestry issue?

**Comment by novasolarius** [comment] 2016-02-27 17:12
@aking4125 Create a new instance, move over only the important files (so 'mods'. 'configs', 'saves', 'options.txt' and such) from your original instance. See if that works.

**Comment by aking4125** [comment] 2016-02-27 17:22
@Nova001Sol Roger that. Will do that in a few. Though the saves I don't need. I have no local worlds.
EDIT, New Instance, Only Mods and Configs folder was left alone. Crash.

[crash-2016-02-27_12.29.59-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/149451/crash-2016-02-27_12.29.59-client.txt)

**Comment by novasolarius** [comment] 2016-02-27 17:46
@aking4125 Have you tried removing HEE?

**Comment by aking4125** [comment] 2016-02-27 17:51
@Nova001Sol Will do that now.

EDIT: After some more BiomeID Conflicts which it never asked me before. I got a successful boot. Because of the new BiomeID Conflicts I tried placing back HEE 1.8.5 and got the same crash. I went to redownload the HEE 1.8.5 jar file incase there was some derp somewhere but same crash. So it does seem to be related to Hardcore Ender Expansion.

**Comment by ReikaKalseki** [comment] 2016-02-27 20:35
HEE has been identified as the cause, and apparently he is changing something in one of the maps somewhere. I am closing this because there is [a thread there](https://github.com/chylex/Hardcore-Ender-Expansion/issues/170) and this is not on my end.

**Closed as completed by ReikaKalseki** 2016-02-27 20:35 UTC
Labels: Mod Interaction, Crash, @&#%?!, DragonAPI, Other Mod's End

**Comment by aking4125** [comment] 2016-02-27 20:38
@ReikaKalseki Understood.
