### ISSUE TITLE
[ReC] The Isotope Centrifuge no longer produces Uranium dusts in v25b

### ISSUE THREAD

**Issue by eugennc** [ReikaKalseki/Reika_Mods_Issues#2391] opened 2020-04-02 16:58 UTC
- Issue: The Reactorcraft Isotope Centrifuge no longer produces Depleted or Enriched Uranium dusts in V25b.
It keeps consuming Uranium Hexafluoride gas, but nothing pops up in its output slots. The blue progress bar also doesn't fill up.
This happens only on my multiplayer server; testing in single-player creative has the Centrifuge working properly.
- Other versions: The Isotope Centrifuge worked properly in V24a.
- Other testing: the initial Centrifuge (built in V24a) stopped working after the V25b update. It was disconnected from the ME fluid export, connected with a Gas Duct from a Reservoir, then a Bedrock Pipe. The Centrifuge was broken, replaced. Then, a new Centrifuge was crafted and put in place. New Centrifuges were crafted and placed in other locations. The world was deleted, a new world was created, and the set-up quickly rebuilt in Creative mode. Nothing worked. Again, Single-player Creative mode building has the Centrifuge working normally.
- My set-up: (both working single-player and non-working multiplayer) ECU ->(above) Gas Turbine -> Dynamometer -> CVT (32 speed) -> CVT (32 speed) -> Dynamometer -> Bevel Gears (output Up) ->(above) Isotope Centrifuge ->(above) Gas Duct ->(above)->(above) Covered Reservoir with UF_6.  I've varied the above set-up by removing the Dynamometers, no change.
- Images: [Centrifuge not working](https://gitlab.com/eugennc/bugreps/-/raw/master/Minecraft/2020-04-02_19.49.45.png)
[Test setup](https://gitlab.com/eugennc/bugreps/-/raw/master/Minecraft/2020-04-02_19.49.34.png)

**Comment by ReikaKalseki** [comment] 2020-04-05 19:22
I am using it just fine myself, and have been for more than a month.

**Comment by eugennc** [comment] 2020-04-05 22:23
Then, it's likely a mod interaction? It would be super hard to test, since it's not a crash, and requires human interaction. And I have 130 mods.

**Comment by Tycoon51** [comment] 2020-04-06 11:00
I confirm that the Isotope Centrifuge doesn't work on the server with ReactorCraft v25b, Running same setup with same mods in singleplayer works fine, but on server it doesn't produce Uranium Dusts. 
[Modlist](https://imgur.com/a/NUfsz1Z)

**Comment by eugennc** [comment] 2020-04-06 11:42
> I confirm that the Isotope Centrifuge doesn't work on the server with ReactorCraft v25b, Running same setup with same mods in singleplayer works fine, but on server it doesn't produce Uranium Dusts.
> [Modlist](https://imgur.com/a/NUfsz1Z)

The mods I have in common are:

Baubles-1.7.10-1.0.1.10.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
DragonAPI+1.7.10+V25c.jar
ElectriCraft+1.7.10+V25b.jar
fastcraft-1.25.jar
ChromatiCraft+1.7.10+V25b.jar
Morpheus-1.7.10-1.6.10.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
ReactorCraft+1.7.10+V25b.jar
RotaryCraft+1.7.10+V25b.jar
witchery-1.7.10-0.24.1.jar

I already tested by removing fastrcraft (on both server and client), didn't fix the issue. I'll test more when I have time, but this seems approachable now that we have a far shorter list of likely culprits.

**Comment by eugennc** [comment] 2020-04-06 14:47
I did more tests, with the only mods being:
ReactorCraft+1.7.10+V25b.jar
RotaryCraft+1.7.10+V25b.jar
DragonAPI+1.7.10+V25c.jar
I tried switching the server in offline/online mode. Deleted both the client and server ./config and ./scripts (and, of course, ./world). Didn't work.
I tried using forge 1558, the server crashed, although the client started up fine. (I cannot use DragonApi and forge 1558 on the server.)
I am currently using forge 1614 (forge-latest for 1.7.10); the server runs on oracle-java-8-amd64, jre, Debian, the client on opendjk-java-8-amd64, jre, Ubuntu.

**Comment by ReikaKalseki** [comment] 2020-04-08 19:35
Again, it has been working nonstop for more than a month, and continues to do so. ![https://i.imgur.com/RVKA6Uk.png](https://i.imgur.com/RVKA6Uk.png)

**Comment by Tycoon51** [comment] 2020-04-08 22:51
Is it on the server or singleplayer?

**Comment by ReikaKalseki** [comment] 2020-04-09 01:36
Mine? A dedicated server, but that is not going to affect recipes.

**Comment by eugennc** [comment] 2020-04-09 12:02
Extremely weird. May I ask people encountering this bug to leave their server specifications (or other particularities they might find relevant) here?

Also, in case I wasn't clear: this is not a visual bug, or a client issue; using AE Import Buses or EnderIO conduits to extract Uranium Dusts doesn't extract anything. I had an EnderIO duct extract from the Isotope Centrifuge into a chest, logged off, logged back in, the chest was empty.

**Comment by Tycoon51** [comment] 2020-04-10 00:05
Hello, I have encountered this bug again in singleplayer, so I recorded video with the centrifuge setup working in v24 and bugged in v25. Video here: https://youtu.be/GNY41wYgT5Y

**Comment by Retovath** [comment] 2020-04-11 08:42
Replicated this bug in SMP V25c/b/b Reactorcraft. Manually moving the UF6 into the IC got the fluid into the machine, but no pipe setup would work. Even then, with fluid in it and maxed out power/speed input, it would not function. When I tried the pipe setup, the machine would argue with the pipes, as my client thought that the machine should have fluid in it, but the server re-updated my client every few moments and told my client that it in fact had no fluid in it. This smells of heretical desync. 

forge-10.3.4.1614
[Modlist](https://gist.github.com/Retovath/1e1ee9b53a933ba1328414abaa297dd3)
server is an AMD build with a ryzen 7 3800x, Win 10, I don't know the java version at the moment, i am not host.

the mods on the modlist above that I have in common are


> CodeChickenCore-1.7.10-1.0.7.47-universal.jar
> DragonAPI+1.7.10+V25c.jar
> ElectriCraft+1.7.10+V25b.jar
> fastcraft-1.25.jar
> NotEnoughItems-1.7.10-1.0.5.120-universal.jar
> ReactorCraft+1.7.10+V25b.jar
> RotaryCraft+1.7.10+V25b.jar
> witchery-1.7.10-0.24.1.jar

**Comment by eugennc** [comment] 2020-04-11 11:34
I have a ryzen 7 3800x on the Client (but my singleplayer Isotope Centrifuge works).
The server runs a FX-4350. It seems extremely unlikely this is a CPU issue, but it's better to make sure.

**Comment by Thorinair** [comment] 2020-04-14 13:02
I can confirm that I have exactly the same issue. I have also recorded a video to show how weirdly it is all acting. Not only does the Centrifuge not accept any input, but its tank amount also changes weirdly when you look towards it and away from it. The values in the Uranium Processor are also all over the place. This smells of a client/server desync bug, as everyone seems to be having these issues on servers. Client expects something to happen and is trying to render it, but server says no. Currently using v25c.
https://www.youtube.com/watch?v=lJmbdHM2jLE

EDIT: Server is Ryzen 5 1600 running Debian, Java build 1.8.0_211-b12. Honestly, the specs of the servers should make no difference, but Java differences might.

**Comment by leonbaronick** [comment] 2020-04-17 00:55
Can confirm this issue. Working fine in singleplayer, while totally bugged out on a server. Exactly the same behaviour as in the videos.

I'm running a modified version of FTB Infinity Evolved. Only added DragonAPI, Rotarycraft, Reactorcraft and a couple more. Can go into further detail if required.

The server is running inside a docker container with the itzg/minecraft-server image (based on openjdk:8u212-jre-alpine).

My game is running on Java 1.8.0_51-b16.

**Comment by Goliathos** [comment] 2020-04-18 23:18
Also confirming centrifuge issue. It used to work just fine (even on 25b) but one day, must have been in the last 10 days or so, it quit working.

Modlist:
![Modlist](https://user-images.githubusercontent.com/63853121/79673633-4b527880-81d3-11ea-8c57-c27fad18df1f.png)

**Comment by Goliathos** [comment] 2020-04-19 13:21
Video for setup reference. Creative SP.

https://www.youtube.com/watch?v=C740VXGFQqk

**Comment by Goliathos** [comment] 2020-04-19 23:19
I tested it again with only Rotarycraft, Electricraft, and Reactorcraft Installed. Still not working. That means something must have changed when I updated MultiMC (maybe new Forge Loader?).

For everyone struggling with mod interactions, I don't think that's what's causing it.

I originally had it working on v25b and then something changed. I didn't add mods, so MultiMC must have done something.

Edit: Could also be Java updates maybe? All I can say for sure is that it WAS working at one point (v25b). The only things that have changed on my PC were windows updates.

**Comment by Thorinair** [comment] 2020-04-20 01:08
Nope, it is not in any way related to MultiMC. I run my server on a completely separate Ubuntu machine from terminal without any additional software (like MultiMC), and I didn't update MultiMC either on my PC where I play. Yet still, I get this issue. No Java updates either, and definitely no Windows updates on the server. It may however be an issue related to the date. Maybe some April Fools feature which has now "expired" in the code is interfering with normal operation.

**Comment by Goliathos** [comment] 2020-04-20 10:29
I'm completely grasping at straws. Without knowing how many people actually use Reactorcraft in its' latest version AND have gotten to use the centrifuge we can't say if anyone ISN'T having the issue.

That being said, Reika himself said he isn't having the issue. I wonder what he's doing differently.

**Comment by Thorinair** [comment] 2020-04-20 11:30
There is a possibility that he runs a non-compiled version directly from within the development suite he may be using. We can't know, but that is one of the possibilities I would assume.

**Comment by ReikaKalseki** [comment] 2020-04-21 22:57
While I have been using intermediate dev versions, the relevant code has not been touched since early February. Moreover, there is nothing in this code that explains the things being reported here, namely A) that it works in SSP and not SMP and B) that it *was* working even in v25 for someone and then spontaneously stopped. None of the code is "sticky" or server-specific.

**Comment by leonbaronick** [comment] 2020-04-21 23:33
Any information we can provide you or anything we can do to help? I think resolving this issue is really important as it locks the entire reactor tech-tree on servers.

**Comment by ReikaKalseki** [comment] 2020-04-22 19:16
I cannot think of anything obvious, short of checking to see if the TE contains any weird or inconsistent data.

One thing that does occur to me is that my centrifuges *postdate* the change, i.e. they did not exist prior and then get grandfathered in, whereas I imagine at least some people here have centrifuges that were.

**Comment by Goliathos** [comment] 2020-04-23 16:07
The video i posted earlier featured a centrifuge that post dated the change.

**Comment by ReikaKalseki** [comment] 2020-04-24 21:14
Thus invalidating my idea.

**Comment by rkane31174** [comment] 2020-05-06 00:47
I'm having this problem too. Is there a way to download version V24a just to get it to work in the interim? I don't see any other way to progress without the centrifuge working.

Could this be an issue with java? I can check what version my server is using if you think it might help.

**Comment by Goliathos** [comment] 2020-05-06 13:41
I too, would like access to the older version if possible. It's the only thing holding back progress at the moment.

**Comment by rkane31174** [comment] 2020-05-12 18:38
If it helps, the centrifuge seems to fill up and stop accepting UF6 if I don't look at it. If I do look at it, NEI will show the tank values fluctuating wildly and it will resume draining the UF6 again.

Did a bit more experimenting and tried removing NEI from my client and server.
The centrifuge still didn't process uranium, but now it wouldn't accept UF6 from the pipes at all. With no NEI, looking at it makes no difference.

**Comment by eugennc** [comment] 2020-05-12 21:17
> If it helps, the centrifuge seems to fill up and stop accepting UF6 if I don't look at it. If I do look at it, NEI will show the tank values fluctuating wildly and it will resume draining the UF6 again.
> 
> Did a bit more experimenting and tried removing NEI from my client and server.
> The centrifuge still didn't process uranium, but now it wouldn't accept UF6 from the pipes at all. With no NEI, looking at it makes no difference.

That's my experience as well. Haven't tried removing NEI individually, but with other mods, the centrifuge's UF_6 levels fluctuate, and without other mods (just DA, RoC, EC, ReC), the centrifuge fills up and the UF_6 remains at max levels.

**Comment by ReikaKalseki** [comment] 2020-05-13 15:45
Checking the fluid fill code, I just found the problem.

The enum class representing the recipes was not being initialized, *until* the Centrifuge NEI handler was checked. Due to how NEI is coded, looking up *any* NEI recipe loads all handlers, including in this case the centrifuge. Meaning the centrifuge itself would only begin to work once you looked up a recipe in NEI - a near inevitability on a large pack - and would continue to work until the next restart.

However, as NEI is mostly clientside, it only initialized the class - and thus the machine working - clientside. This explains the earlier desync, and why the machine *looks* to be working when it is not.

It *also* explains the "my machine *was* working and then stopped" reports.


This **has** to be the most insanely convoluted issue with a singular simple cause, and the most unexpected interaction I have ever dealt with, at least as far as I can remember.

**Closed as completed by ReikaKalseki** 2020-05-13 15:45 UTC
Labels: Bug, Fixed, ReactorCraft, Classloading, I don't even..

**Comment by ReikaKalseki** [comment] 2020-05-13 15:48
And to that end...

**Comment by Speiger** [comment] 2020-05-14 10:24
Yeah I had one of these too. They are gems in my eyes!

**Comment by eugennc** [comment] 2020-05-14 10:29
Mad cheers to @rkane31174 for pointing it out. I had noticed the weird NEI fluid behaviour 6 weeks ago when I did the extensive comparative tests, but didn't think to report it (thought it to be a weird UI display issue and -thought-terminating-clichee-).

Thanks again for your hard work.

**Comment by Thorinair** [comment] 2020-05-14 14:35
> This **has** to be the most insanely convoluted issue with a singular simple cause, and the most unexpected interaction I have ever dealt with, at least as far as I can remember.

I have to agree with this. It is hilarious how this even happened, and somehow, I love it haha (in a positive way)
