### ISSUE TITLE
RotaryCraft crashes on startup (with COFHCore?).

### ISSUE THREAD

**Issue by OrsonRoutt** [ReikaKalseki/Reika_Mods_Issues#3117] opened 2022-12-12 18:07 UTC
I've been playing RotaryCraft and wanted to add Thermal Dynamics but whenever I try and load the game I get an error to do with 'ItemScrewdriverFocus'. I've done basic testing to determine what mod is causing the crash (which Thermal mod it is) and it seems to be COFH Core.

Crash Report: [pastebin.com/2v9RHRRF](https://pastebin.com/2v9RHRRF)

**Comment by MalTeeez** [comment] 2022-12-14 19:47
Duplicate of #2558

**Closed as completed** 2023-07-03 22:11 UTC
Labels: Duplicate, Stop Reporting This
