### ISSUE TITLE
Void Monster Ticking Entity Crash

### ISSUE THREAD

**Issue by gmnovakrc** [ReikaKalseki/Reika_Mods_Issues#2853] opened 2021-06-09 03:02 UTC
Trying out in custom modpack, currently making with about 60-ish mods atm.
Just trying out random stuff with it to see how it reacts with other things in world, I wasn't able to kill it for some reason while in creative mode, gave up after a bit. 
While also trying to use a Quarry from BC to dig out random hole while this is going on, Void seemed to have gotten stuck on pipe frame of Quarry. Don't remember if the Quarry was on or off at time though. Crashed about 20-ish secs after making contact with pipes.

Awesome mod btw, let me know if you need any other info.

MC 1.7.10
Forge 1.7.10-10.13.4.1614
DragonAPI 1.7.10-V29g
Void Monster 1.7.10-V29c
Plus a bunch of other mods, I can give you a list if needed.

Crash report
[crash-2021-06-08_00.19.07-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6620798/crash-2021-06-08_00.19.07-server.txt)

Log
[2021-06-08-1.log.gz](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/6620802/2021-06-08-1.log.gz)

**Comment by MalTeeez** [comment] 2021-06-10 08:59
Duplicate of #2209 ?

**Comment by ReikaKalseki** [comment] 2021-06-14 16:46
Yes.

**Closed as completed by ReikaKalseki** 2021-06-14 16:46 UTC
Labels: Duplicate
