### ISSUE TITLE
Problem with mouse becoming invisible with update notification 

### ISSUE THREAD

**Issue by MJRLegends** [ReikaKalseki/Reika_Mods_Issues#317] opened 2015-10-08 21:38 UTC
![](https://cloud.githubusercontent.com/assets/3783930/10357387/0a92e5e0-6dc5-11e5-8d0c-eaa81a078fef.png)

This has only become a problem since the update notification for the Dragon API, ElectriCraft, ReactorCraft,  RotaryCraft mods has came about. 

And people are saying they cant press CTRL to close the update notification  popup on Apple mac's

Sorry if this has been fixed or reported loads, just people are complaining to me via my issue tracker for my mod pack

**Comment by ReikaKalseki** [comment] 2015-10-09 05:27
> And people are saying they cant press CTRL to close the update notification popup on Apple mac's

LWJGL should map it accordingly, probably to its equivalent (the little curly square symbol).

**Comment by MJRLegends** [comment] 2015-10-09 09:00
Well its causing loads of problems as people can't remove it from there screen. And the mouse goes invisible making it hard to use anything

**Comment by Modbder** [comment] 2015-10-09 09:45
You know what is funny? The key codes for ctrl on mac and on other OS are different in LWJGL for no actual reason. It's 219 or 220 for mac's and 29 and 157 for other OS. You could use GuiScreen.isCtrlKeyDown() to check for ctrl being pressed, since it includes the mac check too.

**Comment by MJRLegends** [comment] 2015-10-09 11:05
Yeah that would fix it and all we need now is a fix for the invisible mouse glitch

**Comment by ReikaKalseki** [comment] 2015-10-09 17:58
> Yeah that would fix it and all we need now is a fix for the invisible mouse glitch

Is this also OS-specific? It does not happen for me, and I am on a Win7 machine (and the day I own an apple device, call the mental hospital).

Alternatively, is the missing mouse caused by holding CTRL? Try holding the proper key.

**Comment by MJRLegends** [comment] 2015-10-09 17:59
The invisible mouse glitch seems to happen on both windows and mac

**Comment by ReikaKalseki** [comment] 2015-10-09 18:03
Not for me. Can someone else reproduce it?

Also, I just fixed the CTRL handling here and everywhere else I use LCTRL (like the CC lexicon GUI and the Casting Delegate).

**Comment by MJRLegends** [comment] 2015-10-09 18:04
Well i have had loads of people using my mod pack saying they have it too

**Comment by MJRLegends** [comment] 2015-10-09 18:05
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/65 https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/68
https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/70

**Comment by MJRLegends** [comment] 2015-10-11 09:48
Are you able to fix the invisible mouse @ReikaKalseki

**Comment by ghost** [comment] 2015-10-11 13:10
I actually found a fix to this.
The problem is the update notification that appears at the top-left when the game starts. Its asking you to update four mods: DragonAPI, RotaryCraft, ElectriCraft and ReactorCraft
But if you disable the notifications, the problem no longer happens.
To disable, you can type the following command in the chat box:
/checker disable [ModName]

So you type in the four commands:
/checker disable DragonAPI
/checker disable RotaryCraft
/checker disable ElectriCraft
/checker disable ReactorCraft

After this, restart Space Astronomy and the problem should be fixed. If you still see the update notification, check which mod update it is for and use the command to disable the update notif.

Ofcourse, the update notifications for those mods gets disabled, but that wasn't a big problem for me.

**Comment by MJRLegends** [comment] 2015-10-11 15:12
@SparkerComet but will this have to be done by a user playing the mod pack or will it keep the settings when i disable it and upload the update.

**Comment by lossycrypt** [comment] 2015-10-11 16:34
/config/Reika/DragonAPI.cfg

```
"control setup" {
    B:"Only show update notice to Ops or SSP"=true
    B:"Only show update notice to pack creator"=true
}
```

**Comment by ReikaKalseki** [comment] 2015-10-11 21:23
> @SparkerComet but will this have to be done by a user playing the mod pack or will it keep the settings when i disable it and upload the update.

Or you could try updating the mods? If you are updating your pack, why the _hell_ are you choosing to continue using an old version?

**Comment by MJRLegends** [comment] 2015-10-11 21:25
Yeah but i want a permanent way to fix this so if you release another update people don't have the invisible mouse issue all over again

**Comment by ReikaKalseki** [comment] 2015-10-11 21:27
That is what the configs lossycrypt linked are for.

Also, the bug does not happen. At all:

![](http://i.imgur.com/cEvu4gO.png)

**Closed as completed by ReikaKalseki** 2015-10-11 21:27 UTC
Labels: Bug, Fixed, Can't Reproduce, DragonAPI, OS/Hardware-Specific, Compound Issue

**Comment by MJRLegends** [comment] 2015-10-11 21:28
@ReikaKalseki if you go back to the main menu without closing the notification stuff it does!

**Comment by ReikaKalseki** [comment] 2015-10-11 21:29
> @ReikaKalseki if you go back to the main menu without closing the notification stuff it does!

It does not.

EDIT:
I found one thing that _can_ make the cursor disappear, but it is not what you are reporting.

**Comment by MJRLegends** [comment] 2015-10-11 21:29
I dont make this stuff up you know? do i really have to make a video to show you?

**Comment by ReikaKalseki** [comment] 2015-10-11 21:33
I just fixed the issue I discovered.

As for yours, if I am not seeing it, it has to be a result of something else. Maybe OS, maybe JVM, maybe other mods, maybe running programs, maybe hardware drivers, I do not know and am not going to spend months debugging.

You can wait until v10 to see if the above fix also fixes your issue.

**Comment by MJRLegends** [comment] 2015-10-11 21:35
Ok, but its more people are moaning at me for the invisible mouse thing and blaming me for it. Cant i just disable it from showing the notification?

**Comment by MJRLegends** [comment] 2015-10-11 22:05
@ReikaKalseki here is the bug, take a look. All i did was load the mod pack and load a world and then this gif follows on containing the bug http://i.imgur.com/ozskiQs.gifv

**Comment by MJRLegends** [comment] 2015-10-15 19:55
???????

**Comment by lossycrypt** [comment] 2015-10-15 20:51
Please read my post above on how to disable these warnings in the config for your users.

**Comment by MJRLegends** [comment] 2015-10-15 20:55
but if the fix is not to use the update notification popup then whats the point in them? We need a fix that will work when using them.

**Comment by lossycrypt** [comment] 2015-10-15 23:00
Then you need to provide the steps to reproduce the bug in a way that works on Reikas system. If he can't reproduce it he can't fix it. As a start I suggest removing mods one by one to find out the minimum mod selection that causes the bug. Yes that will take time and a lot of restarts.

**Comment by elitebyte** [comment] 2015-12-31 06:35
This is also happening to me and it is very frustrating. I am playing on a modpack called Unabridged, on a public server, and I'm am on a Macbook Air running OSX 10.11.1 (El Capitan). So when I join the server the box pops up saying I need to update DragonAPI from v9 to v10, when holding the LCRTL button my cursor pops up, but I am unable to click the "X" button to close the box. (While I move my cursor to close it my player's perspective moves too, unlike when you go into the "esc" menu and your player's view doesn't change ) Keep in mind I haven't moved my player yet (In position). When I do move my player and re-attempt the LCRTL my cursor doesn't appear anymore, and when I go into my inventory my cursor is invisible as well, but I am able to move the invisible cursor around to move items and everything else because I use the slot highlights as I my reference. Once this happens my entire Minecraft instance is buggy with this invisible cursor; for example, I leave the server back into the main menu and my cursor is still gone, and it remains gone until I restart the entire instance. I can't update because I do not own the modpack nor do I own the server, but when I update my client with DragonAPI v10 the game crashes the instant I attempt to launch it. So, in conclusion I am a very angry player, and if you want me to provide a video I can make one.

**Comment by elitebyte** [comment] 2015-12-31 06:39
Oh another thing before losscrypt suggest I follow his steps, I've done so and nothing has changed the message still happily awaits me on login. I also ran each command that would disable such update checker I.E. "/checker disable dragongui" and it responds with "It has been disabled" but in reality it didn't do jack shiet.

**Comment by ljfa-ag** [comment] 2015-12-31 18:54
Well this issue should be fixed in v10. Obviously the only way how you can get the fix is by updating. You will have to wait until the server updates, sorry :/

**Comment by robindegen** [comment] 2016-01-29 17:36
I can confirm this doesn't work at all with mac. It's making a lot of modpacks unplayable.

**Comment by ReikaKalseki** [comment] 2016-01-29 20:50
Are you on v10?
