### ISSUE TITLE
Frequent crash in chroma dimensions

### ISSUE THREAD

**Issue by Mr-CHENmatrix** [ReikaKalseki/Reika_Mods_Issues#2992] opened 2022-02-08 07:05 UTC
I don't know why. Is my computer not good enough? Now I'm short of three puzzle structures, but I often crash in chroma dimension, so I can't find them.

---- Minecraft Crash Report ----
// Don't do that.

Time: 22-2-8 下午2:53
Description: Invalid Biome id

java.lang.NullPointerException: Invalid Biome id
	at net.minecraft.world.biome.WorldChunkManager.func_76936_a(WorldChunkManager.java:76)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:26)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:52)
	at net.minecraft.world.biome.BiomeCache.func_76837_b(SourceFile:61)
	at net.minecraft.world.biome.WorldChunkManager.func_76935_a(WorldChunkManager.java:58)
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:160)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
	at net.minecraft.world.World.func_72807_a(World.java:130)
	at Reika.ChromatiCraft.World.Dimension.ChunkProviderChroma.func_73153_a(ChunkProviderChroma.java:735)
	at Reika.ChromatiCraft.World.Dimension.ChunkProviderChroma.func_73154_d(ChunkProviderChroma.java:522)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.SpawnerAnimals.func_151350_a(SpawnerAnimals.java:32)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:100)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.WorldChunkManager.func_76936_a(WorldChunkManager.java:76)

-- DownfallBlock --
Details:
	biome id: 0
	downfalls[] size: 256
	x: 2896
	z: 1040
	w: 16
	h: 16
Stacktrace:
	at net.minecraft.world.biome.WorldChunkManager.func_76936_a(WorldChunkManager.java:76)
	at net.minecraft.world.biome.BiomeCache$Block.<init>(SourceFile:26)
	at net.minecraft.world.biome.BiomeCache.func_76840_a(SourceFile:52)
	at net.minecraft.world.biome.BiomeCache.func_76837_b(SourceFile:61)
	at net.minecraft.world.biome.WorldChunkManager.func_76935_a(WorldChunkManager.java:58)
	at net.minecraft.world.World.getBiomeGenForCoordsBody(World.java:160)
	at net.minecraft.world.WorldProvider.getBiomeGenForCoords(WorldProvider.java:365)
	at net.minecraft.world.World.func_72807_a(World.java:130)
	at Reika.ChromatiCraft.World.Dimension.ChunkProviderChroma.func_73153_a(ChunkProviderChroma.java:735)
	at Reika.ChromatiCraft.World.Dimension.ChunkProviderChroma.func_73154_d(ChunkProviderChroma.java:522)

-- Chunk to be generated --
Details:
	Location: 180,64
	Position hash: 274877907124
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.SpawnerAnimals.func_151350_a(SpawnerAnimals.java:32)
	at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:100)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:161)

-- Affected level --
Details:
	Level name: test
	All players: 1 total; [EntityPlayerMP['fndxn'/862, l='test', x=3000.50, y=120.50, z=1000.50]]
	Chunk stats: ServerChunkCache: 381 Drop: 0
	Level seed: -8894657674320088839
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4521353752 bytes (4311 MB) / 6157238272 bytes (5872 MB) up to 6442450944 bytes (6144 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.7.0
	LaunchWrapper: 41 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: Reika.ChromatiCraft.Auxiliary.ChromaASMHandler$ASMExecutor
          - Transformer: Reika.DragonAPI.ASM.InterfaceInjector
          - Transformer: Reika.DragonAPI.ASM.APIStripper
          - Transformer: Reika.DragonAPI.ASM.DragonAPIClassTransformer
          - Transformer: Reika.DragonAPI.ASM.FMLItemBlockPatch
          - Transformer: Reika.DragonAPI.ASM.FluidNamePatch
          - Transformer: Reika.DragonAPI.ASM.DependentMethodStripper
          - Transformer: Reika.DragonAPI.ASM.ClassReparenter
          - Transformer: Reika.DragonAPI.ASM.Profiling.WorldGeneratorProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.Profiling.MapGeneratorProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.Profiling.ChunkInitProfilingHooks
          - Transformer: Reika.DragonAPI.ASM.StructureLootHooks
          - Transformer: Reika.DragonAPI.ASM.SpecialBiomePlacement
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 11, tcache: 110, allocated: 1, tallocated: 4
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.16} [ChickenChunks] ([区块载入]ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	DragonAPI{v31a} [DragonAPI] (DragonAPI+1.7.10+V31a.jar) 
	UCHIJAAAA	ChromatiCraft{v31a} [ChromatiCraft] (ChromatiCraft+1.7.10+V31a.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	ItemRender{@VERSION@} [Item Render] (ItemRenderRebirth_V1.0.0_MC1.7.10.jar) 
	UCHIJAAAA	KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.7.10-2.1.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial] (NEIPlugins-1.1.0.11.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['fndxn'/862, l='test', x=3000.50, y=120.50, z=1000.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by MalTeeez** [comment] 2022-02-08 19:37
Duplicate of #2962

**Closed as completed** 2023-07-04 02:04 UTC
Labels: Duplicate
