### ISSUE TITLE
Extractor caused server to crash when items were placed inside it.

### ISSUE THREAD

**Issue by sharkck** [ReikaKalseki/Reika_Mods_Issues#977] opened 2016-06-17 19:50 UTC
We placed 34 Redstone ore inside an extractor and the second the ore was placed inside it, the server crashed with the following error:
[14:56:38] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ExceptionInInitializerError
        at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.canProcess(TileEntityExtractor.java:292) ~[TileEntityExtractor.class:?]
        at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.testIdle(TileEntityExtractor.java:93) ~[TileEntityExtractor.class:?]
        at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.updateEntity(TileEntityExtractor.java:214) ~[TileEntityExtractor.class:?]
        at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:464) ~[TileEntityBase.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        ... 4 more
Caused by: java.lang.UnsupportedOperationException: This map does not support overwriting values! Item tile.null:6 already mapped to '1xitem.item.modextracts@24'!
        at Reika.DragonAPI.Instantiable.Data.Maps.ItemHashMap.put(ItemHashMap.java:66) ~[ItemHashMap.class:?]
        at Reika.DragonAPI.Instantiable.Data.Maps.ItemHashMap.put(ItemHashMap.java:82) ~[ItemHashMap.class:?]
        at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesExtractor.addRecipe(RecipesExtractor.java:105) ~[RecipesExtractor.class:?]
        at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesExtractor.addModRecipes(RecipesExtractor.java:63) ~[RecipesExtractor.class:?]
        at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesExtractor.<init>(RecipesExtractor.java:55) ~[RecipesExtractor.class:?]
        at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesExtractor.<clinit>(RecipesExtractor.java:32) ~[RecipesExtractor.class:?]
        at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.canProcess(TileEntityExtractor.java:292) ~[TileEntityExtractor.class:?]
        at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.testIdle(TileEntityExtractor.java:93) ~[TileEntityExtractor.class:?]
        at Reika.RotaryCraft.TileEntities.Processing.TileEntityExtractor.updateEntity(TileEntityExtractor.java:214) ~[TileEntityExtractor.class:?]
        at Reika.DragonAPI.Base.TileEntityBase.func_145845_h(TileEntityBase.java:464) ~[TileEntityBase.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        ... 4 more
[14:56:39] [Server thread/ERROR]: This crash report has been saved to:

**Comment by sharkck** [comment] 2016-06-17 19:54
We are currently running Rotarycraft version: RotaryCraft 1.7.10 V14b

I noticed that there is an update. I'll try to update it to the latest version tonight to see if the update fixes the issue and will report back.

**Comment by sharkck** [comment] 2016-06-17 19:57
Also, here is a full error report from the crash log:
http://pastebin.com/111yKshw

**Comment by redelman** [comment] 2016-06-17 20:49
Duplicate of #893, #859. Fixed in v14c, I believe.

**Closed as completed by redelman** 2016-06-17 20:49 UTC
Labels: Duplicate, Old Version, Fixed
