### ISSUE TITLE
weard dragon api roterycraft bug

### ISSUE THREAD

**Issue by PlatinumEragong** [ReikaKalseki/Reika_Mods_Issues#445] opened 2015-12-04 16:00 UTC
http://paste.creeperhost.net/view/decc5a70

**Comment by Towsty** [comment] 2015-12-04 18:49
Dupe of #229 I believe. You'll have to roll back forestry to something 3.x.x.x.

**Comment by ReikaKalseki** [comment] 2015-12-04 20:32
You are the 319th to report this. There is no glory in this.

**Closed as completed by ReikaKalseki** 2015-12-04 20:32 UTC
Labels: Duplicate
