### ISSUE TITLE
Unable to optain Chromaticraft Mystcraft pages

### ISSUE THREAD

**Issue by eqdanteon** [ReikaKalseki/Reika_Mods_Issues#511] opened 2015-12-27 00:43 UTC
I have been unable to obtain the Chromaticraft Mystcraft pages as they don't appear to be in the Mystcraft loot table.  I have used the The Much Loot mod to analyze the Mystcraft loot table and it appears that they are not included.  I have also tried locating them in creative mode but I am unable to find them on any of the Mystcraft or Chromaticraft tabs.  I am also not sure if they are suppose to appear in the Chromaticraft dungeon loots instead.  Any assistance would be greatly appreciated.

**Comment by eqdanteon** [comment] 2015-12-27 00:49
Forgot to mention Chromaticraft V10b and Mystcraft 0.12.3.01

**Comment by TomeWyrm** [comment] 2015-12-27 18:11
Intended behavior as far as I am aware.

**Comment by eqdanteon** [comment] 2015-12-27 18:26
I apologize beforehand if I am missing something but I fail to see how this is intended behavior.  Are the pages somehow obtained in Chromaticraft structures or other method.  The Chromaticraft book states that generation is now controlled by custom pages as does the v10 changelog.  I am unable to do that if I can't obtain the pages.

**Comment by ReikaKalseki** [comment] 2015-12-27 21:20
This sounds like a bug, yes. I thought MystCraft handled this automatically.

**Comment by ReikaKalseki** [comment] 2015-12-30 19:54
Does anyone know how to fix it?

**Comment by eqdanteon** [comment] 2015-12-30 21:41
I opened the issue on XCompWiz's tracker as well to see if he has any input.

https://github.com/XCompWiz/Mystcraft-Issues/issues/144

**Comment by EyeDeck** [comment] 2016-03-28 07:10
Should be fixed in v12. 

For DragonAPI to use Mystcraft's API, DragonAPI has to send an inter-mod comm (IMC) to Mystcraft asking Mystcraft to reflectively provide an API object for DragonAPI to use. DragonAPI tried to do its page registration in init, but IMCs are only sent in post-init, and so Mystcraft didn't provide DragonAPI with the API until after DragonAPI had tried, and failed, to register its pages. Oops.

**Closed as completed** 2016-03-28 07:14 UTC
Labels: Bug, Fixed, Mod Interaction, ChromatiCraft

**Comment by Fantazer3z** [comment] 2025-02-13 15:13
I warn you: I wrote through a translator, because I don't know English well. 
If you enter the world with shaders and full build , and then go to the creative tab of the Mystcraft pages, the pages are: buried structures, cave crystals, chroma ores, chroma plants, corrupted aura, crystal pylons, dense generation, disabled, dye trees, energy drain, excessive discharge, hospitable aura, lumen loss, pylon stabilization, sky rivers, and as I understand it, Chromaticraft adds, they will have the texture of fire, and in the chat it is written in red: "An error occurred when rendering an item. Please check the log file for more information." If you try to take such a fires, the assembly will crash. When re-entering, the broken pages remain, but this time nothing about the error is written in the chat. If you go in purely with Optifine, Chromaticraft and Mystcraft, visiting this tab in the creative will become fatal immediately ("shutting down internal server" and crashing), and not as soon as you take the fires. If you turn off the shaders (when fully assembled), the fires will disappear, you can take the pages, but they will have large black pixels in the form of a diamond, as well as a diamond with an unfinished one and two pixels (apparently the symbol on it is a little broken). And then turn it on, turn it off, re-enter - there's no point, anyway, the pages are in pixels. Every time you turn on the shaders again, an error appears in the chat: "OpenGL error: 1282(Invalid operation)". If you reenter to Minecraft, everything will return to its original position. If you go into the world with shaders, and then turn them off without going to the tab, the pages will be normal, and if you turn on the shaders again, they will have black pixels. It looks like the problem has returned. /
