### ISSUE TITLE
applied energistic v3

### ISSUE THREAD

**Issue by aldro01** [ReikaKalseki/Reika_Mods_Issues#2419] opened 2020-04-11 11:03 UTC
hi reika chromaticraft crash with appliedenergistic rv3

**Comment by wamc2017** [comment] 2020-04-11 11:13
Without a crash report, it's hard to say, but I guess this is a dupe of https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/481

Try setting exportItemNames to false in AppliedEnergistics2/CustomRecipes.cfg ....

**Comment by aldro01** [comment] 2020-04-11 14:52
ok I'll try thanks

**Comment by aldro01** [comment] 2020-04-11 16:12
it works thanks

**Closed as completed** 2020-04-11 16:12 UTC
Labels: Duplicate, Stop Reporting This

**Comment by ReikaKalseki** [comment] 2020-04-14 01:58
#1732 #1683 #1681 #1493 #1257 #1280 #1238 #2390 #1848 #1985
