### ISSUE TITLE
CC Item Collector destroys items that spawn within it's collection radius.

### ISSUE THREAD

**Issue by lossycrypt** [ReikaKalseki/Reika_Mods_Issues#341] opened 2015-10-15 19:38 UTC
###### Required mods:
- DragonAPI 1.7.10 V9b
- ChromatiCraft 1.7.10 V9b
###### Reproduction (weird):
1. Start minecraft (aka don't use an already running instance)
2. Make a new world.
3. Place an Item Collector
4. Link it up to some Kuro and Asveste or use /debugtest.
5. Set a filter on the IC. I'm using wheat.
6. Throw some wheat into the air. (If the collector is unpowered at this point the client will crash.)
7. Very quickly open the ICs gui. If you're fast enough you can see the wheat flashing up before vanishing. Now comes the weird part:
8. Save map, close minecraft. (Going to the main menu is not enough)
9. Start minecraft again.
10. Load the world from step 2.
11. Now everything works as intended.

```
Time: 15/10/15 21:22
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
    at Reika.ChromatiCraft.TileEntity.AOE.TileEntityItemCollector.absorbItem(TileEntityItemCollector.java:130)
    at Reika.ChromatiCraft.ChromaticEventManager.preSpawnItemXP(ChromaticEventManager.java:716)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_59_ChromaticEventManager_preSpawnItemXP_EntityJoinWorldEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.world.World.func_72838_d(World.java:1334)
    at net.minecraft.entity.player.EntityPlayer.func_71012_a(EntityPlayer.java:793)
    at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:370)
    at net.minecraft.entity.player.EntityPlayer.func_71040_bB(EntityPlayer.java:724)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:431)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at Reika.ChromatiCraft.TileEntity.AOE.TileEntityItemCollector.absorbItem(TileEntityItemCollector.java:130)
    at Reika.ChromatiCraft.ChromaticEventManager.preSpawnItemXP(ChromaticEventManager.java:716)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_59_ChromaticEventManager_preSpawnItemXP_EntityJoinWorldEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at net.minecraft.world.World.func_72838_d(World.java:1334)
    at net.minecraft.entity.player.EntityPlayer.func_71012_a(EntityPlayer.java:793)
    at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:370)
    at net.minecraft.entity.player.EntityPlayer.func_71040_bB(EntityPlayer.java:724)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:431)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
    Connection: net.minecraft.network.NetworkManager@1de00b31
Stacktrace:
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by lossycrypt** [comment] 2015-10-15 20:46
Oh, i forgot to mention:
The destruction of items in step 7 only occurs if the item is spawned inside the collection radius. Items that enter the radius from outside (i.e. thrown from above) are collected correctly.

**Comment by ReikaKalseki** [comment] 2015-10-20 19:45
Duplicate of #329.

**Closed as completed by ReikaKalseki** 2015-10-20 19:45 UTC
Labels: Duplicate
