### ISSUE TITLE
Changing mode (split/merge) on shaft junction sometimes crashes the client

### ISSUE THREAD

**Issue by pjolin** [ReikaKalseki/Reika_Mods_Issues#512] opened 2015-12-27 03:55 UTC
I get these client crashes occasionally when changing mode on the shaft junction. 

It happens rarely enough, but most of the time it _seems_ like it's when I change mode just after placing them or rotating them and the red/green boxes are still showing. 

I can normally produce that crash within 10-15 seconds of hammering at it with a screwdriver randomly alternating between rotating and changing mode. (Note: it doesn't take hammering at it like that to happen, it's just a reliable way to cause the crash). 

I've had that bug occasionnally since I started playing with Rotarycraft (v6) and I can still produce it 10b. 

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 12/26/15 9:36 PM
Description: Rendering Block Entity

java.lang.NullPointerException: Rendering Block Entity
    at Reika.RotaryCraft.Auxiliary.IORenderer.renderIO(IORenderer.java:74)
    at Reika.RotaryCraft.Renders.RenderSplitter.func_147500_a(RenderSplitter.java:134)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1337)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at Reika.RotaryCraft.Auxiliary.IORenderer.renderIO(IORenderer.java:74)
    at Reika.RotaryCraft.Renders.RenderSplitter.func_147500_a(RenderSplitter.java:134)

-- Block Entity Details --
Details:
    Name: RCsplitter // Reika.RotaryCraft.TileEntities.Transmission.TileEntitySplitter
    Block type: ID #1159 (tile. // Reika.RotaryCraft.Blocks.BlockTrans)
    Block data value: 9 / 0x9 / 0b1001
    Block location: World: (746,65,-929), Chunk: (at 10,4,15 in 46,-59; contains blocks 736,0,-944 to 751,255,-929), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
    Actual block type: ID #1159 (tile. // Reika.RotaryCraft.Blocks.BlockTrans)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:483)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1337)

**Comment by TomeWyrm** [comment] 2015-12-27 18:11
I think this is a known issue that we can't reproduce to fix. Also, please use a paste service to post the FULL log from beginning to end.

**Comment by pjolin** [comment] 2015-12-27 20:33
http://pastebin.com/PKq6jfXQ

**Comment by TomeWyrm** [comment] 2015-12-27 21:21
Fixed. Thanks!

**Comment by TomeWyrm** [comment] 2015-12-27 21:22
It will be in v10c when that goes public!

**Comment by ReikaKalseki** [comment] 2015-12-28 01:56
This falls under the "should be impossible" category, and I have never seen it or heard it reported.

**Closed as completed** 2015-12-28 01:56 UTC
Labels: Can't Reproduce, RotaryCraft
