### ISSUE TITLE
Chromaticraft 9b Elemental Manipulator issue

### ISSUE THREAD

**Issue by 1skandar** [ReikaKalseki/Reika_Mods_Issues#366] opened 2015-10-28 20:42 UTC
It appears that the elemental manipulator recipe when first unlocked will only take a Kuro crystal shard. Both NEI and the Lexicon only show the recipe with the Kuro shard and crafting with any other crystal shard doesn't work. Exiting out and then coming back in fixes the issue.

**Comment by 1skandar** [comment] 2015-10-28 21:20
Thisis another one that seems to be intermittent. I've run a few test worlds. Most cases it unlocks just fine, some cases you need to exit and come back for it to work with anything other than a Kuro shard.

**Comment by ReikaKalseki** [comment] 2015-10-29 00:39
The recipe should use OreDict wildcard...

Relogging reloads all the casting recipes, so it sounds like something gets errored intermittently...

**Comment by 1skandar** [comment] 2015-10-29 00:53
I'm still trying to determine the exact circumstances, but it looks random so far. 

Sorry I keep finding these weird little bugs.

**Comment by ReikaKalseki** [comment] 2015-11-29 01:02
I am going to close this for now due to its irreproducibility. If you see it in another pack, or get more info, I will reopen it.

**Closed as completed by ReikaKalseki** 2015-11-29 01:02 UTC
Labels: Can't Reproduce, ChromatiCraft, @&#%?!
