### ISSUE TITLE
Crash on launch v17b from v16d DragAPI / RoC / ExtRed v16b

### ISSUE THREAD

**Issue by AbieTheFishman** [ReikaKalseki/Reika_Mods_Issues#1446] opened 2017-05-26 22:54 UTC
Crashes on launching Minecraft - Forge 10.13.4.1566-1.7.10

https://pastebin.com/8kdFgRUK

**Comment by ReikaKalseki** [comment] 2017-05-27 06:41
IC2 classic?

**Comment by DracoScythem** [comment] 2017-05-27 08:17
`IC2-Classic-Spmod{0.0.0.0} [IC2 Classic Detection Helper] (IC2Classic Version 1.2.1.5.1.jar)`
It certainly seems so - what's causing the problem is the fact that the entire ISemiFluidFuelManager is an always-empty dummy (returns null and an empty HashMap respectively).
For my own setup I wrote a small Patch to overwrite it with an actually working one to circumvent that issue.
Not having null checks in place there could still prove fatal even with a 'normal' IC2 Version if another mod removes those Entries (it would be very bad practice, but it is a possibility)

**Comment by AbieTheFishman** [comment] 2017-05-27 16:35
Yes - that is correct IC2 Classic Version 1.2.1.5.1. 

So I need to stick with v16d?

**Comment by ReikaKalseki** [comment] 2017-05-27 17:05
Use IC2 experimental or his patch for now.

**Comment by AbieTheFishman** [comment] 2017-05-27 17:18
I'll report to him - not sure what to report - can I include Leguan12 comment

Thanks

**Comment by ReikaKalseki** [comment] 2017-05-27 17:33
...? What is there to report?

**Comment by ReikaKalseki** [comment] 2017-05-27 17:41
Also, fixed in code for now.

**Comment by AbieTheFishman** [comment] 2017-05-27 17:49
I believe I misunderstood - I thought it was an issue that needed to be reported to the IC2 Classic developer.

Again thank you for your time and really original mods.

**Comment by Speiger** [comment] 2017-05-27 18:23
Its fine that you reported it to me. I want to know these things. If any other issues are there. No worry about reporting them.
Since i assume its already fixed. I close it on my side.

**Comment by ReikaKalseki** [comment] 2017-05-27 20:09
Fixed and released.

**Closed as completed by ReikaKalseki** 2017-05-27 20:09 UTC
Labels: Fixed, Mod Interaction, RotaryCraft, Crash
