### ISSUE TITLE
RC and NEI

### ISSUE THREAD

**Issue by MaciejMalczyk** [ReikaKalseki/Reika_Mods_Issues#252] opened 2015-09-12 19:45 UTC
I get an error when i want to check any recipe in nei. It happens on the newest version of both mods.

http://pastebin.com/0eQVbq9w

**Comment by ljfa-ag** [comment] 2015-09-12 21:24
Duplicate of #224. Seems to be a problem with Pneumaticcraft.

**Closed as completed by ljfa-ag** 2015-09-12 21:24 UTC
Labels: Duplicate

**Comment by MaciejMalczyk** [comment] 2015-09-13 18:15
But I get it without PC too.

**Comment by ReikaKalseki** [comment] 2015-09-13 18:18
I do not, so clearly another mod is involved.

**Comment by MaciejMalczyk** [comment] 2015-09-13 19:42
Heh, which versions of PC and RC do you use?

**Comment by ReikaKalseki** [comment] 2015-09-13 20:19
I do not use PnC in my pack.
