### ISSUE TITLE
Infinite output when making HSLA with Iron Block

### ISSUE THREAD

**Issue by Prunoideae** [ReikaKalseki/Reika_Mods_Issues#1997] opened 2018-11-22 07:33 UTC
Making HSLA ingot with iron block is available in previous version, but recently I've found that blast furnace will not consume materials in the input slot if the output is already filled with charcoal and iron ingots.
![tim 20181122153112](https://user-images.githubusercontent.com/24620047/48887828-b1668f00-ee6b-11e8-9cdc-767a10727e39.jpg)
![tim 20181122153152](https://user-images.githubusercontent.com/24620047/48887843-c2af9b80-ee6b-11e8-87dd-4b38de473f65.jpg)
![tim 20181122153205](https://user-images.githubusercontent.com/24620047/48887853-ca6f4000-ee6b-11e8-92c3-5fbec17aeb71.jpg)

**Comment by ReikaKalseki** [comment] 2018-11-24 05:04
This is probably a deeper issue in handling multiple output types than anything in that specific recipe (though this might be the only recipe with such output variation).

Also, you really should not be making steel this way.

Amusingly, this recently came up in another platform:

![https://i.imgur.com/0EjDIda.png](https://i.imgur.com/0EjDIda.png)
![https://i.imgur.com/KzeOWy6.png](https://i.imgur.com/KzeOWy6.png)
![https://i.imgur.com/Y7hndu8.png](https://i.imgur.com/Y7hndu8.png)

**Comment by ReikaKalseki** [comment] 2018-12-14 22:26
Indeed, the problem is that the Blast Furnace recipe system does not support multiple output items, and the crappy recipe was essentially specially coded in.

**Comment by ReikaKalseki** [comment] 2018-12-14 22:31
Fixed by way of that recipe now requiring an empty output to function.

**Closed as completed by ReikaKalseki** 2018-12-14 22:31 UTC
Labels: Bug, Fixed, RotaryCraft, Exploit
