### ISSUE TITLE
Crash with Forestry 4.0

### ISSUE THREAD

**Issue by Akai1** [ReikaKalseki/Reika_Mods_Issues#229] opened 2015-09-06 01:04 UTC
Your mod is not compatible with latest Forestry. Please update.

https://gist.github.com/Akai1/6f05ccf523748dc9f34c

**Comment by ReikaKalseki** [comment] 2015-09-06 04:37
Actually, it is you who needs to update.

**Comment by Akai1** [comment] 2015-09-06 05:31
All mods in my instance are up to date @ReikaKalseki .
You can see the version in the crash report.

**Comment by ReikaKalseki** [comment] 2015-09-06 06:41
I updated to the latest Forestry API in v8. Your Forestry version is ancient.

EDIT:
Wait...4.0.0.0? Did they make another new release in the last week, and ditch the 3.X series entirely at that?

EDIT 2: All Forestry downloads I can find are 3.6.X.

**Comment by zoeliterally** [comment] 2015-09-06 09:28
http://ic2api.player.to:8080/job/Forestry_Dev/

**Comment by ljfa-ag** [comment] 2015-09-06 09:49
Well it doesn't say that it might be unstable for nothing. I think you shouldn't use Jenkins builds for playing if you plan on keeping your worlds.

**Comment by Akai1** [comment] 2015-09-06 15:30
Yeah you can get 4.0 on http://ic2api.player.to:8080/job/Forestry_Dev/
At this point 4.0 is really stable and has quite a few new cool things.
So it would be really nice, if you support it @ReikaKalseki.

**Comment by ReikaKalseki** [comment] 2015-09-06 17:49
Is 4.0 a different branch entirely? I cannot support two branches simultaneously.

**Comment by TomeWyrm** [comment] 2015-09-06 17:55
Yes it is, all the X.y.y.y are completely new branches with Forestry. Please do not support in development versions of mods that aren't easily accessible from the "main download" page. It screws up most users and creates a lot of rather annoying scavenger hunts.

**Comment by Akai1** [comment] 2015-09-06 18:46
Ok thanks. Is it possible to disable mod interaction with Forestry?

**Comment by ReikaKalseki** [comment] 2015-09-06 19:41
No. Use a proper Forestry version.

Also, it looks like the 4.0 version is using the **_old**_ API from pre-3.6. So updating to newer mainline Forestry versions actually broke it.

Someone on the Forestry team has explaining to do.

**Comment by mezz** [comment] 2015-09-30 05:20
@ReikaKalseki  Forestry 4.0 is not using an older API. Forestry's API versioning is per-package using [SemVer](http://semver.org/) and is not tied to the mod version number.

There are many internal changes in this release, especially to wood items and multiblocks.
There are API changes as well (mainly removing deprecated things).

**Comment by ReikaKalseki** [comment] 2015-09-30 05:43
4.x worked with the 3.5.x code, but 3.6.x code works with neither.

**Comment by mezz** [comment] 2015-09-30 05:48
Sounds coincidental to me, I didn't do anything too weird.

I loaded up DragonAPI and it was dying on the Forestry Log blocks. 
https://github.com/ReikaKalseki/DragonAPI/blob/d922a9fa422e5c2fde921a611e3043fd9033e235/ModInteract/ItemHandlers/ForestryHandler.java#L63-L70
Seems weird to use reflection instead of `GameRegistry.findItemStack()` but anyway...
Forestry's Logs changed a lot, they are now one block and use NBT for the species.

There is a new API in Forestry to get the wood items, `TreeManager.woodItemAccess`. Not sure if you'd need access to the block in DragonAPI any more.

**Comment by ljfa-ag** [comment] 2015-09-30 10:11
Yeah reflecting into a mod's internal classes if you just need blocks or items is a bad idea. I did the same mistake and recently switched to lookup from the block/item registry. This will continue to work for as long as the mod in questrion doesn't make changes that break existing worlds.

That said, the AbstractMethodError in the OP still seems weird.

**Comment by ReikaKalseki** [comment] 2015-09-30 16:02
My reflective handlers, if they fail, never crash, only fail to load the items. Any NoSuchMethod or similar errors are caused by API changes.

Also, stupid as it is, most mods change their APIs rather more than their internal code.

Example 1: AE. Eight breaking API changes in six months (including a recapitalization of AEAPI.instance()!) whereas the internal registries remain unchanged.

Example 2: MystCraft. Constant refactoring of the API class and constant renaming of the fields (repeatedly adding and removing block_ to the field names). No internal registry change.

Also, most mods provide no API hooks to get their items, and yes, like to play musical registration names.

**Comment by ljfa-ag** [comment] 2015-09-30 17:02
Well I guess those are stupid examples.

> Also, most mods provide no API hooks to get their items, and yes, like to play musical registration names.

I can't imagine that it happens that often that mods break existing worlds by changing block and item names. I would guess that Block.getBlockFromName and Item.getItemFromName are still more reliable than reflection.

For instance, my stuff broke in the past when Thermal Expansion and Chisel renamed their packages.

**Comment by mezz** [comment] 2015-10-07 01:49
I think this discussion got derailed, Forestry made breaking changes including ones that remove blocks in the world.
Can this issue be reopened?

**Comment by ReikaKalseki** [comment] 2015-10-07 01:52
I cannot yet update, because fully half of the players are refusing to update the mod version, yet still demanding the support.

**Comment by mezz** [comment] 2015-10-07 02:45
Since I was confused about why DragonAPI includes Forestry, I took a look into it.

I've been working to improve the API, basically so that people don't have to implement stuff like in `ModInteract/Bees/`.

Flowers in particular have breaking changes because we really messed it up in earlier implementations. Instead of needing `BasicFlower.java` class, you can now register flowers with `FlowerManager.flowerRegistry.registerAcceptableFlower` or `registerPlantableFlower`

Instead of needing to write `BeeSpecies.java` you can create bee species with a brand new API, `BeeManager.beeFactory.createSpecies`. (This addition is backward compatible, all the old ways of doing it are still there for now)

As for the item handler, why not request that one be added to the Forestry API? It would be much easier to maintain there, and there would be no version conflict issues.

If you find yourself needing to implement stuff like that in DragonAPI, please let me know that the Forestry API needs improvement. Having DragonAPI act as middleware for active projects like Forestry and others sounds like maintenance hell, worse than Forge.

**Comment by ReikaKalseki** [comment] 2015-10-07 05:36
I have base classes like `BeeSpecies` because I generally prefer to boilerplate things, as for most of it a great deal can be inherited and shared. Additionally, going through DragonAPI means that no matter what happens within Forestry (or any other mod), only one area of code needs to change; rather than 15 different classes from 9 mods needing to update their content, only the intermediary needs to do so.

**Comment by mezz** [comment] 2015-10-12 15:36
Just a heads up, Forestry 4.0 is now the stable release.

**Comment by TomeWyrm** [comment] 2015-10-12 16:23
With it being the stable release now, my previous comment is still relevant, just in the other direction.

Forestry 4 is now the current version, and all the addons that are actively developed seem to have switched to using it. Which means in my eyes? Anyone staying on Forestry versions <4 can deal with not having the latest version of your mods like they're dealing with not having the latest versions of their other mods.

In a partly irrelevant tangent to this current discussion, thank you bdew/mezz/whomever else made gendustry's json bees thing into a reality. Because relying on Binnie's mods was becoming a support headache. Now I can just json the bees and get similar functionality (even hives!). Not the woodworker, but oh well; I'm sure someone will make a mod that lets you do that with arbitrary blocktypes eventually :-p

**Comment by AlexPlus117** [comment] 2015-10-12 16:35
I believe Binnie will release an updated version of his mods on Christmas holidays and Forestry 4 is a stable release now. I don't know what to do...

**Comment by TomeWyrm** [comment] 2015-10-12 16:48
If you only used Extra Bees, my suggestion would be Gendustry. If you actually utilized the other features of the mod, have a long-term world, or both? Stick with the most up to date forestry version that Binnie supports, and experience the reason I'm now dropping Binnie's mods: Compatability issues combined with a glacial release pace

Note: I am not blaming Binnie! The mod (it's one jar, don't care if it's 4 or 400 modules) is awesome, it just doesn't fit my requirements of "doesn't version lock me for months at a time". Precisely one author gets that courtesy extended to them, because I know it will be temporary and the mods are core to my pack.

**Comment by AlexPlus117** [comment] 2015-10-12 16:53
I use Binnie's mods only because of the "EXTRA" bees that are in his mods. I'm already using GenDustry to do other awesome things, but Extra Bees is a mod that adds many mod-interaction bees (how many times I said "bees"?).

**Comment by TomeWyrm** [comment] 2015-10-12 16:55
Good, then you're in the same boat I am. There is a solution to your problem: https://bdew.net/gendustry/configuration/adding-custom-bees/

It'll be a bit of tedious data entry work, but you can completely replace Extra Bees

**Comment by AlexPlus117** [comment] 2015-10-12 16:59
Oh my God! I wasn't aware of this possibility. I'm going to try this as soon as possible. Thank you for the suggestion... you've just saved my life!

**Comment by TomeWyrm** [comment] 2015-10-12 17:01
You can even do custom hives since Gendustry 1.6.

Just note, I was not kidding when I said tedious. You will be entering a LOT of data if you aim to replicate Extra Bees.

**Comment by AlexPlus117** [comment] 2015-10-12 17:04
Definitely better than waiting for the update of Binnie's mods! I'm just waiting for Reika's mods fix. Maybe... if someone could update Binnie's mods to Forestry 4 until he does so...

**Comment by ljfa-ag** [comment] 2015-10-13 23:59
Look at that, so many duplicates in the last few hours
I guess this actually needs to be addressed soon

**Comment by Tsyklop** [comment] 2015-10-14 06:43
@ReikaKalseki Please Update!!! Forestry 4 is Stable!

**Comment by wipa44** [comment] 2015-10-14 07:32
@ReikaKalseki

**Comment by wipa44** [comment] 2015-10-14 07:57
@ReikaKalseki please fix

**Comment by AlexPlus117** [comment] 2015-10-14 13:46
This is going to be the most important fix ever on Reika's modding story.

**Comment by border999** [comment] 2015-10-14 22:24
indeed. This may actually cause a good number of people to stop using rotarycraft if he's unwilling to fix this.

**Comment by TomeWyrm** [comment] 2015-10-15 00:58
Wow the hyperbole from the new users.

Trust me the v2 > v3 was MUCH worse. IIRC that was the time that BC updated and a stupid number of mods had API issues, so nearly everything was version-locked.

Reika will update, you just have to be patient for the next major version.

**Comment by Morketh** [comment] 2015-11-01 22:32
I would really like to add these mods back into my modpack but they refuse to load with Forestry installed. Please update and fix this. these are really good mods youve done a fantastic job on things id love to have them running again

**Comment by spamenigma** [comment] 2015-11-02 10:44
I've held back on updating forestry due to the dragonapi incompatibility crash. however this is now causing more issues with more mods no longer working with forestry 3.x and I'm needing to update to 4. Hope this can be sorted soon. ty!

**Comment by walkerjonny** [comment] 2015-11-03 23:36
Same for me. Nearly every major mod I know has now switched over to the Forestry 4 branch, to be exactly, to the 4.1 branch now. So I would really appreciate it, if you won't hold yourself back to update to the new Forestry branches anymore.

**Comment by SirFlip** [comment] 2015-11-10 17:14
Hey. I am currently working on a Modpack for me and some friends and like to use Rotorycraft and Forestry. I don't want to leave any of the mods out. What is the Priority of this issue, would be nice to know when we can suspect a fix for this issue.

**Comment by s-thom** [comment] 2015-11-13 23:14
Another person in the RotaryCraft/ChromatiCraft & Forestry boat. I'd love to see this resolved. Maybe as a temporary solution, have a config option to disable Forestry interaction until you work with the new API?

**Comment by border999** [comment] 2015-11-14 06:08
That would be so helpful!

**Comment by Eladkay** [comment] 2015-11-19 12:36
Yeah, good idea @SecretOnline 
Keeps happening for me.

**Comment by Morketh** [comment] 2015-11-19 17:27
Any status updates? Looks like an entire community is waiting for some kind of answer. Time line, to-do list, progress? Please don't leave us hanging in the void @ReikaKalseki

**Comment by Eladkay** [comment] 2015-11-20 05:47
Folks, I talked to Iskandar, and he said that as a temporary fix, downgrade forestry to Forestry 3, and all other addons to an version released before October 2015.

**Comment by walkerjonny** [comment] 2015-11-20 10:58
And exactly that becomes more and more an issue as many other Mod Developers refuse to support older versions of their Mods. 
Also I can't add bug fixes for existing Mod issues because those Mods switched to Forestry 4.x at the time they were applyind those fixes.
I for myself have at least 10 Mods on my list hat I cannot upgrade because Reika refuses to upgrade his Mods to the new Forestry branch. 
That isn't really funny anymore...

**Comment by ljfa-ag** [comment] 2015-11-20 13:41
Well think about how many people still have old worlds with Forestry 3 and can't update because it would break their world and other addons they have. So unfortunately you can't suit everybody.

**Comment by Eladkay** [comment] 2015-11-20 13:49
@ljfa-ag that's definitely not a reason not to fix a critical bug.

**Comment by walkerjonny** [comment] 2015-11-20 14:40
The point is that those people can stay on the old worlds with the old versions of Forestry and all the other mods. 
But as it looks like many others if not the majority of the community want to proceed to the new Forestry branch and want also include the newest versions of all the affected mods because of good reasons.
That is how the most mod developers and the community out there are acting usually.
Reika interferes with his sometimes uncommon acting those usual proceedings. 
It would be at least good to know if he plans to do some updates within the next few weeks or if he wants to wait until Christmas or even next year...
The badest information is no information about this at all.

**Comment by walkerjonny** [comment] 2015-11-20 19:25
FYI: Forestry just updated to 4.2.0 and did some API changes to add some new functions.
@ReikaKalseki 
Maybe you want to support the new APIs when you decide to upgrade your mods.

**Comment by Eladkay** [comment] 2015-11-20 20:11
Reika has been proven wrong, chances are we'll never be hearing from him.

**Comment by TomeWyrm** [comment] 2015-11-20 20:18
What is with the drama llamas in this comment thread? Use the old versions if you want any DragonAPI dependent mod. If you have to have Forestry 4, et al? Don't use DragonAPI.

Very simple. Reika is aware of the updates, and will change, or not, when HE decides to. Apparently giving the end user the ability to disable forestry integration will raise unrealistic expectations that other integration could be easily disabled (Forestry Integration is very light, and uniquely easy — though non-trivial — to disable), and to prevent a never-ending trend of future support headaches he will not support the "fix" to this problem.

As for why he does not wish to update to Forestry 4 as a fix for the problem, I honestly couldn't tell you. None of the reasons I have seen make much sense to me.

**Comment by walkerjonny** [comment] 2015-11-21 00:15
TomeWyrm is right about stating that this should not become personal and/or insulting. 
Don't forget, Reika is doing an awesome job with his mods aside from this issue.
However it should also be allowed to explain the issues this case causes to us when it is done in a polite way and I for myself am trying to handle it that way.
Maybe some of those arguments will influence Reika's deciding process on this issue a bit.
I'm pretty sure that Reika will fix this finally. He has done that always in the past. It is just the question when he will do that. 
He acts just sometimes a bit unusual, that's his way of handling things and we have to be patient and understanding. It would just be nice, if he might be a bit more communicative about his future plans on this issue. That's all.

**Comment by Morketh** [comment] 2015-11-21 00:20
@walkerjonny i think you make a valid point there. At the least just say "I'm still alive and programming"

**Comment by walkerjonny** [comment] 2015-11-21 00:35
Oh, Reika is still very active. Just have a look on his thread on minecraftforum.net (also maintained by curse). His last reply there is just four hours ago.
I'm quite sure he is working on implementing some new stuff that becomes available on his next major release of his mods. 
His way of releasing and bug fixing comes more in waves. When he releases a new major version of his mods he fixes bugs very fast within one or two weeks after the release and then he stops until he releases his next major version of his mods which could take sometimes a while.

**Comment by plaguewolf** [comment] 2015-11-26 00:46
V10. nuff said.

that said, im waiting, impatiently, with bated breath, and hands itching to once more hold a digital pickaxe, for the release of V10, and along with it, forestry 4 support. ive just stopped developing my modpack entirely while i await the relevant mods to update to forestry api v4.

O.O godspeed reika.

**Comment by TomeWyrm** [comment] 2015-11-26 00:47
He's not putting Forestry 4 support into v10. Or at least was not last time I noticed an answer on the subject.

**Comment by walkerjonny** [comment] 2015-11-26 11:22
That would be really bad then...
Let's hope you're not right about this.
Looks like he is waiting for Binnie to update his mods but Binnie only does updates on holidays when he has some time...
That was the reason why I removed Binnies mods from my mods list.

**Comment by ReikaKalseki** [comment] 2015-11-26 13:16
https://github.com/ReikaKalseki/RotaryCraft/blob/master/RotaryCraft.java#L510

**Comment by walkerjonny** [comment] 2015-11-26 15:34
@ReikaKalseki 
Oh, thank you!
Looks like you are catching that exception now. If I understand that right this lets you support both the old Forestry 3.x.x and the new Forestry 4.x.x.
Nice solution!
Well, then I'll be patient until you decide to do your next release.

**Comment by border999** [comment] 2015-11-26 18:34
Achievement unlocked: solution found!

**Comment by ghost** [comment] 2015-12-01 05:55
Okay, question: Do you have anywhere you post downloads for dev builds that may include this fix? If not, Is there any way to compile a version of RotaryCraft with this fix, because I noticed your Github includes solely source code and not your build.gradle or anything? Or am I just going to have to wait for an update? RotaryCraft is a must-have in my game and I'd like to add it.

**Comment by TomeWyrm** [comment] 2015-12-01 06:22
You'll have to wait for an update, just like the rest of the public.

v10 shouldn't be that long in coming. I'd give my personal estimate, but I know better than to give ETAs in public. Sometimes this community is full of those who let their enthusiasm take over their common sense.

**Comment by ghost** [comment] 2015-12-01 06:59
lol alright thanks

**Comment by DeLourium** [comment] 2015-12-22 11:41
now the new version v10 is there and now neither versions of forestry seem to work for me. (neither 3.4 (which i´ve been using without any problems with RC v9b) nor 4.0)

Any ideas why? (or forestry versions that DO work?)

EDIT:
found these lines to be important (with forestry 4.0): 
Caused by: java.lang.NoClassDefFoundError: Could not initialize class
Reika.DragonAPI.ModInteract.RecipeHandlers.ForestryRecipeHelper

i just have no idea what they mean or how to fix this xD

**Comment by spamenigma** [comment] 2015-12-22 13:47
Just done some quick testing with forestry 1.7.10-4.2.2.50 and no crashing issues here. finally i can update my modpack \o/ :+1:

**Comment by ljfa-ag** [comment] 2015-12-22 14:12
Alright, so if it works with the newest Forestry release it should be fine.

**Closed as completed by ljfa-ag** 2015-12-22 14:12 UTC
Labels: Fixed, API Versions

**Comment by DeLourium** [comment] 2015-12-23 15:51
is there any compatibilty to forestry versions prior to 4.x with the v10 of RC?

I recieved this error while using Forestry 3.6: 
RotaryCraft had an error reading Forestry:
Null Item for Apatite

Can I somehow fix this?

Because i cant update Forestry due to problems with updating the forge version

EDIT: never mind xD
just managed to update forge and use the newest version of forestry
AND IT FINALLY WORKS!
