### ISSUE TITLE
Forestry 4 crashs

### ISSUE THREAD

**Issue by chippeweyan1700** [ReikaKalseki/Reika_Mods_Issues#331] opened 2015-10-13 20:06 UTC
title

**Comment by Duckfan77** [comment] 2015-10-13 20:59
Duplicate of #330, #327, #289, #285, #229.

**Comment by ljfa-ag** [comment] 2015-10-13 23:58
For some reason a bunch of people came here all at once reporting the same thing...

**Closed as completed by ljfa-ag** 2015-10-13 23:58 UTC
Labels: Duplicate

**Comment by Duckfan77** [comment] 2015-10-14 00:13
I believe it is because forestry 4 just came out of beta, so people are updating.
