### ISSUE TITLE
Rotarycraft Spawner Controller or Mob Harvester not working without player present

### ISSUE THREAD

**Issue by dwenograd** [ReikaKalseki/Reika_Mods_Issues#469] opened 2015-12-18 22:11 UTC
This is a hard bug for me to pinpoint down onto something specific, because it only happens when I'm not there in person. What I've noticed though is, a mob farm running off of a RC spawner controller and mob harvester stops functioning the moment there's no player nearby.

https://dl.dropboxusercontent.com/u/7662877/RCBug/2015-12-18_13.46.31.png
A few minutes later: https://dl.dropboxusercontent.com/u/7662877/RCBug/2015-12-18_13.48.45.png

Of course, it is getting enough power: https://dl.dropboxusercontent.com/u/7662877/RCBug/2015-12-18_13.50.31.png

And while a player is there, it does spawn and kill the mobs, with more slime in the AE system: https://dl.dropboxusercontent.com/u/7662877/RCBug/2015-12-18_13.50.35.png

It's not an issue of the area not being chunkloaded, just to be sure I did check the boundary:
https://dl.dropboxusercontent.com/u/7662877/RCBug/2015-12-18_14.00.17.png
https://dl.dropboxusercontent.com/u/7662877/RCBug/2015-12-18_14.00.22.png
Everything the entire setup needs to function is in there, and the same chunkloaders when used on the other farming setups and my main base work just fine.

It's not just the slime beetles that has issues, I'm also running into a problem with blazes not working without a player there. It's more than happy to fill that room with an uncountable number of blazes, but once a player isn't present it just stops working.

**Comment by ReikaKalseki** [comment] 2015-12-18 22:58
This has been reported before, and I have never been able to reproduce it.

**Comment by dwenograd** [comment] 2015-12-18 23:02
Could be a bit overkill for a solution, but would it help at all if I zipped up the pack and world, linking them for you?

**Comment by ReikaKalseki** [comment] 2015-12-19 08:33
No, because I would not be able to load it in the dev environment.

**Comment by dwenograd** [comment] 2015-12-19 18:59
Thanks to creative mode and Opis, I've narrowed it down to the spawner controller, or specifically the mobs they create. It seems that the moment the player gets far enough away, all of the mobs that the spawner controller create despawn immediately and don't show up again on the entity list. Extending the amount of loaded chunks made no difference, so it's clearly not that causing it.

**Comment by ReikaKalseki** [comment] 2015-12-19 19:20
This is indeed a vanilla mechanic, but I have - apparently nonfunctional - code to prevent it. And it would explain my inability to reproduce it, since at 128m away the entities do not even render.

**Comment by ReikaKalseki** [comment] 2016-03-30 22:02
I found the problem. Forge only fires the event during the "random despawn" check, not the "far" one.

**Comment by ReikaKalseki** [comment] 2016-03-30 23:37
Hopefully fixed with new ASM.

**Closed as completed by ReikaKalseki** 2016-03-30 23:37 UTC
Labels: Bug, Fixed, RotaryCraft, Can't Fix/Vanilla Bug, Stupid Code
