### ISSUE TITLE
Lumen Essence does not render correctly in RoC Filling Station [no color blend]

### ISSUE THREAD

**Issue by TsumiHokiro** [ReikaKalseki/Reika_Mods_Issues#1728] opened 2017-12-25 05:45 UTC
https://imgur.com/UQHsq91
https://imgur.com/NI2iaUd
Both the Filling Station and the Decorative Tank have Lumen Essence.

**Comment by arceus179** [comment] 2017-12-25 11:32
This is a dupe of 1705.

**Comment by ReikaKalseki** [comment] 2018-04-19 23:26
Fixed. In reservoirs and pipes as well.

**Closed as completed by ReikaKalseki** 2018-04-19 23:26 UTC
Labels: Bug, Fixed, Rendering Glitch, RotaryCraft
