### ISSUE TITLE
Can't hit Endermen when Minefantasy 2 is installed alongside DragonAPI

### ISSUE THREAD

**Issue by tehFoxx0rz** [ReikaKalseki/Reika_Mods_Issues#1438] opened 2017-05-22 20:18 UTC
When I have both Minfantasy 2 (version 2.8.12, link to the mod [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2467203-minefantasy2-alpha) ) and DragonAPI (17b, but previous versions too) installed, Endermen seem unable to register damage coming from the player - punching them causes nothing to happen, and for non-melee things like the shock focus from Thaumcraft, too. It seems to register client-side perhaps (for punching at least), since their mouth briefly opens like they're angry, but only for a brief instant before the Enderman continues acting peaceful as if nothing happened.

In my testing this seems to be possible to replicate with only DragonAPI and Minefantasy 2 installed and nothing else.  Unsure if anything was reported relevant to this in the log, but here it is in case it can help: https://pastebin.com/rRASdkFE

I reported this to the MF2 dev (AnonymousProductions) a while back (as well as in your MCF thread at the same time), but they seem to have since become inactive.

Thanks.

**Comment by ReikaKalseki** [comment] 2017-05-22 20:37
This does not happen to me. What does Minefantasy change?

**Comment by tehFoxx0rz** [comment] 2017-05-23 03:00
I'm unsure out of all the things it adds what could affect Endermen, but it adds different forms of damage (blunt, cutting, piercing) and some different damage multipliers depending on those and how the attack was made (running towards, jumping then crouching while falling, etc.), which is at least to do with mob interaction.

Should have had this in my first post, but in case this makes any difference at all, the Forge version I'm using is 10.13.4.1614.

**Comment by ReikaKalseki** [comment] 2017-05-23 03:33
And this new issue only affects Endermen? I do have some hooks into endermen attacks, but none of them are new to v17.

**Comment by tehFoxx0rz** [comment] 2017-05-23 09:41
It had been happening for previous versions too, yes. It was happening all the way back in January if that helps.

**Comment by ReikaKalseki** [comment] 2017-05-23 21:01
....Why is this only being reported now? At this point the issue is so old that I likely cannot debug it.

**Comment by tehFoxx0rz** [comment] 2017-05-23 22:14
I reported it in your thread back then. [Here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291655-reikas-mods-tech-worldgen-civilization-and-more?page=1442#c29236). I think it was still only last version.

**Comment by ReikaKalseki** [comment] 2017-05-24 00:32
Due to the extreme volume of what is effectively spam ("help my game crashes I'm using Minecraft if it helps"/"Is this for 1.10?"/"Hey I'm using Monster 1.1.1 and I can't craft the engine"), the forum thread is not an effective place to report bugs.

Do you happen to have older versions on hand to try? Without knowing when it was added I cannot do much to look into it, since the likely cause is ASM somewhere.

**Comment by tehFoxx0rz** [comment] 2017-05-24 19:08
Fortunately, I did have some. I managed to narrow it down to being introduced in either V11 or V12 - I didn't have V11, but it was present in V12 but absent in V10. I hadn't started putting together my mods until more recently; I realise these versions are actually rather old, hope they aren't too old. Thank you for being helpful :)

**Comment by ReikaKalseki** [comment] 2017-05-25 01:41
According to the changelog, v11b added the Ender Lock enchantment to ChromatiCraft, which relies on [a DragonAPI ASM patch into EntityEnderman](https://github.com/ReikaKalseki/DragonAPI/blob/master/ASM/Patchers/Hooks/Event/Entity/EnderAttackTPEvent.java). Try disabling that patch by adding the JVM flag "-DragonAPI_disable_ASM_ENDERATTACKTPEVENT". This will break the enchantment but will determine whether this is the cause.

**Comment by tehFoxx0rz** [comment] 2017-05-25 09:50
That appears to have worked, yes!

**Comment by ReikaKalseki** [comment] 2017-05-25 18:32
$%^#...

If the developer is no longer active there is no hope of this being fixed. That said, since you do not have ChromatiCraft, this normally-debug-only workaround may work for you.

**Comment by tehFoxx0rz** [comment] 2017-05-25 19:41
I'll bring it up with them when they come around again. I do use ChromatiCraft normally; would I be able to play it with this disabled in any capacity? Or is the Ender Lock enchantment not so avoidable. (Just wondering what I'm able to about it in the meantime.)
Thanks!

**Comment by ReikaKalseki** [comment] 2017-05-25 20:57
The Ender Lock enchantment will exist but be entirely nonfunctional.

**Comment by ReikaKalseki** [comment] 2017-06-15 20:28
I just looked at his code - he has no ASM. This complicates things severely, as there is now no clear explanation.

**Comment by Sirse** [comment] 2017-07-13 12:41
@ReikaKalseki, MF just listens Forge entity attack entity event, it's very strange bug.

I try to debug it, but can't run DragonAPI in deobfuscated env (https://pastebin.com/TR3D5QJv).

**Comment by ReikaKalseki** [comment] 2017-07-13 16:16
Try adding CodeChickenCore.

**Comment by Sirse** [comment] 2017-07-15 15:14
Already installed (dev version)

**Comment by ReikaKalseki** [comment] 2017-07-15 17:34
I am at a loss; I do not even know what that crash *means*, let alone how to fix it. It looks ASM-related, but my mods obviously work in both dev and non-dev.

**Comment by Sirse** [comment] 2017-07-29 08:25
gradlew setupDevWorkspace - DragonAPI don't work (see crash abowe)
gradlew setupDecomWorkspace - https://pastebin.com/sT5pFxub (just NSFE, waiting for fix)
Works with **DragonAPI_disable_ASM_PERMUTEDBIOMEREG** JVM flag

**Comment by Sirse** [comment] 2017-07-30 14:37
Issue should be fixed via https://github.com/Sirse/MineFantasyII-Cont/commit/12637d6fc52f566d268f25402e0995cddaafa999

**Closed as completed** 2017-07-31 07:56 UTC
Labels: Bug, Fixed, Mod Interaction, Needs Info, DragonAPI, Uncertain Fixability, Reflection/ASM
