### ISSUE TITLE
EnderIO 2.2.8 + Chromaticraft 13b ExceptionInInitializerError

### ISSUE THREAD

**Issue by MineWitherMC** [ReikaKalseki/Reika_Mods_Issues#836] opened 2016-05-18 09:04 UTC
This crash doesn't happen without CC nor it crashes without EIO. And it's not the same as plenty of closed CC/EIO issues.
http://codepad.org/SsSzIBKJ

**Comment by ghost** [comment] 2016-05-18 15:56
Duplicate of #834 #815.

EnderIO is the problem. You do have a different crash but if you're not using 2.3 beta then that might be why it appears different. 

Here's the issue Reika made on EnderIOs tracker: [EnderIO tracker](https://github.com/SleepyTrousers/EnderIO/issues/3298)

**Closed as completed** 2016-05-18 18:34 UTC
Labels: Duplicate
