### ISSUE TITLE
RotaryCraft Centrifuge visibly expands and contracts. V25b

### ISSUE THREAD

**Issue by rkane31174** [ReikaKalseki/Reika_Mods_Issues#2488] opened 2020-05-07 19:46 UTC
This is purely a visual bug and does not affect functionality.

When a centrifuge is powered and left running for a minute or so, it begins to expand and contract as opposed to spinning normally. Faster input speeds seem to make this happen sooner. This occurs in both SSP and on a server.

**Comment by ReikaKalseki** [comment] 2020-05-07 20:32
This only happens for some clients.

**Comment by rkane31174** [comment] 2020-05-07 20:44
Huh... I wonder why.
Should I go ahead and close this seeing as how it can't be reproduced?

**Comment by voidsong-dragonfly** [comment] 2020-05-07 20:53
No. if it's left up it'll still be remembered.

**Comment by Thorinair** [comment] 2020-05-08 09:00
I have this issue as well. It randomly started a few months ago on its own without me changing any mods or any configuration.

**Comment by tiny-maple** [comment] 2020-05-08 09:17
I always thought this was intended, did not really thought of this as a bug.

**Comment by rkane31174** [comment] 2020-05-14 14:40
There's a chance this could be hardware related. I didn't have this problem when I was using my i5-2500k (quad core cpu), but now I have an i7-9700k (eight core cpu) and it's happening. I also have a friend who uses a dell laptop with a dual core cpu (intel pentium something-or-other) and he isn't having this rendering issue.

Anyone having this issue: What CPU do you have?

**Comment by Rubyheart** [comment] 2020-05-14 15:20
I have an i5 and have experienced the same size changes.  The longer it's running, the more pronounced it is.

**Comment by rkane31174** [comment] 2020-05-14 16:00
@Rubyheart How many cores does it have?

**Comment by Rubyheart** [comment] 2020-05-14 16:55
Both my client and the server the world was running on are quad core i5s.

**Comment by rkane31174** [comment] 2020-05-14 17:55
As a temporary solution to issue #2391 I've downgraded my server/client to V23a.
I'm still getting the visual bug in the old version where I previously didn't. I suspect that DragonAPI / RotaryCraft aren't at fault here. Could it be the java version or a windows update? It may even be some GPU setting. Further investigation required.

I have a gaming laptop I can test this on, and I asked my friend (who doesn't have this issue) what java version they have.

I do have to say that I find it interesting that this rendering bug occurs with the RotaryCraft centrifuge and NOT with the ReactorCraft Isotope Centrifuge, or anything else that rotates.

**Comment by rkane31174** [comment] 2020-05-15 16:07
Java version doesn't seem to be the problem. I don't get this visual bug on my laptop despite it having the same java version as my desktop: 1.8.0_251.

At this point I think I've ruled out:
-# CPU cores
-Mods / versions
-OS
-Memory
-java version
-Launch options

Still have to test:
-GPU brand / type
-GPU driver
-CPU clockspeed
-NVIDIA settings

I have one machine where this bug occurs and one where it does not. I'll keep poking at it, but if anyone has any additional insights as to how I could test this, let me know.

**Comment by ReikaKalseki** [comment] 2020-05-15 22:16
I do *not* have it. Here are my hardware specs:

-i7-5200K (8 cores)
-Win7
-16GB DDR3 1600MHz RAM, but it did not happen when I had 12GB either
-Java 8
-Nvidia GTX 1060 6GB graphics card

**Comment by rkane31174** [comment] 2020-05-16 15:59
That's the same GPU I used to have. I didn't have this bug when I used a GTX 1060.
Now I have an RTX 2080 Super. That might have something to do with it, but I can't test it unless I borrow the GPU back from my brother...

**Comment by Barhandar** [comment] 2020-05-16 20:22
The issue happens mostly on AMD cards; as far as I can tell it's because Reika doesn't clamp his rotational angle in any way - the issue starts happening faster the higher you set the speed and the code has speed plainly added to the angle it's supposed to display at - and eventually precision errors accumulate and start screwing with transformation matrix.

**Comment by ReikaKalseki** [comment] 2020-05-16 20:40
People have seen it appear as soon as the machine is first created.

**Comment by Thorinair** [comment] 2020-05-17 02:03
> The issue happens mostly on AMD cards; as far as I can tell it's because Reika doesn't clamp his rotational angle in any way - the issue starts happening faster the higher you set the speed and the code has speed plainly added to the angle it's supposed to display at - and eventually precision errors accumulate and start screwing with transformation matrix.

I have an RTX2070 and also get the bug, so...

**Comment by tiny-maple** [comment] 2020-05-17 11:10
PC spec
i5-4670k (4 core)
8GB RAM DDR3 1600 MHz
Java 8 (I assign either 2GB or 4GB to my modpack) RoC works well with 2GB in the JVM)
Current GPU is gtx 760, and still see this bug, Previously I had a HD7870 and the bug is also observed on it.

**Comment by Folanlron** [comment] 2020-05-24 03:31
I get it on both of my systems, a 960, or my 2080TI.. 

It's the friction heaters "ripple" effect it causes on blast furnaces/furnaces, my 960 I can get it too happen after about 5mins, my 2080 takes about 3hours for it too start.. looks kinda of interesting watching Shaft Junctions constantly shrink/expand, as soon as I turn off my friction heater the issue stops.

**Comment by ReikaKalseki** [comment] 2020-05-25 02:24
> as soon as I turn off my friction heater the issue stops.

Wait really?

**Comment by Folanlron** [comment] 2020-05-25 07:00
> 
> 
> > as soon as I turn off my friction heater the issue stops.
> 
> Wait really?

Yes..

More Info it happens from the beginning if the expand/shrinking is gonna happen, it's very very minuscule at the start(being colorblind, I can't see it till after it runs for awhile), friend told me about it with the server we are running..

**Comment by ReikaKalseki** [comment] 2020-05-27 01:38
Does the issue also happen around running jet engines?

**Comment by rkane31174** [comment] 2020-05-27 12:58
I've tested it in creative connected to an industrial coil. It still happens there.
No microturbines, friction heaters, or jet engines in the entire world.

**Comment by ReikaKalseki** [comment] 2020-05-27 22:48
That does not answer my question. I want to know if a jet engine running will trigger it from a state of not happening.

**Comment by rkane31174** [comment] 2020-05-28 01:18
I don't think I can answer that since it happens even before I activate or even place the jet engine.

**Comment by ReikaKalseki** [comment] 2020-05-28 04:10
You are not @Folanlron who had a more testable condition.

**Comment by Folanlron** [comment] 2020-05-28 06:08
Sorry gonna be swamped for a couple weeks and unable too test..

Network Migrations are a good idea right now... right ?

**Comment by Goddfrey** [comment] 2020-06-26 01:33
![centrifuge acting funny](https://user-images.githubusercontent.com/49716936/85810554-18dd7280-b764-11ea-96d1-8a00bf61b6b1.png)

Playing on single player, restarting (quit to title) and launching again seems to fix the problem for a short while but eventually it starts pulsating again to increasingly smaller sizes. For some reason not every centrifuge acts this way, some are more sane than others. Removing friction heater didnt seem to have any immediate effect.

**Comment by ReikaKalseki** [comment] 2021-03-26 03:37
Fixed in v29.

**Closed as completed by ReikaKalseki** 2021-03-26 03:37 UTC
Labels: Bug, Fixed, Rendering Glitch, RotaryCraft
