### ISSUE TITLE
Crash on startup updating the mods

### ISSUE THREAD

**Issue by lightning02** [ReikaKalseki/Reika_Mods_Issues#924] opened 2016-06-03 19:14 UTC
I update the following mods to the last version avaiable; dragonapi V13b, rotarycraft 13b, reactorcraft 13b, electricraft 13a, territoryzone 13a, cavecontrol 13a
this is the result :/
http://pastebin.com/xfXh1KeR
I've also tryed to delete the configs, but nothing changed

**Comment by redelman** [comment] 2016-06-03 19:24
This is a duplicate of #902 #906 #914 #916 #919 and #921. Also, latest versions are v14.

**Closed as completed by redelman** 2016-06-03 19:24 UTC
Labels: Duplicate

**Comment by ReikaKalseki** [comment] 2016-06-03 23:52
So you get what version you are using wrong, to report an error that does not happen in the version you claim, an error that is on another mod's end and is a duplicate of several others?!

**Comment by Aivech** [comment] 2016-06-03 23:54
We all make dumb mistakes, I guess...

**Comment by TomeWyrm** [comment] 2016-06-04 03:54
Linking the relevant issue for AOBD: ganymedes01/Another-One-Bites-the-Dust#125
