### ISSUE TITLE
Crash with Replication Wand

### ISSUE THREAD

**Issue by globsb** [ReikaKalseki/Reika_Mods_Issues#356] opened 2015-10-22 21:06 UTC
Trying to replicate any structure crashes the game. Ill provide any other information if needed.

http://pastebin.com/Wp9x0HEQ

**Comment by ReikaKalseki** [comment] 2015-10-22 22:08
Caused by an issue in DragonAPI and fixed. For now, do it in creative.

**Comment by Barhandar** [comment] 2017-09-05 20:09
https://gist.github.com/Barhandar/2df99cc844f0843799ba2f857ffea526

Just got it with V18b. Got the crash by trying to place a 2x2 of grass (after trying to place 1x5 of crystalline stone did nothing, with full stack of it in hotbar).

**Comment by ReikaKalseki** [comment] 2017-09-05 20:21
This is the rune crash in #1151.

**Comment by Barhandar** [comment] 2017-09-05 21:05
Also, Replication Star is broken outside of creative. Trying to place a block that is on hotbar (aforementioned crystalline stone) does nothing. Trying to place 1 block of crystalline stone with two stacks of it in inventory, one with 1 item and other with 63 places the block __and consumes both stacks entirely_ while failing to update inventory clientside (requiring player to manually touch an item in it for stacks to change).

P.S. And _of course_ this crash reset my progression.

**Comment by ReikaKalseki** [comment] 2017-09-14 00:48
Fixed on all counts.

**Closed as completed by ReikaKalseki** 2017-09-14 00:48 UTC
Labels: Fixed, Crash, DragonAPI
