### ISSUE TITLE
[ReC] HPT doesn't work with Plutonium/Uranium Reactors

### ISSUE THREAD

**Issue by Kobra331** [ReikaKalseki/Reika_Mods_Issues#2372] opened 2020-03-26 02:29 UTC
I Tested a 5 Blocks tall, 45 Core Reactor filled with Plutonium. There is now 30 000m³ Steam per line and of course filled with lubricant.
The HPT doesn't start to spin.

My Thorium Reactor can start it, but Plutonium/Uranium not.

**Comment by Retovath** [comment] 2020-04-11 08:26
Replicated this -bug- in SMP V25c/b/b Reactorcraft. 100000Cubic meters of steam from a basic fission reactor could not turn a HiP turbine. Spawning in molten salts/boilers/heat exchangers made the turbine start. 

forge-10.3.4.1614
[Modlist](https://gist.github.com/Retovath/1e1ee9b53a933ba1328414abaa297dd3)

**Comment by ReikaKalseki** [comment] 2020-04-22 16:49
Fixed. The issue is in the steam lines, not the turbine; they were not correctly transferring reactor type data. This *does* mean you will need to replace all of them.

**Closed as completed** 2020-04-22 16:49 UTC
Labels: Bug, Fixed, ReactorCraft, High Priority
