### ISSUE TITLE
RotaryCraft V11b crashes when looking up recipies for glowstone dust in NEI

### ISSUE THREAD

**Issue by JeromeJ** [ReikaKalseki/Reika_Mods_Issues#680] opened 2016-03-07 13:59 UTC
It might be crashing when looking up other recipes (but if so, only a few, because most recipes work just fine) but I didn't try ALL recipes as every crash takes me around 5min to start the game again.

```
java.lang.NullPointerException: Updating screen events
    at Reika.RotaryCraft.Auxiliary.RecipeManagers.RecipesGrinder.getSources(RecipesGrinder.java:195)
    at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler.loadCraftingRecipes(GrinderHandler.java:163)
    at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:331)
    at Reika.RotaryCraft.ModInterface.NEI.GrinderHandler.loadCraftingRecipes(GrinderHandler.java:146)
    at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:466)
    at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:20)
    at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:23)
    at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307)
    at codechicken.nei.recipe.GuiRecipe.func_73869_a(GuiRecipe.java:80)
    at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java)
    at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java)
    at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475)
    at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full crash report: http://pastebin.com/c1f9ctnV

**Comment by redelman** [comment] 2016-03-07 14:39
Technically this is a duplicate of #636, which seemed to be a problem on Avarita's end. That was (possibly mis-)reported as https://github.com/SpitefulFox/Avaritia/issues/74, which was marked invalid and thrown back to @ReikaKalseki. In the meantime, if you can, removing Avaritia seems to fix the issue. Alternatively, read #636 to see what information we need to fix this or report it properly to Avaritia or whatever other mod is actually causing the issue.

**Comment by JeromeJ** [comment] 2016-03-07 15:01
As a matter of fact, looking up Tungsten Flakes crashed my game in the same fashion.

Removing Avaritia seems to fix the issue but I would like not having to remove it.

In SpitefulFox/Avaritia#74 , SpitefulFox seems to blame Reika for this issue.

As we are dealing with a mod interaction issue between Avaritia and RotaryCraft, who is going fix it? Can Reika or Spiteful fix it? (I mean, technically, on which end can this be fixed?)

**EDIT:** I tried removing Avaritia and updated my post accordingly to the results.
**EDIT 2:** Now that I know the issue is related to Avaritia, I'm going to try to update it as well.

**Comment by redelman** [comment] 2016-03-07 15:13
The person that reported this to Avaritia included "According to Reika something invalid was registered as stone or cobblestone. Try removing mods." But I can't find anywhere Reika actually said that, which is why I said it was possibly mis-reported. SpitefulFox closed the issue based on that, it seems. 

And now that I look closer, it seems that SpitefulFox recently added a config to disable fractured ores, which is what was suspected to be causing the problems. If Avaritia makes dev builds available (I don't know as I've never used it), I'd try the latest as well.

**Comment by redelman** [comment] 2016-03-07 15:18
Looks like Avaritia-1.11 was released right after the commits were made that should fix the issue on Avaritia's end. You'll need to alter the Avaritia config file to disable the fractured ores, I believe.

**Comment by JeromeJ** [comment] 2016-03-07 15:45
```
Change: Fractured Ores now disabled by default.
```

Yes it fixed it! Thanks @SpitefulFox !

**Closed as completed** 2016-03-07 15:47 UTC
Labels: Fixed, Mod Interaction, RotaryCraft, Crash, Other Mod's End

**Comment by ReikaKalseki** [comment] 2016-03-07 21:13
That is a rather bandaid fix...something is still invalid.

**Comment by SpitefulFox** [comment] 2016-03-07 21:18
It's TTFTCUTS' code and not mine.  I have no idea how to fix it and I'm not attached enough to the feature to really care, so just removing it works for me.  I think trying to procedurally trawl the Ore Dictionary and assign OreDict registrations on the fly was a poor way to go about things anyway.

**Comment by ReikaKalseki** [comment] 2016-03-07 23:08
If that is what was being done, it may well not even have been your item that was causing the error, rather hindering the effort to know what it was...
