### ISSUE TITLE
Using item causes ExU angel ring to stop working

### ISSUE THREAD

**Issue by ray121** [ReikaKalseki/Reika_Mods_Issues#1796] opened 2018-03-22 16:26 UTC
I installed Dragon API, ChromatiCraft, ReactorCraft, ElectriCraft, RotaryCraft, Expanded Redstone, Geostrata and dye trees.
Now whenever I use an item, such as eating food or using a TiC crossbow the flight stops, but not only can i not take off but I can't even double tap space to stop flying, only landing will stop it. This issue also affects my ProjectE armor from using the step up ability 

(sorry for putting this in the wrong issue thread)

**Comment by ReactivePlatypus** [comment] 2018-03-23 04:29
I've had a similar issue happen. It seems to be specific to chromaticraft, based on my own testing. It can be temporarily fixed by dropping and picking up the angel ring. Other conditions I've seen that can mess up the angel ring's flight when chromaticraft is present include:

 - being damaged,
 - being hit by a projectile of any kind, damaging or not,
 - being affected by a negative status,
 - gaining and losing hearts from Absorption or similar statuses,
 - gaining/losing maximum health,
 - basically anything that *could* change your health or hunger in general,
 - equipping the Angel Ring as a bauble with the relevant add-on installed.

I think it's on ExU's end since, one, Chromaticraft's own Floatstone Boots work just fine with ExU installed, and two, I've also had it happen without Reika's mods. From Draconic Evolution, Draconic Armor's creative flight setting seems to override the angel ring when it's active and the ring doesn't take over again if draconic flight is turned off. It just stops working until it's dropped and re-collected.

ExU might have some kind of safeguard against other mods' creative flight items potentially overlapping with its own. Maybe it's fighting with Chromaticraft's Floatstone Boots?

**Comment by ray121** [comment] 2018-03-23 13:18
Maybe, but it was odd that other effects were stopped also, such as the step assist also normally when ExU flight is overridden, you can still stop the flight then you just can't take off again. Also I never had it happen this frequently until I installed those mods which makes me think that something that chromaticraft does makes the items behave poorly.

**Comment by ray121** [comment] 2018-03-24 23:39
Some new info, got the draconic armor and the flight on that armor works and doesnt break like the ExU angel rings

**Comment by MachiavelliSeraphim** [comment] 2018-04-17 17:51
Ive been using the ExU angel ring for the past week and haven't had any odd behavior out of it at all... 
But Im running the latest on everything since I just downloaded it all about a week ago.

Im using MPS for the step up and movement boost abilities... and they work perfectly.

**Comment by Skyler-Altol** [comment] 2019-01-23 09:04
@ReikaKalseki you can mark this as closed, this issue is fixed. It's the one that I was harping on about for several months until we finally pinned down the cause.

**Closed as completed** 2019-01-23 20:14 UTC
Labels: Fixed, Mod Interaction, ChromatiCraft
