### ISSUE TITLE
Rotarycraft start crash

### ISSUE THREAD

**Issue by ghost** [ReikaKalseki/Reika_Mods_Issues#1112] opened 2016-09-03 15:04 UTC
http://pastebin.com/T4kJj5rQ. The game close and i get this crash. I did not tried with only the dragon api. I searched in the issues but only found something about null item stacks in the config file but nothing related found on rotarycraft/dragon api config file. Also super interesting mod. Sorry for my bad english.

**Comment by ReikaKalseki** [comment] 2016-09-03 23:30
This is a mod interaction. Try removing mods.

**Comment by ReikaKalseki** [comment] 2016-09-04 00:28
This is in fact a duplicate of #1085.

**Closed as completed by ReikaKalseki** 2016-09-04 00:28 UTC
Labels: Duplicate, Mod Interaction, RotaryCraft, Crash, @&#%?!, Resolved Itself

**Comment by ghost** [comment] 2016-09-06 20:04
Thanks for the support. The cause of the conflict was forestry version 4.2.15.63.

**Comment by ReikaKalseki** [comment] 2016-09-06 20:10
...What changed in that version?

**Comment by ghost** [comment] 2016-09-22 15:12
I tried with various forestry 4.0.0+ versions and all versions crashed. I did not tried any 3.0.0- version.

**Comment by ReikaKalseki** [comment] 2016-09-22 18:49
4.2.12.60 works for me.

**Comment by ghost** [comment] 2016-09-27 13:40
Still crash :(.

**Comment by ReikaKalseki** [comment] 2016-09-27 18:30
Have you done anything to Forestry? Do you have a broken addon?

**Comment by ghost** [comment] 2016-09-28 21:28
No, only forestry.

**Comment by ReikaKalseki** [comment] 2016-09-29 07:13
...

**Comment by ghost** [comment] 2016-09-29 21:33
I tried with the last 3.X.X version and it still crash. I'm starting to hate forestry.

**Comment by ReikaKalseki** [comment] 2016-09-30 19:16
3 - anything will not work.

**Comment by ghost** [comment] 2016-10-01 22:55
Suddenly, it works.
![2016-10-01_19 46 57](https://cloud.githubusercontent.com/assets/21972487/19017472/04698fa4-8811-11e6-84e3-1f21532b6c11.png)
![2016-10-01_19 47 59](https://cloud.githubusercontent.com/assets/21972487/19017473/0470a118-8811-11e6-8a1b-713fbf569764.png)

**Comment by ghost** [comment] 2016-10-01 22:56
Really really thanks for the support man.

**Comment by TomeWyrm** [comment] 2016-10-02 20:46
@Voidcao which version of Forestry did you end up using?

**Comment by ghost** [comment] 2016-10-02 21:05
4.2.15.63.
