### ISSUE TITLE
Control rods go down when opening world

### ISSUE THREAD

**Issue by traso56** [ReikaKalseki/Reika_Mods_Issues#1559] opened 2017-08-20 01:17 UTC
i didn't test in SMP but in SSP in a test reactor i built everytime i open the world the rods start down shutting down the reactor i can lift them as normal and it works again until next restart .

Also i get this everytime i use the remote CPU

![Alt Text](http://i.imgur.com/O1KoMnJ.png)

I use customNPCs and galacticraft but removing these mods does not solve the problem
It Does work normally but i don't know what that means i can provide logs if needed

**Comment by ReikaKalseki** [comment] 2017-08-20 04:09
Is it accompanied by a sound?

**Comment by traso56** [comment] 2017-08-20 04:59
it isn't
the rods start down and i can't hear the sound of the CPU running out of power or something like that

**Comment by traso56** [comment] 2017-08-26 16:50
is everything going right? if needed i can provide video or logs

**Comment by ReikaKalseki** [comment] 2017-08-26 18:06
A video might help.

**Comment by traso56** [comment] 2017-08-27 03:19
https://youtu.be/vEck3vwqwFA

**Comment by ReikaKalseki** [comment] 2017-08-27 03:30
I wonder if that recent code change I made to the CPU fixed it...

**Comment by traso56** [comment] 2017-08-27 20:03
i hope that fixes it

**Comment by ReikaKalseki** [comment] 2017-08-31 03:37
As suspected, the cause is a no-power SCRAM on the first tick of a world being loaded. There is no clean fix for this, as the implementation of RC power necessitates up to one tick per power transfer tile (shaft, gear, etc). I have put a 20-tick timer on it, so that it cannot SCRAM in the first one second of a world, but a geartrain longer than 20 tiles will still have this issue. Larger timers are not an option as they will begin to interfere with intended functionality.

**Closed as completed by ReikaKalseki** 2017-08-31 03:37 UTC
Labels: Fixed, ReactorCraft

**Comment by traso56** [comment] 2017-08-31 16:27
sounds fair my geartrain isn't vey long so i hope that solves it
