### ISSUE TITLE
Does the extractor always cascade as intended?

### ISSUE THREAD

**Issue by davebx** [ReikaKalseki/Reika_Mods_Issues#2611] opened 2020-07-08 03:47 UTC
Sometimes when I'm before the point where I can power an extractor without switching from torque mode to speed mode, I'll have four turbines powering an extractor. Unfortunately, when I use the screwdriver to switch from speed to torque, so that I can complete the middle stages, the extractor doesn't seem to realize that it has compatible input material in the secondary slot, so all 64 intermediate products have to wait until the slurry or whatever stage is done before it realizes that oh hey, I have input materials.

**Comment by davebx** [comment] 2020-07-08 03:51
And before you accuse me of being an incompetent programmer, _look at my github history_

**Comment by ReikaKalseki** [comment] 2020-07-23 19:29
The "cascade" is always checked, every tick, for the four stages independently. The only limiter is the sizes of the stacks and the return value for `getNumberConsecutiveOperations`, but neither of those should ever be less than one, so you should see, at minimum, one item be moved per tick, assuming there is space to do so. This is not even dependent on having enough power to run the machine; it cascades regardless (just with the minimum value of one).

**Comment by ReikaKalseki** [comment] 2020-07-23 19:37
I just checked and I cannot get it to "stall".

**Comment by Schadrach** [comment] 2020-08-19 22:19
FWIW, it happens for me too.  Was much more noticeable when running it at extreme speeds.  Have a turbine at 835.584MW connected to a turbine flywheel, then through a 16:1 bedrock gearbox set for speed then a bevel gear and the extractor.  One import bus, one fluid anchor to supply water, and three export buses connected to it.

It routinely fails to pass items from the output of one step to the input of the following step, especially step 1->step2.  When this happens, items will not move until the input stack for that step is empty, then the output from the previous step transfers over and it starts behaving as intended for a while.

It occasionally did it when I had it connected to a stack of hydros (4 rows of 16, bedrock upgraded shaft junctions tying it all together, geared as much for speed as possible while still running all 4 stages), but it was much more noticeable after moving it to the turbine.

**Comment by ReikaKalseki** [comment] 2020-08-21 18:19
Are you sure the items exactly match? It cannot cascade if the stacks are not combinable.

**Comment by Schadrach** [comment] 2020-08-21 22:50
I've seen it happen with vanilla ores.  So unless sometimes iron ore produces slightly different items for a given step that's not it.

**Comment by davebx** [comment] 2020-08-23 17:07
@Schadrach considering the quality of the 1.7.10 code (not that other versions are better), nothing would surprise me.

I'm shrugging. It's not a deal-breaker in any remotely conceivable way, just an awkward fiddle in the mid-game stage.

**Comment by ReikaKalseki** [comment] 2020-08-24 18:47
`considering the quality of the 1.7.10 code (not that other versions are better), nothing would surprise me.` The hell?

**Comment by davebx** [comment] 2020-08-25 04:36
Do you really want to claim that minecraft 1.7.10 is good code?

**Comment by ReikaKalseki** [comment] 2020-08-25 20:20
No, but the vanilla codebase has no relevance here beyond the simple functionality of inventories and ItemStacks themselves, which are pretty reliable.

**Comment by BlueAgent** [comment] 2021-01-29 08:56
Referencing the code [here](https://github.com/ReikaKalseki/RotaryCraft/blob/c788b228bb508aa60570fce6595ab0eccff0b96f/TileEntities/Processing/TileEntityExtractor.java#L149-L158):
<details>
<summary>Click for copy of code</summary>

```java
else if (inv[i].stackSize < inv[i].getMaxStackSize()) {
	if (ReikaItemHelper.matchStacks(inv[i], inv[i+3])) {
		int amt = Math.min(inv[i+3].stackSize, inv[i+3].getMaxStackSize()-inv[i+3].stackSize);
		amt = Math.min(amt, this.getNumberConsecutiveOperations(i));
		if (amt > 0) {
			inv[i].stackSize += amt;
			ReikaInventoryHelper.decrStack(i+3, inv, amt);
		}
	}
}
```
</details>

`inv[i]` is the input slot of a stage.
`inv[i+3]` is the output slot of the previous stage.

The starting value of amt should probably be changed from:
```java
int amt = Math.min(inv[i+3].stackSize, inv[i+3].getMaxStackSize()-inv[i+3].stackSize);
```
to:
```java
int amt = Math.min(inv[i+3].stackSize, inv[i].getMaxStackSize()-inv[i].stackSize);
```
Since I think we want to take the `min(output slot size, remaining space in input slot)`

**Comment by ReikaKalseki** [comment] 2021-02-04 00:16
And the first i+3 should in fact be just i. This looks like I put the +3 in the wrong place when implementing your "faster cascade" that you asked for last January.

**Closed as completed by ReikaKalseki** 2021-02-04 00:16 UTC
Labels: Bug, Fixed, RotaryCraft
