### ISSUE TITLE
ChromatiCraft freezes the game by using NEI on GregTech items

### ISSUE THREAD

**Issue by xXGandalfXx** [ReikaKalseki/Reika_Mods_Issues#668] opened 2016-03-03 13:48 UTC
Hey,

the game freezes completely when i look into the usage recipes of GregTech items... I don´t know if GT or CC causes this, but i think it´s Chromati... There is no crash report or something, because the i need to kill the game with task manager.

I use Chromaticraft v11b, GregTech 05.09.19 and NEI 1.0.5.120

**Comment by ReikaKalseki** [comment] 2016-03-03 15:35
Does this happen without CC installed?

Also, if you have v10 on hand, try that. I have a suspicion as to what it is. Also, you can try confirming that suspicion by holding LCTRL when mousing over one of the crashing items (to pull up the little "elemental composition" render).

**Comment by xXGandalfXx** [comment] 2016-03-03 16:19
No, it doesn´t happen without CC.

Sry, i do not have v10... Is there a download link for older versions? But i tested it with v9b and the crash doesn´t happen.

And btw nothing happens by hover over the item and press LCTRL

**Comment by redelman** [comment] 2016-03-03 16:44
I have v10b laying around on my HD, and can make it available provided Reika agrees. Older versions are generally removed from Curse once new ones are available. This is to keep people from downloading old versions and reporting bugs that have been long since fixed, among other things.

**Comment by ReikaKalseki** [comment] 2016-03-03 18:45
v9b also works.

If LCTRL does not do anything, try LSHIFT.

**Comment by xXGandalfXx** [comment] 2016-03-03 19:13
Same again. Nothing happens with LSHIFT

**Comment by ReikaKalseki** [comment] 2016-03-03 22:57
Then I have no idea why a uses lookup gets stuck in an infinite loop....try turning on debugging in DragonAPI, looking for ItemElementCalculator or calculating element tags/value for an item.

**Comment by xXGandalfXx** [comment] 2016-03-04 15:15
Hmm... sry, i don´t know what you mean with calculating element tags.

And there is no ElementCalculator...

**Comment by ReikaKalseki** [comment] 2016-03-04 20:59
It turns out the debug prints were disabled. Still, looking up uses, and not the ItemElementCalculator, should not cause a crash. The only new NEI handler in v10 that I can see causing this is the one for the Transmutation Flame, which uses ItemElementCalculator.

**Comment by xXGandalfXx** [comment] 2016-03-04 21:39
Hmmm Ok

But i don't understand why only the usage of gregtech items causes a crash. All other items are working perfectly...

**Comment by ReikaKalseki** [comment] 2016-03-04 22:27
Does GT have any infinite recipe loops?

**Comment by xXGandalfXx** [comment] 2016-03-04 22:35
I'm not sure. I have not noticed something like that

**Comment by Duckfan77** [comment] 2016-03-05 01:12
I believe that it may, as if this hasn't changed recently there was a way to disassemble the machines for some of the components used to create it.

**Comment by ReikaKalseki** [comment] 2016-03-05 03:27
I have no idea.

**Comment by Duckfan77** [comment] 2016-03-05 18:38
I asked in the Gregtech thread, there are recipe loops that show up within NEI.

**Comment by ReikaKalseki** [comment] 2016-03-05 20:22
Using only the vanilla table and/or smelting? My only guess here is that it is recursing infinitely when parsing the recipe for a given item (in trying to calculate its value), and if the recipe never loops to a full match (including NBT), it will never complete.

**Comment by Duckfan77** [comment] 2016-03-05 20:24
That I am not sure of. I would recommend asking in the thread, as you most definitely know more about what would cause issues in your code than I.

**Comment by mysticviperx** [comment] 2016-03-07 21:07
Greg tech is not the only mod that suffers from CC v11b, MagicalCrops, and EnderIO are also freezing when CC is installed. I would test more mods, but it takes 10 min for my client to boot up.

Removing CC removes the 'freeze bug', currently testing 9b version of CC. (and there went MeteorCraft...) But more errors have come up, gave up...9b is its own ball of doom with Forestry4.

**Comment by Aivech** [comment] 2016-03-08 11:59
For v9 and previous you need forestry 3.
v10 and later require forestry 4.

**Comment by xXGandalfXx** [comment] 2016-03-08 19:34
ProjectRED freezes also... :(

**Comment by ghost** [comment] 2016-03-11 05:56
I found that the loops are not infinite, and are instead just very long. (5-6 min)  It seems to be caused when mods use lots of interconnected recipes that can cause one item to look through tons of recipes taking a very long time.  Gregtech suffers from this more than most as it adds meta tools than can be made from any material to process any other material or even itself causing some items to be linked to thousands of others.

At least the caching causes this to only occur on the first item that is connected like this, additional lookups are much faster.  

Perhaps a limit to the number of items to search through or more blacklisted/hard coded values can prevent the search from taking too long?

**Comment by ReikaKalseki** [comment] 2016-03-22 13:48
I put in some loop length limits; this will hopefully fix the issue.

**Comment by J-swl** [comment] 2016-03-31 13:03
For mentioned above,the same problem occurs when I only use Chromaticraft V12c, Gregtech 5.08.33 Unofficial,NotEnoughItem1.0.5.120-universal(all of them are in the latest version) in the same mod pack.I tried to look up for the usage of bowl and I press the U key,then the game freezed.
The .log file is here.
https://paste.ee/p/wnQif

**Comment by ReikaKalseki** [comment] 2016-03-31 14:16
Did it ever start responding? What are your computer specs?

**Comment by J-swl** [comment] 2016-03-31 18:01
I waited about 20 minutes,then it start responding(TvT~I'm sorry if I was a little short with you..But when the problem occurs the first time and after 5 minutes waiting,I shut down the process) .My computer specs...let me see...With i7-Intel 4790K,Nvidia GTX970,16G.And allocate 8G ram to Java.
BTW, I tried the earler version of your mods and the problem does not occurs.The version I tried was V10b.

**Comment by ReikaKalseki** [comment] 2016-04-01 00:44
I added nothing new to this system in v11 or v12.

**Comment by J-swl** [comment] 2016-04-01 05:26
Since you said that "Also, if you have v10 on hand, try that. I have a suspicion as to what it is. Also, you can try confirming that suspicion by holding LCTRL when mousing over one of the crashing items (to pull up the little "elemental composition" render)."
I tried to do this and game freezed with v10,and still running properly with v12...But when I use v12c,almost every time I press U above an item and game freezed.In a modpack only have chromaticraft,gregtech and NEI,this prolem only occurs when I join the game and looking for something's usage at the first time this round. It's really confusing.
Finally,thank you for your patient and I'd like to find a way to remove my U key physically.;)

**Comment by xXGandalfXx** [comment] 2016-04-13 15:54
Hmm... this bug is still not fixed :(

**Comment by ReikaKalseki** [comment] 2016-04-13 20:43
And I still have yet to see it.

**Comment by outlawtorn316** [comment] 2016-05-14 14:45
Even though it is closed I am hoping I can clarify the situation a little. I'm assuming this is the EXACT same issue J-swl had, but his pastebin expired so I can't double check. This is definitely a Gregtech issue. I'm using GT Unofficial 5.09.21 with the latest version of your mods, V.13B. Included is a log with debugging on. My log is so huge I can't pastebin it, so I had to zip it and place it on Mega (sorry for the inconvenience).

The fun starts at [08:54:35] but really becomes an issue at [08:55:18]. The player action was hitting "u" while highlighting "Impure Iron Dust" (it actually happens anytime I recipe check a gregtech item with meta data attached) As you can see from the time stamps this locks my game for almost an hour. Once it runs though then I can recipe check without any issue, it's just the first lookup sequence, however waiting for an hour for a game to "load" is some what maddening.

Even though I am sure this is a solely a gregtech issue, I was hoping you would have any ideas short of removing either CC or GT from my mod files. I appreciate your time and patience for reevaluating this issue,  and even if there is no "fix" short of removing the mods listed above, I was hoping that maybe I can prevent people having the same problem from bashing their faces against a keyboard wondering WTF was going on. Thanks again!

Log link -->  https://mega.nz/#!tVFwEDSa!jhD16zxIRF-vsSQW7gqnL-AY9zYAHFE9Gfzbmf_RaU4

**Comment by ghost** [comment] 2016-07-14 04:55
Seems to persist with CC V15a GT Unofficial 5.09.23 
Begins at [22:32:14] 

Log: https://zerobin.net/?4ba091e6872c987c#8CIZ8IjOlEaEKUgdJueoN5R6A6m7Qbi6cpuyJBA9E4U=

**Comment by SeppDE** [comment] 2016-08-02 19:28
Like i posted there (https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1076) the bug is still there.

Reika? Do CC save the recipes only for the current "season"?
The reason i asked is it could be an fix to save the recipes till anything block or item related changed. 
If CC already did this than something changes every time MC get started.

**Comment by ghost** [comment] 2016-08-02 19:40
The problem is interconnected recipes.  This happens with other mods as well, but not to the extent as it does with gregtech.  Nothing is really wrong, it's just the size of what it has to look through.

What is happening in this case is the gregtech tools being able to be made out of any material are causing the search to be very deep and broad.  For example with planks:
each plank can be made with the log + a saw (~1000 different ones)
each saw can be made with the plate + some sticks
sticks can be made with planks + a saw (~1000 different ones excluding those that have been done)
each plate can be made with the ingot + a hammer (~1000 different ones)

This means for this one recipe you are looking at millions of recipes with a depth of only 3. It would continue to grow larger because of the interconnections with greater depth, but you have already limited that.

However, most of these items end up having a value of 1 of each color anyways because of the nature of the search so perhaps you can just terminate the search once it reaches that point as it will no longer make a difference

**Comment by ReikaKalseki** [comment] 2016-08-02 21:27
> However, most of these items end up having a value of 1 of each color anyways because of the nature of the search so perhaps you can just terminate the search once it reaches that point as it will no longer make a difference

It could easily reach more than one of any color.

**Comment by ghost** [comment] 2016-08-05 15:49
I recall looking through the calculator before that each addition takes the lower of the values of the previous items down to a minimum of 1. So once it reaches 1 the minimize will always pick 1 correct? This seems to be right as every single item that causes this problems ends up costing 1 in every color. Unless it's not always minimized?

**Comment by ReikaKalseki** [comment] 2016-08-05 18:52
Oh, does it? In that case, yes, you _could_ put a stop condition here.

**Comment by ReikaKalseki** [comment] 2016-08-05 20:00
Implemented.

**Comment by ghost** [comment] 2017-02-06 16:50
Is this fix released in V16d?

Cause right now running fresh Chromaticraft of version V16d (which is released after Aug 5, last comment on this bug) I still have NEI freezing after using "Uses" function on some items, namely flawless or exquisite gems from GregTech.

**Comment by ReikaKalseki** [comment] 2017-02-06 19:24
At this point, I am not sure what else there is that can be done.

**Comment by ghost** [comment] 2017-02-06 20:23
So, the current fix (mentioned in comments) is released, and either its a new issue either its problem on my side, right?


edit: its not big deal (original problem e.g) at this moment anyways, since it takes about 5 minutes for first "uses" search and after that its quite fast (5 seconds give or take). 


However, there -might- be a balance issue: every GregTech dust I've tested looked like this

http://imgur.com/a/SYRaN


every gem, every small dust, every everything looked like this. To give the context: this dust might be crafted to 4 small dusts or 9 tiny dusts, every of those tiny/small dusts would be 10 of each color as well.

This might be somehow related to GregTech meta tools that are used in possible recipes for such items, as some meta tools might have super-high-value items as ingridients (you can make a hammer out of steel, but you can make same hammer out of naquadah or anything else you have in mind; and every such hammer would only be different by NBT data). Just guessing here.. 

It may be worth it to block GT materials from Lumen Transmutation System, if such possibility exists.

**Comment by LukaPix** [comment] 2017-04-05 14:08
Would it be possible to just blacklist all GT items for Chromaticraft Recipe Calculation ?

**Comment by ReikaKalseki** [comment] 2017-04-06 16:47
Not particularly difficult, but also not an approach I really want to do.

**Comment by OvermindDL1** [comment] 2017-04-06 16:58
Its not just GT, any mod with long recipe lists causes it too.  It takes a *very* long time to process the first time certain things are accessed (usually putting some non-ChC item on one of those bowl things in the alter), about 5-10 minutes, but every time after that until shutdown is fast.

**Comment by ReikaKalseki** [comment] 2017-04-06 23:35
> but every time after that until shutdown is fast.

It caches the calculation result.

**Comment by LukaPix** [comment] 2017-04-07 12:37
could this be written to a file and loaded on world join if the same mods are still present ?

**Comment by ReikaKalseki** [comment] 2017-04-07 17:47
Perhaps....

**Comment by 1Matthias** [comment] 2017-04-07 22:12
Probably not. That might lead to the scenario of someone starting a world,
doing some stuff with it for a little while, including having CRC calculate
some of the recipe costs, then exiting, minetweaking/editing configs (Which
changes the calculations), then re-joining and CRC still using the old
calculated values, which are now incorrect.

**Comment by ghost** [comment] 2017-04-09 12:40
Why not calculate all that stuff on game start, or on world start, instead of calculating that in-game? Long loading times is something you except when running modded mc anyways.

**Comment by OvermindDL1** [comment] 2017-04-10 14:10
> Why not calculate all that stuff on game start, or on world start, instead of calculating that in-game? Long loading times is something you except when running modded mc anyways.

Things like minetweaker can entirely change the recipes of about everything, so pre-caching, though nice, should be double-checked at run-time and if it does not match then at least 'that' recipe should be re-cached.

**Comment by Barhandar** [comment] 2017-08-19 08:34
Alternately, can it not simply _ignore Greg's metatools_? The recipes only show the main metatool, not all the NBT variations it has, and it's irrelevant which material tool is made of, they all behave in recipes identically. Thus parsing all possible variations is entirely pointless.

**Comment by ReikaKalseki** [comment] 2017-08-19 14:59
The calculator has no way of knowing - semantically - what the item is or what it is for, much less how similar it is to other things.

**Comment by Barhandar** [comment] 2017-08-19 16:38
>The calculator has no way of knowing - semantically - what the item is or what it is for, much less how similar it is to other things.

So it's not aware of the ID, both item and modname parts?

Any way to disable the calculator/NEI integration altogether, then? I'd rather not have to wait 20+ (literal, also results in ticklag in SP, adding inability to interact with things after the freeze) minutes every time I restart the game and want to look something in 'U', or abstain from looking up usages altogether. And not seeing Chroma's things like which aura kudzu drops which item or how many lumens an item will produce in an unknown processor that is completely inaccessible at this progression stage is acceptable drawback.

**Comment by ReikaKalseki** [comment] 2017-08-19 17:57
> So it's not aware of the ID, both item and modname parts?

That it knows, but to what end?

**Comment by Barhandar** [comment] 2017-08-19 18:01
>That it knows, but to what end?

Ignore items from mod gregtech/ignore `gregtech:gt.metatool.01:*` (and IDs for the tool heads for metatools/recipes that involve GT item + `minecraft:stick`) (optionally if any matching has already been scanned), both in input and output of the recipes (and thus skip such recipes immediately).

That is, assuming the issue _is_ in fact caused by the crafting recipes for the metatools.


...huh, going by code metatool heads are on same ID as metatools themselves. I'll check tomorrow.

**Comment by ReikaKalseki** [comment] 2017-08-19 20:10
I added code to skip anything whose internal item name contains "gt.metatool".

**Comment by Barhandar** [comment] 2017-08-20 06:18
That will work for recipes using metatools, and recipes producing metatools, toolheads for them are gt.metaitem.02 - which also includes turbine blades, long rods, fine wiring, rotors, gems and food.

I've just had the _second_ freeze in same game launch, from 'U'-ing PHC apple cider (first was intentional from U on enchanting table, Ascension of the Technomancer pack). How far in both directions does it even search?

**Comment by Barhandar** [comment] 2017-08-20 10:50
I've just had the _second_ freeze in same game launch, from 'U'-ing PHC apple cider (first was intentional from U on enchanting table, Ascension of the Technomancer pack). How far in both directions does it even search?

**Comment by ReikaKalseki** [comment] 2017-08-21 02:13
> How far in both directions does it even search?

Infinitely, stack depth notwithstanding.

**Comment by Barhandar** [comment] 2017-08-21 07:22
Uh-huh. Please do cache them persistently and calculate for things missing from cache only, if possible.

**Comment by ReikaKalseki** [comment] 2017-08-21 17:03
I do.

**Comment by Barhandar** [comment] 2017-08-24 05:25
I mean, persistently across game quits. Slightly longer loading time for cache (_if_ it'll be slight in comparison to full calculation) is preferable to in-game hang for a number of minutes.

Also half the items are 10-d on the lumens due to this.

**Comment by ReikaKalseki** [comment] 2017-08-24 06:46
> if it'll be slight in comparison to full calculation

It would not.

**Comment by Barhandar** [comment] 2017-08-29 13:58
Yeah please excise GregTech altogether from the calculation. Being unable to use its machines and metals for lumens is a small price to pay for not getting frozen for half an hour total every time the game is started with errant 'U's and Ctrls (because with progression holding Ctrl over items displays lumens and has to calculate if the cache is missing).

**Comment by ReikaKalseki** [comment] 2017-08-29 18:09
A better solution would be to hardcode the values of a few items, which should stop the recursive calculation.

**Comment by Barhandar** [comment] 2017-09-04 15:11
How would the items to hardcode be determined?

**Comment by ReikaKalseki** [comment] 2017-09-04 18:15
Someone familiar with GT would have to tell me the internal names and what they are made of and/or for.

**Comment by Barhandar** [comment] 2017-09-05 09:59
>Someone familiar with GT would have to tell me the internal names and what they are made of and/or for.

The problem is metaitems, and as such you _cannot_ say what they're made of and what for at compile time. It includes anything from copper screws to steel plates to helium plasma. Only way to tell would be writing full-on GT integration that [accesses its metasystem](https://github.com/Blood-Asp/GT5-Unofficial/tree/unstable/src/main/java/gregtech/api/items), which, uh, I believe would be far longer than "if(id.contains("gregtech") continue;" as well as probably freezing the game just as well.

https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/items/GT_MetaGenerated_Item_01.java  
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/items/GT_MetaGenerated_Item_02.java  
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/items/GT_MetaGenerated_Item_03.java  
https://github.com/Blood-Asp/GT5-Unofficial/blob/unstable/src/main/java/gregtech/common/items/GT_MetaGenerated_Tool_01.java

**Comment by OvermindDL1** [comment] 2017-09-05 14:34
> Only way to tell would be writing full-on GT integration that accesses its metasystem, which, uh, I believe would be far longer than "if(id.contains("gregtech") continue;" as well as probably freezing the game just as well.

Actually it's system fully encodes all data into the item information so querying for stats is fairly instant.

Minecraft is horrid in how it's recipe system works, but gregtech has a duplicate of the recipe system in it's setup that is based on a hash system for near-instant lookups instead of linear like Minecraft's stock system is, but you'd have to depend on it to use that (but would make all recipe lookups *significantly* faster that using the stock Minecraft recipe manager), so not really a capability.

GT5 (as @Barhandar linked above) is the older GT, it does not have a lot of the additional features that GT6 does either (GT6 even uses a custom recipe handler for it's meta recipes that I alluded to that these mods could do too previously) so GT6 should not cause the issue regardless from item count since it does not expose its items via the recipe manager directly but only via shapes.  GT5, however, exposes them individually, which is fine in a hashing recipe manager, but anything that iterates over a linear recipe manager (like ChC) fails on pretty hard.

**Comment by ReikaKalseki** [comment] 2017-09-05 16:35
> Actually it's system fully encodes all data into the item information so querying for stats is fairly instant.

Elaborate?

**Comment by OvermindDL1** [comment] 2017-09-05 16:40
GT6's (and GT5's as I recall) meta-items are items that have an 'id' (which is the 'damage' value of the itemstack) along with stats like what material it is made from and so forth encoded into the NBT, so it looks up based on that in custom recipe handlers and machine interfaces (like when right clicking a machine with a tool).  Even damageable tools is just data on the NBT (the 'damage' field on an itemstack is purely for ID usage).

There are interfaces from GT that make querying item information really fast, but still, unless you actually use anything from GT there is no point and should just ignore anything that you do not explicitly handle, from any mod, not just GT.

**Comment by ReikaKalseki** [comment] 2017-09-05 20:22
So in other words, I can read the NBT manually?

**Comment by OvermindDL1** [comment] 2017-09-06 14:17
> So in other words, I can read the NBT manually?

Yep yep, you can see the open source to see what is stored.  Or just ignore/blacklist it all.   ^.^

Do note, a lot of things on the NBT are enumerations to very large and detailed lists of `Material`'s as one example, so if you need to map specific materials you may need to hard-code a few values instead of doing those lookups.

**Comment by ReikaKalseki** [comment] 2017-09-06 17:45
I know. Can I see some of these entries?

**Comment by OvermindDL1** [comment] 2017-09-06 19:37
You can dump an itemstack nbt via normal in-game means as one example, but otherwise what specific information do you want to get from the NBT?  You can see the source of his entire API at http://gregtech.overminddl1.com/com/gregoriust/gregtech/gregtech_1.7.10/6.05.38/gregtech_1.7.10-6.05.38-sources.jar (or for GT5 it is similar but not as refined, and yes he has odd naming conventions but they make senseish once found out what they are).

His system overall works like:

1. First you create a Material or grab an existing one, creating one is like:
  ```java
  // Instance a new material with name Examplium
  gregapi.oredict.OreDictMaterial tExamplium = gregapi.oredict.OreDictMaterial.createMaterial(32766, "Examplium", "Examplium");
  // Give it some attributes, there are a *lot* more, everything from atomic weights to melting and
  // boiling temps to thaumcraft aspects and far far more, all done in the same way as this example,
  // which makes it smeltable in a vanilla furnace:
  tExamplium.add(gregapi.data.TD.Processing.FURNACE);
  ```
2. Decide whether to create a new prefix (think `ore` or `gear` or something)  via `final gregapi.oredict.OreDictPrefix tExamplePrefix = gregapi.oredict.OreDictPrefix.createPrefix("exampleprefix");` or just use an existing one (there are a lot of existing ones to choose from).  The prefix is used as the ore dictionary prefix, so a gear of steel has the ore dictionary name of `gearSteel`, they all follow the `shapeMaterial` style of naming (this is often the easiest way to find out what something is in GT, if you want a screw of iron then just accept anything that is oredict'd with `screwIron`, in addition to defining an ore dict with the material and shape's themselves as well).
3. There are many types of items, many 'do' nothing, like a screw does nothing, primarily just used as recipe ingredients, to things like tools and weapons and even machines.
4. Then to get an itemstack of an item you need to define the shape, material, and type of the item.  There are utility classes that make doing this (and about anything in GT) very simple:
   * Easiest way to get a stack of, say, 20 examplium (see where I made examplium above) screws is `gregapi.data.OP.screw.mat(tExamplium, 20)` and the returned itemstack has all the stats set, where the 'damage' is the internal item id that defines the shape and material, and the nbt includes at this point not much for this basic call, but if it was crafted then it would include the input resources (so crafting a machine out of ingredients encodes the materials of those ingredients, so making a bronze machine encodes that it is made up of some parts of bronze of a specific amount, this is so you can melt things back down and/or disassemble them in certain ways back into what they were made instead of just generic/wrong items).

If you give a specific example of what you want to look up then I can explain in detail how that specific aspect is (but in general checking the ore dict is what you are looking for for generic shape and/or material).  But use NEI with ore dictionary entries displayed and the F3+H mode to see most of the useful bits of a gregtech item.

In what cases is it useful to check for gregtech items on a pedestal anyway's I'm curious?

**Comment by ReikaKalseki** [comment] 2017-09-07 08:11
> In what cases is it useful to check for gregtech items on a pedestal anyway's I'm curious?

In calculating what elements are there for particle display, lumen decomposition, and so on.

**Comment by ReikaKalseki** [comment] 2017-09-15 00:15
So if ore names contain useful material information, this new parser should fix the issue.

		int[] ids = OreDictionary.getOreIDs(is);
		for (int i = 0; i < ids.length; i++) {
			String name = OreDictionary.getOreName(ids[i]);
			OreType ore = ReikaItemHelper.parseOreTypeName(name);
			if (ore != null) {
				ElementTagCompound tag2 = ItemMagicRegistry.instance.getValueForOreTypeName(ore);
				if (tag2 != null)
					tag.addButMinimizeWith(tag2);
			}
		}

		if (!tag.isEmpty() || is.getItem().getUnlocalizedName().contains("gt.metatool")) { //hopefully avoid deep recursion
			return tag;
		}


	public static OreType parseOreTypeName(String name) {
		Matcher m = ORE_MATERIAL_PATTERN.matcher(name);
		return m.find() ? getOreType(m.group()) : null;
	}

	public static OreType getOreType(String name) {
		OreType ore = ReikaOreHelper.getByEnumName(name);
		if (ore == null)
			ore = ModOreList.getByEnumName(name);
		return ore;
	}

**Closed as completed by ReikaKalseki** 2017-09-15 00:15 UTC
Labels: Mod Interaction, Needs Info, ChromatiCraft, Awaiting New Release
