### ISSUE TITLE
ReactorCraft: Control Rods all lowered upon world unload (i.e. save-quit and reload)

### ISSUE THREAD

**Issue by Fatmice** [ReikaKalseki/Reika_Mods_Issues#810] opened 2016-05-13 00:52 UTC
1.7.10-V13b
This issue was supposedly fixed back in 1.6.4-V20.  The fix appears to have regressed.

**Comment by Barhandar** [comment] 2016-05-13 12:23
Saved and quit, reloaded, rods raised. Saved and quit, closed instance, launched instance, joined world, rods still raised. No updating alert so I presume latest versions same as you.

Provide your circumstances, because stated error doesn't happen with uninterruptible power supply (creative coil) with reactor controls and their supply being in same chunk.

**Comment by Fatmice** [comment] 2016-05-13 13:39
Why don't you use the files that I provided and see for yourself.  My rods always lowered on reload.  Do you know how long I've played this mod?
http://www.mediafire.com/download/wnmzfy0994f9dkd/1.7.10-Thorium_Experiments.7z

**Comment by ReikaKalseki** [comment] 2016-05-13 18:28
>  Do you know how long I've played this mod?

Long enough that it helped inspire a Factorio mod a year ago. :P

**Comment by ReikaKalseki** [comment] 2016-05-15 23:27
I cannot reproduce it either. Whatever your issue is, it is either one of mod interaction or power supply that does not function the first few ticks of world load.

**Closed as completed by ReikaKalseki** 2016-05-15 23:27 UTC
Labels: Can't Reproduce, ReactorCraft, @&#%?!

**Comment by Fatmice** [comment] 2016-05-16 23:29
Did you use my world save and mods that I provided to test?

**Comment by ReikaKalseki** [comment] 2016-05-17 00:59
No, because I cannot load that in the dev environment. I cannot test an issue outside of it.

**Comment by Fatmice** [comment] 2016-05-17 01:10
I'll make some tests then and isolate the issue if I can.

**Comment by Fatmice** [comment] 2016-05-19 04:52
So I tested this issue on a fresh world with minimal mods
Forge:10.13.4.1558-1.7.10
DragonAPI:1.7.10V13b
ReactorCraft:1.7.10V13b
RotaryCraft:1.7.10V13a

Same problem.  Reloading causes all of the control rods to lower.
![2016-05-18_23 51 22](https://cloud.githubusercontent.com/assets/8956281/15382840/7c33a048-1d53-11e6-89e7-adf23d77f824.png)
![2016-05-18_23 51 39](https://cloud.githubusercontent.com/assets/8956281/15382841/7c35fa00-1d53-11e6-92b7-0940f7406e1f.png)
![2016-05-18_23 51 45](https://cloud.githubusercontent.com/assets/8956281/15382843/7c383464-1d53-11e6-8659-4cf25e76ca07.png)
![2016-05-18_23 51 56](https://cloud.githubusercontent.com/assets/8956281/15382842/7c3817c2-1d53-11e6-98c1-f8ed43ccc94e.png)

I can only think that the CPU is not getting power on reloading thus it initiated scram.

**Comment by ReikaKalseki** [comment] 2016-05-19 06:01
I tested the exact same setup, minus the shafts....wait - that may be the issue. RC shaft power transfer is not instantaneous. Does the problem go away if the CPU is direct-driven from the bevel gear?

**Comment by Fatmice** [comment] 2016-05-19 16:32
No Change.  It still scrams.
![2016-05-19_11 25 01](https://cloud.githubusercontent.com/assets/8956281/15401272/602969d0-1db4-11e6-871d-c23288cd494d.png)
![2016-05-19_11 25 05](https://cloud.githubusercontent.com/assets/8956281/15401274/602c6798-1db4-11e6-8402-14a793d65449.png)
![2016-05-19_11 25 21](https://cloud.githubusercontent.com/assets/8956281/15401273/602b7a54-1db4-11e6-8262-319ed21d2c1a.png)

Not even with motors.
![2016-05-19_11 32 02](https://cloud.githubusercontent.com/assets/8956281/15401472/52bc905a-1db5-11e6-988f-ead1ec57f727.png)
![2016-05-19_11 32 21](https://cloud.githubusercontent.com/assets/8956281/15401473/52bf3e0e-1db5-11e6-9203-fdc6234fe584.png)

**Comment by ReikaKalseki** [comment] 2016-05-19 18:26
I am out of ideas again....

**Comment by Fatmice** [comment] 2016-05-19 22:24
It used to work quite well in the past.  Did you make changes upstream that causes this downstream behavior?

Can you tell when world is going down or coming up?  If you can, write to file the state of the CPU when world is going down and then when world is going up and there is power and file exist you read from file to restore CPU state.

**Comment by ReikaKalseki** [comment] 2016-05-20 02:31
By the time the CPU ticks, the world is already up, and it has stopped ticking before the world goes down.

And no, I have not changed power code or CPUs since 1.6.4.

**Comment by Fatmice** [comment] 2016-05-20 04:15
Hm well either way, you will have to write to file the CPU's configuration before world goes down and read it back in after world comes up when it has power.  Maybe the solution is make it like a chunk loader that doesn't load chunk.  I know chunk loaders keep their settings in some files to serialize their states for this sort of thing.

**Comment by ReikaKalseki** [comment] 2016-05-20 05:37
No, that is not how any of that works.

**Comment by Fatmice** [comment] 2016-05-20 06:36
Well, then how else do you save the state of the machine when world not active?

**Comment by ReikaKalseki** [comment] 2016-05-20 07:08
NBT. But that is superseded by when it ticks.

**Comment by Builderb0y** [comment] 2016-05-20 15:00
If the issue is that the CPU gets ticked before the engine that powers it, then perhaps it can be solved with a one or two tick countdown to delay the retraction of the rods? Assuming that the countdown is A: set every tick it's receiving power, and B: written to NBT, this would guarantee that the engine powering it would tick at least once before the countdown expires.

**Comment by ReikaKalseki** [comment] 2016-05-20 19:19
The thing is, it may take multiple ticks, and that number may not be constant; I actually do not know internally how fast RC power transfer really is, but I suspect in the worst case that it could be 1 tick for every block of power transmission.

Note that tiles tick in an essentially random order.

**Comment by Fatmice** [comment] 2016-05-21 00:39
How about allow CPU to store 20 ticks worth of energy.  Write that to NBT and deplete this first if CPU is not powered and temperature is not at or above critical.

**Comment by Builderb0y** [comment] 2016-05-21 01:20
Tile entities tick in the same order they were created, which is the same as the order they were placed by the player. This persists between saves as well, though it also depends on the order chunks are loaded. If you placed block A, then block B (in the same chunk), A is guaranteed to tick before B. If you started placing shafts at the engine and continued placing them until they get to the CPU, then shaft power will transmit instantly (unless it crosses a chunk boundary, anyway). If you started at the CPU however and worked backwards towards the engine, then yeah, it would be one tick per block.

Also, a 20 tick cool down would be very noticeable if you're trying to drop all the control rods by cutting the power, which is a reasonable way to shut down a reactor if you don't want it to get hot enough to trigger the SCRAM behavior.

**Comment by TomeWyrm** [comment] 2016-05-21 04:21
Huh, so that's (at least one reason) why chunk-border crossing builds involving multiblocks/networks are prone to errors. I love it when I learn new stuff about MC from you guys!

**Comment by Fatmice** [comment] 2016-05-21 05:26
> Also, a 20 tick cool down would be very noticeable if you're trying to drop all the control rods by cutting the power, which is a reasonable way to shut down a reactor if you don't want it to get hot enough to trigger the SCRAM behavior.

Why would it matter if it was going to scram anyway?  My suggestion is to only draw upon this NBT reserve if temperature is not near critical, define that however you like.  This would solve the ticking order problem.

**Comment by Builderb0y** [comment] 2016-05-21 15:02
> Why would it matter if it was going to scram anyway? My suggestion is to only draw upon this NBT reserve if temperature is not near critical, define that however you like. This would solve the ticking order problem.

The point I was trying to make is that it wouldn't look particularly realistic if you cut the power and the rods stayed up. If they retract a tick or two later, that's an almost un-noticeable delay; but more time than that, and it starts to look… odd, to say the least.

**Comment by Fatmice** [comment] 2016-05-22 12:08
Sure, whatever time scale is fine with Reika.  I merely suggested a solution to the problem.  The implementation of it is up to him, of course.

**Comment by ReikaKalseki** [comment] 2016-05-22 17:34
This is difficult to implement and I suspect that any interval long enough to work essentially always will also be noticeable.

**Comment by TomeWyrm** [comment] 2016-05-22 17:51
Fatmice, try placing the power source, then whatever transfer method you're using and THEN the CPU. If that fixes the problem, then we've got a known issue with an easy enough work around (break/replace your power lines from the engine to the CPU (IN ORDER) and then the cpu itself). Because if you don't "instant" transmit shaft power by placing the tile entities in correct order, I could easily have power coming in 30+ ticks after it's generated.

Is there an automatic way to retract the control rods that could check the temperature so it doesn't do that on an actual SCRAM?

**Comment by Fatmice** [comment] 2016-05-23 10:54
I suspect it should work if the placement order is the reverse.  I'll test later today.  Regarding scram, Reika wanted a realistic scram, i.e. there is no temperature override.  If scram is triggered for whatever reason, it will withdrawal all of the control rods as in real-life.  There is no override protocol because an overreaction is considered safer than insufficient reaction in the nuclear industry, whose overriding principle is as safe as possible.

**Comment by Fatmice** [comment] 2016-05-24 21:31
Well, I tried placing things in reverse, i.e. creative industrial coil, then bevel gear, then the cpu and its associated control rods.  Same behavior as before.  Rods all drop when world is reloaded.

**Comment by ReikaKalseki** [comment] 2016-05-25 06:29
$#%&....
