### ISSUE TITLE
plasma injector multiblock not forming

### ISSUE THREAD

**Issue by squeakers0704** [ReikaKalseki/Reika_Mods_Issues#2980] opened 2022-01-31 22:32 UTC

**Comment by LKD-PIX** [comment] 2022-02-01 00:37
The front middle block inside the 3x3 area has an Orientation, try placing it so it face either right or left into the ring

**Comment by MalTeeez** [comment] 2022-02-01 02:28
Duplicate of #2956 , wait for the new release

**Closed as completed** 2022-05-14 19:53 UTC
Labels: Duplicate
