### ISSUE TITLE
High Pressure Turbine not working in latest update.

### ISSUE THREAD

**Issue by madsamjp** [ReikaKalseki/Reika_Mods_Issues#2432] opened 2020-04-16 18:13 UTC
HP turbine connected to fission reactor. Supplied with lube and plenty of steam (5000 m^3). Wont spin up. Worked fine in previous version.

**Comment by madsamjp** [comment] 2020-04-16 19:44
Tested in creative world with new reactor setup (fission) using both water and ammonia. Confirmed not working.

**Comment by Retovath** [comment] 2020-04-16 20:29
Duplicate of #2372

**Comment by madsamjp** [comment] 2020-04-16 20:32
> 
> 
> Duplicate of #2372

How many heat exchanger did you use to get it running?

**Comment by madsamjp** [comment] 2020-04-16 20:43
> 
> 
> Duplicate of #2372

I cant seem to recreate your setup. Using the molten salt/ heat exchanger /boiler doesnt seem to activate turbine.

**Comment by Retovath** [comment] 2020-04-16 21:07
https://i.imgur.com/8DFyKlX.png
The test setup using molten salts as the heat source, and a uranium based fission reactor in the background.
https://i.imgur.com/6yiCQte.jpg
The functional setup running on a thorium molten salt reactor reactor (Ignore the Transvector interface).
https://i.imgur.com/x5L3ltg.jpg
The actual molten salt reactor running 2x HPT.

**Comment by madsamjp** [comment] 2020-04-16 21:17
> 
> 
> https://i.imgur.com/8DFyKlX.png
> The test setup using molten salts as the heat source, and a uranium based fission reactor in the background.
> https://i.imgur.com/6yiCQte.jpg
> The functional setup running on a thorium molten salt reactor reactor (Ignore the Transvector interface).
> https://i.imgur.com/x5L3ltg.jpg
> The actual molten salt reactor running 2x HPT.

So you just attached 1 molten sodium heat exchanger to the HP turbine, with the fission reactor supplying the majority of the steam?

If you disconnect the sodium heat exchanger, does the HP turbine stop running?

**Comment by Retovath** [comment] 2020-04-16 21:58
One heat exchanger and 8 boilers running off of Hot FLiBe can run one HiP turbine. The steam for the HiP turbine was provided only from the salt. I tested powering the HiP turbine with basic fission steam using the reactor in the background of the first photo, and did not test mixed steam.

**Comment by Goliathos** [comment] 2020-04-17 11:35
Can also confirm.

12-Core Fission Uranium Reactor powered regular turbines just fine. There is 1,700 m^3 of steam in the lines but a fully lubed and connected HP Turbine will not spin.

Debug mode is the only way I've found to make it spin. I haven't tried using any other reactorcraft blocks.

I'm on the latest version of all mods.

**Comment by Thorinair** [comment] 2020-04-20 11:34
Oh god, I had hoped that I will just need to wait for a fix for the Neutron Absorbers, but this is already two layers of the Fusion Reactor that will not work once I finish my build. I might as well completely quit playing on my base for half a year until these issues get fixed...

**Closed as completed** 2020-04-21 22:54 UTC
Labels: Duplicate, Fixed
