### ISSUE TITLE
Extractor causes client crash

### ISSUE THREAD

**Issue by Lelob123** [ReikaKalseki/Reika_Mods_Issues#94] opened 2015-06-11 01:35 UTC
http://pastebin.com/YqCVk6qQ

This is on a custom pack that is private too with the following mods: (There are 5 pics, I couldn't think of a better way to show it without typing them out individually)

http://imgur.com/evPy5oG,bZwKDqV,EHbpByO,mnZ0SXJ,lFa5tgF

Basically you right click on the extractor, the UI opens up and you cannot interact with it, and within seconds the entire thing crashes your client to desktop. It was hooked up to 64.536kw@512rad/s coming from a hydrokinetic engine.

edit: http://pastebin.com/dCCYYDHG <-modlist

**Comment by 1Matthias** [comment] 2015-06-11 01:38
I know from what he was saying in IRC that it was caused when he right clicked on an extractor.

**Comment by ReikaKalseki** [comment] 2015-06-11 21:06
This is a mod interaction - something is trying to access nonexistent inventory slots. Remove all other mods and try again.

I have closed this issue because it is not a bug on my end, though you can still investigate to find the offending mod.

**Closed as completed** 2015-06-11 21:06 UTC
Labels: Mod Interaction, RotaryCraft, Crash, Other Mod's End
