### ISSUE TITLE
CC crash while server loads

### ISSUE THREAD

**Issue by steelshot** [ReikaKalseki/Reika_Mods_Issues#804] opened 2016-05-11 03:43 UTC
CC crashes while the server is loading, from the crash reports its something with ComputerCraft and ASM

Crash Report: http://pastebin.com/wTGRt2ig

**Comment by ReikaKalseki** [comment] 2016-05-11 03:53
Use v13b. And duplicate of #802.

**Closed as completed by ReikaKalseki** 2016-05-11 03:53 UTC
Labels: Duplicate, Old Version, ChromatiCraft, Crash

**Comment by steelshot** [comment] 2016-05-11 04:03
I've redownloaded all of your mods from curseforge just a min ago, still a crash
http://pastebin.com/pq1znWmh

**Comment by ReikaKalseki** [comment] 2016-05-11 04:28
You are still using DragonAPI v13a. And your jarfiles all have the version info stripped from them.

**Comment by steelshot** [comment] 2016-05-11 04:29
Yeah i rename them, so they are just left by their names, its easier for me to update, redownloading again from curseforge

**Comment by steelshot** [comment] 2016-05-11 04:38
Yet again same crash, all files are fresh, none of em renamed.
http://pastebin.com/RtPV4tPq
Mcmod.info
[
{
  "modid": "",
  "name": "",
  "description": "",
  "version": "V13b",
  "mcversion": "1.7.10",
  "url": "",
  "updateUrl": "",
  "authorList": ["Reika"],
  "credits": "Reika",
  "logoFile": "",
  "screenshots": [],
  "dependencies": []
}
]
version_chromaticraft.properties
Major=13
Minor=b

version_dragonapi.properties
Major=13
Minor=b

**Comment by steelshot** [comment] 2016-05-11 04:56
The client loads fine, but the server just does not. Im out of ideas, downloaded via my phone, used Wget on server, used 2 different browsers on my main pc. ive even tried 2 different FTP clients to transfer the files over to the server

**Comment by ReikaKalseki** [comment] 2016-05-11 06:40
Our server is running 13b fine.

**Comment by steelshot** [comment] 2016-05-11 11:39
Managed to get around this issue by removing Engineer's Toolbox as it was showing that it is providing ComputerCraft API in the crash reports, most likely an extremely old api, should be put somewhere as an Incompatible Mod, now iam only getting the EnderIO crash that you've reported on theirs github.

**Comment by ReikaKalseki** [comment] 2016-05-11 19:15
That could trigger it, yes.

**Comment by eqdanteon** [comment] 2016-05-11 23:02
I apologize if this is not the correct place for this however I am experiencing this issue as well and wanted to confirm that my current options are to remain on V13a until enderio issues a fix or to remove enderio? Please let me know if there are any options I have missed.

Thanks

**Comment by steelshot** [comment] 2016-05-11 23:27
So your crashing because of you have EnderIO and latest v13b versions right?
Removing EnderIO fixes the crash
As i remember i had no issues using v13a
So depends on you, which will impact you most

**Comment by eqdanteon** [comment] 2016-05-11 23:30
Yes.  I did not have any issues with 13a as well I just wanted to make sure that I had no other options before having to decide between the two.

Thanks

**Comment by steelshot** [comment] 2016-05-11 23:32
Well myself, ive shut down the server and waiting for the EnderIO update, hopefully in the coming hours, i am using too many enderio items to just remove it

I'd say any update on this would happen here
https://goo.gl/Ggm1aZ

**Comment by eqdanteon** [comment] 2016-05-11 23:35
I'm in the same boat.  I've subscribed that issue as well.  I appreciate the quick response.  Thanks for your time.
