### ISSUE TITLE
[Chromaticraft (V18a)] Teleportation Pump GUI crashes client when trying to render fluid

### ISSUE THREAD

**Issue by ChaosAlpha** [ReikaKalseki/Reika_Mods_Issues#1549] opened 2017-08-12 22:25 UTC
Crash report:
[crash-2017-08-12_23.50.50-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/1220100/crash-2017-08-12_23.50.50-client.txt)

We are playing on the Revolution3 modpack (with some modifications, particularly, all of your mods patched to their latest version, to fix the Luminous Cliffs biome not spawning due to ClimateControl+RTG): when using the Teleportation Pump from Chromaticraft we end up crashing our clients very often. This happens only when opening or interacting in the GUI, the block and TileEntity seem to otherwise behave correctly.
More precisely, here's how I have reproduced the crash multiple times: the pump is placed down in a desert to collect BC:Energy Oil. The ender particles pop up (which I suppose indicates that the pump is scanning the area for liquid blocks) and the pump is unavailable to be interacted with during this. Once it's ready, we open the GUI: most of the times, this results in a direct CTD, without even a frame of the GUI rendering. Sometimes, after moving the pump to another close-by location, the GUI actually opens up, but, if the down arrow in the UI is used to select another fluid (BC:Energy Oil in this case, even though I can't know if this is the fluid that is causing the issue, since the GUI only shows you the current selected fluid) the crash can happen at that time too.
Note that this is not crashing 100% of the time: the pump was used to successfully collect BC:Energy Oil, after many crashes. However, it appears that if the pump is left in the location it last crashed, it seems to be guaranteed to crash again after relogging. The opposite is not true: the time the pump was successfully used and configured, it was interacted with again after leaving it there for a few days, but caused a CTD upon trying to open the GUI after it had stopped collecting fluids (very probably due to getting its chunk unloaded, since the storage crystal still had energy in it, and there definitely was still BC:Energy Oil in proximity of the pump).

I think there is either a semi-random rendering issue with modded (or not) fluid icons, or one fluid that is consistently crashing upon trying to render, though I would have difficulty determining which with exactitude. Perhaps rendering nothing or a "No texture" icon if the error can be caught in the code would work as a fallback, if there's no other way to determine if an icon will render correctly deterministically.

**Comment by DaFuqs** [comment] 2017-08-13 08:48
You beat me to it, ChaosAlpha. I reached the progression for the Teleportation Pump two days ago and can reproduce your problem. (Installed: DragonAPI, Chromaticraft, Rotarycraft, Buildcraft)

Rendering of some fluids in general - even outside of the peleportation pump - is a thing that leeds to crashes. Another example are the usage recipes of the deco tank. When cycling through the filling recipes and reaching an unrenderable fluid the client crashes, too.

##########

How should I report serious dupe issues btw? I would not be comfortable with writing it here where everyone can read and abuse it.

**Comment by ReikaKalseki** [comment] 2017-08-18 20:51
Fixed by way of passing it through the same verification-and-bedrock-texture-as-fallback as the RC reservoir uses. I know some variants of BC fuel (I think with an Artifice interaction) have this issue.

**Closed as completed by ReikaKalseki** 2017-08-18 20:51 UTC
Labels: Fixed, ChromatiCraft, Crash, Other Mod's End, Stupid Code
