### ISSUE TITLE
Server shutting down after some time | Chromaticraft

### ISSUE THREAD

**Issue by blackdevil8975** [ReikaKalseki/Reika_Mods_Issues#624] opened 2016-02-15 14:09 UTC
First it only happened when I hit a leaf of a tree, the server instantly closed. After a restart all worked well again and now the Server shuts down after ~5mins. In the crash log it says something about Chromaticraft, so I thought I have to post it here.
[crash-2016-02-15_14.27.16-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/130866/crash-2016-02-15_14.27.16-server.txt)

cant upload the fml latest here, because its about 5MB big.
fml latest:First it only happened when I hit a leaf of a tree, the server instantly closed. After a restart all worked well again and now the Server shuts down after ~5mins. In the crash log it says something about Chromaticraft, so I thought I have to post it here.
[crash-2016-02-15_14.27.16-server.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/130866/crash-2016-02-15_14.27.16-server.txt)

cant upload the fml latest here, because its about 5MB big.
fml latest: http://www.mediafire.com/download/s5ooxqw9lcdlgwq/fml-server-3.log

**Comment by ljfa-ag** [comment] 2016-02-15 15:38
Duplicate of #611, #557, #535, #528, #526, #527, #520

**Closed as completed by ljfa-ag** 2016-02-15 15:38 UTC
Labels: Duplicate
