### ISSUE TITLE
Waila not working with DragonApi and resourcefulcrops

### ISSUE THREAD

**Issue by Saereth** [ReikaKalseki/Reika_Mods_Issues#272] opened 2015-09-18 00:11 UTC
As of the latest update to DragonAPI the Waila display for Resourcefulcrops has stopped working. Waila shows aboslutely nothing, not even a blank box. This issue is not present without dragonapi.

Resourcefulcrops github: https://github.com/TehNut/ResourcefulCrops

forge 1448 multiplayer, let me know if you need anymore info

**Comment by FoxySophie** [comment] 2015-09-18 09:00
Can confirm that this is also the case for AgriCraft Crops.

**Comment by ReikaKalseki** [comment] 2015-09-18 18:13
This is possibly fixed in v9.

**Comment by TehNut** [comment] 2015-09-30 02:50
Apparently this is still an issue in v9.

**Comment by Saereth** [comment] 2015-09-30 02:55
Can confirm, created a new instance with dragon api v9, Waila and resourcefulcrops, no waila display at all.

**Comment by ReikaKalseki** [comment] 2015-09-30 05:46
> _<

I am out of ideas.

**Comment by ReikaKalseki** [comment] 2016-02-04 16:23
I am currently playing what will eventually become v11, and have no issues with any crop type. So the issue is either fixed (somewhat spontaneously) or is simply nonexistent or dependent upon other factors.

**Closed as completed by ReikaKalseki** 2016-02-04 16:23 UTC
Labels: Bug, Fixed, Mod Interaction, Can't Reproduce, DragonAPI

**Comment by Saereth** [comment] 2016-02-04 17:45
yeah I did notice if I plant resourceful crops agricraft style the names show up just fine, so I'll see when v11 rolls around, thanks!
