### ISSUE TITLE
Chromaticraft Aspect Jar Issues 

### ISSUE THREAD

**Issue by Reignofmagic** [ReikaKalseki/Reika_Mods_Issues#282] opened 2015-09-26 02:33 UTC
I have noticed a few issues with the aspect jar. I'm making this as a list and potential fix/contact thread for all parties involved.

List of problems I have encountered:
1: Aspect jar is not usable for the Infusion Altar (even tho it implements IAspectSource)
2: Alchemy Golems will only deposit one type of essential into the jar (Always the first type that makes it to the jar) 
3: Aspect jar will not accept Essentia tubes for piping purposes. I tested this with a crucible and ambelic set up to see if I could add Essentia this way. (Implements IEssentiaTransport so that should work)
4: Aspect jar "eats" phials when you put essentia into them (no idea on this one)
5: Aspect jar will not give essentia back when using phials or warded jars (no idea as well, unless you have to click a certain portion of the jar)

Untested: Any interaction with Thaumic Energistics/Horizion machinery, or other Thaumcraft addons.

Potential Causes: 

I'm bad and did something wrong. 
Wrong implements in the aspect jar/code, or something else wrong with the code. I looked through it, everything seems reasonable without an easy reference to the source files of Thaumcraft. 
Thaumcraft is blacklisting these features.

Potential Fixes:

Make the aspect jar act like a essentia reservoir(eldritch research) (IE it is a buffer tank with large capacity, and multiple essentia types (but less than what the aspect jar has), but no use for Infusion crafting.) 
Make the Aspect jar a single essentia type tank (IE warded jar) but with large capacity (the 500 or 5k that you have it set at currently could work for testing purposes)  

Links to various places that could provide aid:

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292130-thaumcraft-4-2-3-5-updated-2015-2-17
https://github.com/Azanor/thaumcraft-api/issues

People I'm pinging to see if they can help:
@ReikaKalseki 
@Azanor
@Hillburn  (Simply because he seems to help with a lot of problems, please ignore this if this is out of line & sorry)

Links to the related files within Chromaticraft from what I could find:

https://github.com/ReikaKalseki/ChromatiCraft/blob/88f103d1dbb82c4429d018f33a85b02ad8306845/ModInterface/TileEntityAspectJar.java
https://github.com/ReikaKalseki/ChromatiCraft/blob/23151a8294d844333828eebfcd54d1cf7a188175/Base/BlockChromaTile.java
https://github.com/ReikaKalseki/ChromatiCraft/blob/99205199310589267b9aa863ae98901c20df578c/Render/TESR/AspectJarRenderer.java

Links to Related files within DragonAPI from what I could find:

https://github.com/ReikaKalseki/DragonAPI/blob/58a92532e582342c44489068e4823527a4409762/Instantiable/ModInteract/AspectTank.java
https://github.com/ReikaKalseki/DragonAPI/blob/58a92532e582342c44489068e4823527a4409762/Instantiable/ModInteract/CompoundAspectTank.java
https://github.com/ReikaKalseki/DragonAPI/blob/84cc4fd73e83027c9b5da01486b8d831baaa7803/ModInteract/ItemHandlers/ThaumItemHelper.java

I'll do some more testing tomorrow when I get a chance to play some more. I'll test interaction with other thaumcraft addons and see if any of them provide a use for the jar, as it currently is useless as far as I can see unless I am doing something wrong with the essentia tubes. I shall also provide SS of my setups in-case this is an error on my part.

**Comment by ReikaKalseki** [comment] 2015-09-26 05:57
Pinging @hilburn

[This](https://github.com/ReikaKalseki/ChromatiCraft/blob/23151a8294d844333828eebfcd54d1cf7a188175/Base/BlockChromaTile.java#L265) is the cause of the phial consumption.

**Comment by hilburn** [comment] 2015-09-26 07:43
Fun

**Comment by ReikaKalseki** [comment] 2015-09-26 20:35
:P

Any ideas?

**Comment by hilburn** [comment] 2015-09-27 02:18
Ummm... don't do that thing that doesn't work?

I'll have a look tomorrow if I get a chance

**Comment by Reignofmagic** [comment] 2015-09-29 00:23
Well an update on my end. I tested thaumic energistics with the aspect jar (both with import, export, and storage bus) no dice there. So it looks like the aspect jar is just sad at the moment. Hopefully @Azanor can help with this one.

**Comment by ReikaKalseki** [comment] 2016-03-21 22:54
This was fixed in v11.

**Closed as completed by ReikaKalseki** 2016-03-21 22:54 UTC
Labels: Bug, Fixed, Mod Interaction, Needs Info, ChromatiCraft, @&#%?!
