### ISSUE TITLE
[RotaryCraft] ID is already registered (Entity-ID)

### ISSUE THREAD

**Issue by walkerjonny** [ReikaKalseki/Reika_Mods_Issues#76] opened 2015-05-25 14:15 UTC
Hi, 

I'm getting an error with different mods that I had already in my list or that I try to add. It is always the same error caused by this RotaryCraft exception. Some of the mods (like the weaponmod) aren't even tech mods.
So I'm posting this error here. Maybe you have an idea where this might come from.
http://pastebin.com/X7EbaBpa

**Comment by Duckfan77** [comment] 2015-05-25 15:34
At a first look it seems that the mods are attempting to register onto a entityID taken by RotaryCraft, could you remove mods and readd until you can see which mods cause the issue?

**Comment by walkerjonny** [comment] 2015-05-25 16:32
Interesting...
For me it looks like the exception is caused by RotaryCraft as it tries to add an Entity with the ID 31 which is already registered by another mod. See:

433.java.lang.IllegalArgumentException: ID is already registered: 31
434.        at net.minecraft.entity.EntityList.func_75618_a(EntityList.java:93) ~[sg.class:?]
435.        at cpw.mods.fml.common.registry.EntityRegistry.registerGlobalEntityID(EntityRegistry.java:199) ~[EntityRegistry.class:?]
436.        at Reika.RotaryCraft.RotaryRegistration.addEntities(RotaryRegistration.java:90) ~[RotaryRegistration.class:?]
437.        at Reika.RotaryCraft.RotaryCraft.load(RotaryCraft.java:308) ~[RotaryCraft.class:?]

Also the first exception is:

1.[15:49:29] [Client thread/INFO]: Could not load Extracts API!
2.[15:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoSuchFieldException: modOres
3.[15:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at java.lang.Class.getDeclaredField(Unknown Source)
4.[15:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at Reika.RotaryCraft.API.ExtractAPI.<clinit>(ExtractAPI.java:98)
5.[15:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at ganymedes01.aobd.recipes.modules.RotaryCraft.initOre(RotaryCraft.java:28)
6.[15:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at ganymedes01.aobd.recipes.RecipesModule.init(RecipesModule.java:37)
7.[15:49:29] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]:   at ganymedes01.aobd.recipes.ModulesHandler.init(ModulesHandler.java:31)

This one also points to RotaryCraft and not to another mod in the first place as I understand it.
Are you really sure that another mod causes the issue?
I would assume that in that case the other mod would cause the exception and not RotaryCraft.

I have also explained that this exception happens with different mods.
The Weaponmod (from Balkon) is just an example. It happens also when I try to add the NuclearCraft mod (like in this crash log) or the SPC (Single Player Commands, yes there exist one version for 1.7.10) mod.
Therefore I'd like to suggest to look into RotaryCraft and not into the other mods in the first place.

For example: My question would be: Why does RotaryCraft not try to register another free Entity ID if ID 31 is already in use?

**Comment by Duckfan77** [comment] 2015-05-25 18:04
That's what it looks like, but as I don't know why it wouldn't just pick another ID, determining which mods are conflicting would be useful to know if someone else has this issue down the line.

**Comment by ljfa-ag** [comment] 2015-05-25 18:07
Duplicate of #55.

**Comment by walkerjonny** [comment] 2015-05-26 01:00
Sorry, but in that case a complete different mod causes that issue. So it is not a duplicate issue even if it looks like.
I don't play with IC Combo Armors anymore as I told you in the other thread.
Therefore this issue persists.
Also it is only RotaryCraft that throws this exception. The question remains: Why RotaryCraft and not the other mod(s)?
In this case I tried to add NuclearCraft (see http://www.curse.com/mc-mods/minecraft/226254-nuclearcraft-mod).
The reason for this should be discovered and then finally fixed.
Closing this thread doesn't help anyone.

**Comment by walkerjonny** [comment] 2015-05-26 01:26
I have posted this on the thread of NuclearCraft on the Minecraft Forum.
Maybe you can work this out together.
Here is the link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2187231-nuclearcraft-mod-rf-reactors-nuclear-power?page=5

**Comment by kolatra** [comment] 2015-05-26 06:36
He did reply, take a look at your configs.

**Comment by ReikaKalseki** [comment] 2015-05-26 06:47
Check your Forge and mod versions for mismatches between client and server.

**Comment by walkerjonny** [comment] 2015-05-26 09:24
I'm playing only Single Player and am not using a local LAN Server or any kind of server installation for Minecraft, Forge or any other mod. Therefore there should not be any differencies or am I getting something wrong here?

Also - how can I change this issue back to "open"?

Finally - sorry, I didn't want to make anyone angry. English isn't my mother language. Maybe I have not used the right words in my other issue post to explain my own feelings.

**Comment by coolsquid** [comment] 2015-05-26 09:26
> Also - how can I change this issue back to "open"?

There you go.

**Comment by walkerjonny** [comment] 2015-05-26 09:33
Thank you very much!
I'll do any tests you may ask to help you guys to get that issue fixed.
FYI:
I tried to launch Minecraft just with NuclearCraft and removed RotaryCraft and depended mods.
Minecraft did start properly and I was able to launch a new world.
So it must be definitely a mod interaction issue between both RotaryCraft and NuclearCraft.

**Comment by walkerjonny** [comment] 2015-05-26 10:19
Kolatra, did you mean me with "check your configs"?
In case of yes, do you want me to check the NuclearCraft configs for an entry that points to an Entity?

**Comment by ReikaKalseki** [comment] 2015-05-26 16:34
Did you read the forum thread you posted to?
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2187231-nuclearcraft-mod-rf-reactors-nuclear-power?comment=101

**Comment by walkerjonny** [comment] 2015-05-26 17:27
I assume the line 432 of the crash log was meant:

432.[15:49:33] [Client thread/ERROR]: Caught exception from RotaryCraft
433.java.lang.IllegalArgumentException: ID is already registered: 31

I'll have a check at the NuclearCraft configs and let you know the results.
Maybe there is a setting that could fix that issue.

**Comment by walkerjonny** [comment] 2015-05-27 23:16
Sorry for the late response. I had two very long working days...

I disabled all entities within the NuclearCraft config but without luck.
I'll post this on the NuclearCraft thread, too.

**Comment by ReikaKalseki** [comment] 2015-05-30 16:59
This is hopefully fixed in v7.

**Closed as completed by ReikaKalseki** 2015-05-30 16:59 UTC
Labels: Fixed, Mod Interaction, RotaryCraft
