### ISSUE TITLE
Chromaticraft - Forestry Incompatibility (Caused by Dragon API)

### ISSUE THREAD

**Issue by CrazyPyroEagle** [ReikaKalseki/Reika_Mods_Issues#394] opened 2015-11-15 15:28 UTC
I attempted to run Minecraft 1.7.10 using the following mods.

```
UCHIJ   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
UCHIJ   FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
UCHIJ   Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
UCHIJ   <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
UCHIJ   BuildCraft|Core{7.1.13} [BuildCraft] (buildcraft-7.1.13.jar) 
UCHIJ   BuildCraft|Builders{7.1.13} [BC Builders] (buildcraft-7.1.13.jar) 
UCHIJ   BuildCraft|Transport{7.1.13} [BC Transport] (buildcraft-7.1.13.jar) 
UCHIJ   BuildCraft|Energy{7.1.13} [BC Energy] (buildcraft-7.1.13.jar) 
UCHIJ   BuildCraft|Silicon{7.1.13} [BC Silicon] (buildcraft-7.1.13.jar) 
UCHIJ   BuildCraft|Robotics{7.1.13} [BC Robotics] (buildcraft-7.1.13.jar) 
UCHIJ   BuildCraft|Factory{7.1.13} [BC Factory] (buildcraft-7.1.13.jar) 
UCHIJ   Forestry{4.1.1.46} [Forestry for Minecraft] (forestry_1.7.10-4.1.1.46.jar) 
UCHIJ   DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9b.jar) 
UCHIE   ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V9b.jar)
```

They were all downloaded from the original source (no stupid alternate website which tells you "this is for 1.8" and gives you a 1.7 JAR).

I thought this might be due to the use of an incorrect Forestry version (using current latest), however I could not find the version of Forestry it is compatible with on your website.

Here's the crash report caused by the error.
[crash-2015-11-15_16.19.11-client.txt](https://github.com/ReikaKalseki/Reika_Mods_Issues/files/34898/crash-2015-11-15_16.19.11-client.txt)

In the meantime, is there a version of Forestry which works with DragonAPI 9b?

**Comment by lossycrypt** [comment] 2015-11-15 17:13
Forestry 4 is not currently compatible. Use Forestry 3.
Also use the [search function](https://github.com/ReikaKalseki/Reika_Mods_Issues/search?q=forestry&type=Issues&utf8=%E2%9C%93). This has been reported numerous times.

**Comment by ljfa-ag** [comment] 2015-11-15 19:52
Duplicate of #229.
Yeah, unfortunately it is unknown right now when Forestry 4 compatibility can be expected.

**Closed as completed by ljfa-ag** 2015-11-15 19:52 UTC
Labels: Duplicate
