### ISSUE TITLE
Dragon Api crash

### ISSUE THREAD

**Issue by heyheyhey123243** [ReikaKalseki/Reika_Mods_Issues#1758] opened 2018-01-21 10:06 UTC
https://paste.ee/p/HvVs1

**Comment by ReikaKalseki** [comment] 2018-01-22 04:38
I was expecting this to be a duplicate of previous similar errors, but this actually looks new. What other mods with ASM do you have installed (eg FastCraft, Thaumic Infusion, AE, CoFH...)?

**Comment by arceus179** [comment] 2018-01-22 04:50
From what it looks like, he's added dragonAPI to direwolf 20.

**Comment by ReikaKalseki** [comment] 2018-01-22 08:24
Try removing mods.

**Comment by heyheyhey123243** [comment] 2018-01-22 09:43
I'm using a modified version of Direwofl20 1.7.10. Just added a few mods of my own. I"ve tried removing them one by one but it takes like 10 mins to load up each time. Was just wondering if you could identify anything within the logs since I'm not experienced with this. 

Here's the list.
https://imgur.com/a/bV0zj 

The log above was loaded without optifine.

**Comment by Duckfan77** [comment] 2018-01-22 15:01
You don't need to remove the mods one by one, you should use a binary split search. Basically, take out half the mods, ensuring that you keep dependency links in the same group, and check if you get the crash. If not, then the issue is in the other group, and you check with that group. Repeat until you have the minimal reproducible setup. Obviously, don't remove DApi as it is definitely part of the crash.

**Comment by heyheyhey123243** [comment] 2018-01-23 06:26
Solved the issue, my fastcraft was outdated which was causing the crash.

**Comment by ReikaKalseki** [comment] 2018-01-24 20:35
So it *was* one of the old errors. #919 #902 #906 #914 #916 #921 #924 #963 #1029 #1078 #1222

**Closed as completed by ReikaKalseki** 2018-01-24 20:35 UTC
Labels: Duplicate
