### ISSUE TITLE
RotaryCraft hand book crash.

### ISSUE THREAD

**Issue by StrayanDropbear** [ReikaKalseki/Reika_Mods_Issues#587] opened 2016-01-18 06:41 UTC
When I open the handbook the client crashes. I'm using a modpack and tried disabling to find the cause but it seems like multiple mods in certain combinations is causing this.

Crashlog:
http://pastebin.com/r9wMRsDx

Also the other handbooks from your other mods works fine.

**Comment by ljfa-ag** [comment] 2016-01-18 09:35
Duplicate of #544, #540, #534, ...

**Closed as completed by ljfa-ag** 2016-01-18 09:35 UTC
Labels: Duplicate

**Comment by ReikaKalseki** [comment] 2016-01-18 12:11
#582, #581, #567, #564, #550, #544, #540, #534, #522, #515, #488
