### ISSUE TITLE
Searching for ANY recipe in NEI crashes client (1.3.5)

### ISSUE THREAD

**Issue by ForgedSnow** [ReikaKalseki/Reika_Mods_Issues#559] opened 2016-01-10 17:34 UTC
Disabling pneumaticraft solved my issue, is there a fix that doesn't require disabling mods?

**Comment by ReikaKalseki** [comment] 2016-01-10 19:37
Your lack of any crashlog makes it impossible to be sure, but this sounds like either an issue fixed in v10 or perhaps yet another duplicate of #550, #544, #540, #534, #522, #515, #488. If disabling PnC is a reliable fix, and the only one that works, it is probably the former.

**Closed as completed by ReikaKalseki** 2016-01-10 19:37 UTC
Labels: Old Version
