### ISSUE TITLE
PBR not heating up

### ISSUE THREAD

**Issue by ExtraNautilus** [ReikaKalseki/Reika_Mods_Issues#679] opened 2016-03-06 23:47 UTC
![2016-03-06_18 50 31](https://cloud.githubusercontent.com/assets/17692874/13558185/6e9a963c-e3cc-11e5-9692-fe597dc74672.png)
After a lot of trial and error, I got a 4x4 (16) core PBR working, but about 30 minutes later the reactor heat dropped from 1200C to hovering around 120C... I tried updating and restarting but to no avail. The heat exchanger still worked for a bit after the core went cold. I am sorry if I did not include enough information. The turbine is fully lubricated, the heat exchanger fully powered, and the boiler full of water. I am using the newest version.

**Comment by ExtraNautilus** [comment] 2016-03-06 23:48
Oh, forgot to add: the insulation for the top and bottoms of the cores are buildcraft pipes to get pellets in and out

**Comment by redelman** [comment] 2016-03-07 00:10
I believe this is a duplicate of #672, which is fixed for v12.

**Comment by ExtraNautilus** [comment] 2016-03-07 00:18
That seems like what I'm doing, only his never worked. Thank you for your help.

**Closed as completed** 2016-03-07 00:55 UTC
Labels: Duplicate, ReactorCraft
