### ISSUE TITLE
Crash when opening Rotarycraft Handbook

### ISSUE THREAD

**Issue by Keyarose** [ReikaKalseki/Reika_Mods_Issues#605] opened 2016-01-31 13:24 UTC
Using version 10d, the crash happens immediately after attempting to open the handbook.  I am using a very uncommon collection of mods, however there is no issue when opening the chromaticraft manual (I assume they're largely the same in implementation)

Crash log: http://pastebin.com/kR2uAU1T

**Comment by ljfa-ag** [comment] 2016-01-31 15:00
Duplicate of #589, #588, #587, #582, #581, #567, #564, #550, #544, #540, #534, #522, #515, #488

**Closed as completed by ljfa-ag** 2016-01-31 15:00 UTC
Labels: Duplicate, Stop Reporting This

**Comment by Keyarose** [comment] 2016-01-31 16:10
When I was checking to see if this issue was already reported i filtered using the rotarycraft label, it might be an idea to stick that on one of the other issues should someone else come looking to report it again. Good to know it's fixed though.

**Comment by ljfa-ag** [comment] 2016-01-31 19:40
Hm, the very first one has a "DragonAPI" tag. In any case all those crashes have the same cause ^^
It will still take a bit until the fixed version is actually released though.

**Comment by ReikaKalseki** [comment] 2016-01-31 20:57
> Hm, the very first one has a "DragonAPI" tag

Because the error was in DragonAPI.

**Comment by Keyarose** [comment] 2016-01-31 21:46
Well I'm looking forward to when I can use the manuals rather than piecing things together from the wiki and NEI.  Thanks for the great mods.

**Comment by ReikaKalseki** [comment] 2016-01-31 23:28
You can use the manual; the crash is generally fairly rare.

**Comment by Keyarose** [comment] 2016-01-31 23:38
I'm afraid it's happened 100% of the time for me for the rotarycraft manual (though I've only tried 4 times so far).  With the reactorcraft manual I can open it, but the first page I attempted to open threw the error.  I can make do without for now.  I've been looking forward to these mods its only been recently that I have been able to use them due to the block ID limit being overcome.
