### ISSUE TITLE
Two chromatiCraft crash

### ISSUE THREAD

**Issue by marco6971** [ReikaKalseki/Reika_Mods_Issues#193] opened 2015-08-09 21:58 UTC
i obtain this one trying to recharge elemental manipultor with a strange pylon, strange because the ball in top of it didn't have a colour and when i try to do a right click on a repeater which theoretically would  be connected doesn't show any number, if if it makes a difference the pylon is of zambarau

http://pastebin.com/brzRgBdz

instead I got this when i try to dig the last tier of crafting system with a draconic evolution staff set to 3x3x9

http://pastebin.com/euVD6F0y

**Comment by ljfa-ag** [comment] 2015-08-10 08:42
The second one might be on Draconic Evolution's side - issuing a BreakEvent with a null player where should at least be a fake player.

**Comment by ReikaKalseki** [comment] 2015-08-10 17:50
The first is a duplicate of the ["null player in the world list" issue](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/186) and @ljfa is correct about the second.

The former was originally marked as World Corruption. Given the second report here, I now have a suspicion as to the source. @brandon3055

**Comment by kolatra** [comment] 2015-08-10 17:56
Pinging @brandon3055.

**Closed as completed** 2015-08-11 22:03 UTC
Labels: Mod Interaction, Crash, Other Mod's End, Stupid Code
