### ISSUE TITLE
Ground Penetrating Radar crash

### ISSUE THREAD

**Issue by aeies** [ReikaKalseki/Reika_Mods_Issues#16] opened 2015-04-20 16:01 UTC
roaterycrat corrupted my world!

Description: Ticking block entity

java.lang.StackOverflowError: Ticking block entity
at Reika.DragonAPI.Instantiable.Data.BlockMap.keySet(BlockMap.java:115)
at Reika.DragonAPI.Instantiable.Data.BlockMap.keySet(BlockMap.java:115)
at Reika.DragonAPI.Instantiable.Data.BlockMap.keySet(BlockMap.java:115)
.....

**Comment by 1Matthias** [comment] 2015-04-20 16:07
Please post the full log to: pastebin.com . We also need the versions of the mods.

**Comment by aeies** [comment] 2015-04-20 16:15
The log just more of that. It happened because I placed down a ground pentrating radar. Im using version 6f

**Comment by 1Matthias** [comment] 2015-04-20 16:27
Ok, how were you powering the GPR, and what exactly happens when you try to load the world? Can you provide a list of the mods in the pack, as well as a full crashlog and stacktrace?

**Comment by aeies** [comment] 2015-04-20 16:55
I used a coil and loading the world causes a crash.
This is direwolf with rotarycraft.

**Comment by 1Matthias** [comment] 2015-04-20 17:24
Hmmm...full log posted to pastebin?

**Comment by aeies** [comment] 2015-04-20 17:27
I already gave you the crash log/

**Comment by 1Matthias** [comment] 2015-04-20 17:28
Full log, with stacktrace.

**Comment by madolinn** [comment] 2015-04-20 17:31
The last line shown when your client crashes is a file saved with the full crash log. Please put that on pastebin to expediate the process.

**Comment by aeies** [comment] 2015-04-20 17:36
http://pastebin.com/dsgn8JDb

**Comment by 1Matthias** [comment] 2015-04-20 17:39
> DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V2.jar)

Update. v2 is not supported.

**Comment by aeies** [comment] 2015-04-20 17:40
No, this is 6f!

**Comment by 1Matthias** [comment] 2015-04-20 17:41
> No, this is 6f!
Then why do all the logs say v2?

**Comment by aeies** [comment] 2015-04-20 17:41
They don't.

**Comment by zemerick** [comment] 2015-04-20 17:47
Pastebin shows older versions, showing the changes you just made.

You also forgot to change some of the others:
ExpandedRedstone{Gamma} [Expanded Redstone] (ExpandedRedstone 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
1590		
ReactorCraft{beta} [ReactorCraft] (ReactorCraft 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available

Lying will not help.

**Comment by aeies** [comment] 2015-04-20 18:08
No this is 6f maybe the bug came back! how do you know? if i cant get it fixed Im gonna make my own mod that doesnt have bugs!

**Comment by 1Matthias** [comment] 2015-04-20 18:10
> No this is 6f maybe the bug came back! how do you know? if i cant get it fixed Im gonna make my own mod that doesnt have bugs!

The logs don't lie. You are using v2. Please update, and we will see if the bug persists. https://sites.google.com/site/reikasminecraft/latest-downloads

**Comment by madolinn** [comment] 2015-04-20 18:11
http://pastebin.com/diff.php?i=0MTnKZMP

I'm unsure if he updated or he just changed the log. I'll run a test myself.

**Comment by zemerick** [comment] 2015-04-20 18:12
If you have indeed updated, please include a current log. There are a lot of important details in those logs that we need to track down the source of the problem, and we need the current information to fix it.

Please do feel free to make your own mod. It's part of what has made MC so great, is all of the different mods.

**Comment by madolinn** [comment] 2015-04-20 18:13
He edited his post to change the url. It presently is the new one and the old one is not listed on this page.

**Comment by 1Matthias** [comment] 2015-04-20 18:17
> He edited his post to change the url. It presently is the new one and the old one is not listed on this page.

Ah well. It is just too bad that I don't close tabs until a bug report is resolved. Lying and falsifying data will not change the fact that you are out of date. Until you update, and provide logs that are not doctored, you will receive no support.

**Comment by zemerick** [comment] 2015-04-20 18:17
I'm still only seeing:

http://pastebin.com/0MTnKZMP

That's the edited one. Timestamp and memory usage are unchanged, so it's not a new log.

Also, v6f RoC and Dragon API would crash at start with V2 reactorcraft, long before loading a world.

**Comment by madolinn** [comment] 2015-04-20 18:18
I posted this for you @zemerick http://pastebin.com/diff.php?i=0MTnKZMP

I'm not claiming it's a legit log, I just clicked the revisions button on pastebin.

Could not reproduce this error. I even tried throwing a ridiculous amount of power into it as well as putting it on level 1 bedrock. Both worked perfectly fine.

**Comment by coolsquid** [comment] 2015-04-20 18:19
Sure. You're using:
> [ReactorCraft] (ReactorCraft 1.7.10 V2.jar)
with
> [RotaryCraft] (RotaryCraft 1.7.10 V6F.jar)
Don't lie to us.

**Comment by madolinn** [comment] 2015-04-20 18:20
[Obligatory](http://i.imgur.com/SmfIzlx.png)

**Comment by 1Matthias** [comment] 2015-04-20 18:20
I am closing and locking this issue, as it has become clear that it is not a valid report. Update.

**Closed by 1Matthias** 2015-04-20 18:20 UTC
Labels: Old Version, RotaryCraft
