### ISSUE TITLE
[LegacyCraft] Crash with Thaumic Infusion

### ISSUE THREAD

**Issue by Shadows-of-Fire** [ReikaKalseki/Reika_Mods_Issues#895] opened 2016-05-30 01:50 UTC
Having LegacyCraft and [Thaumic Infusion](https://github.com/TheDrunkMafia/ThaumicInfusion) in the same instance seems to produce this [error](https://gist.github.com/Shadows-of-Fire/3f500e7c5d02579316c1873389a3c9b0).  It occurs before the game even opens the Minecraft 1.7.10 window, and does not cause a crash report to be created at all.

**Comment by ReikaKalseki** [comment] 2016-05-30 08:43
This is an ASM conflict, and it appears the issue is that the method has exceeded 65535 bytes. This is the colorMultiplier() method! What the _hell_ are they doing?

@TheDrunkMafia

**Comment by SeanWHall** [comment] 2016-05-30 13:49
1.7.10 of TI is as you can see not stable, I stopped support for it months ago. The ASM in that version is what causes the incompatibility with most mods, so unfortunately I'd have to strongly recommend not using TI in 1.7.10.

**Comment by ReikaKalseki** [comment] 2016-05-30 18:19
I am still curious: How did the method size become so obscenely large?

**Comment by SeanWHall** [comment] 2016-05-30 18:25
Well, TI works by adding hooks into block methods so it can add mechanics to blocks without directly interfering with the normal execution of their methods. So to find out, @Shadows-of-Fire I'd need you to upload the TI_Transformer.log which will be in the base folder of the MC instance. The 1.7.10 implementation using ASM is fairly dogy since it was when I first started looking into bytecode manipulation and I completely revised it in 1.8, so I can only imagine what the transformer is doing.

**Comment by Shadows-of-Fire** [comment] 2016-05-30 18:30
https://gist.github.com/Shadows-of-Fire/998f59879d3aa84bbc0f79825f4d4036

**Closed as completed** 2016-05-30 22:11 UTC
Labels: Mod Interaction, Crash, @&#%?!, Other Mod's End, Reflection/ASM
