### ISSUE TITLE
[V30] Satisforestry serverside startup crash

### ISSUE THREAD

**Issue by erplsf** [ReikaKalseki/Reika_Mods_Issues#2899] opened 2021-09-25 15:08 UTC
All mods updated to v30 from v29 on pre-existing map. Client boots fine, server crashes: https://pastebin.com/raw/xb5G1Xfe

**Comment by MalTeeez** [comment] 2021-09-25 18:55
Duplicate of #2898

**Closed as completed** 2021-09-26 02:27 UTC
Labels: Duplicate
