### ISSUE TITLE
Crash on start with Reika's mods (specifically Dragonapi)

### ISSUE THREAD

**Issue by talianagisan** [ReikaKalseki/Reika_Mods_Issues#998] opened 2016-06-25 09:25 UTC
So when ever i install Dragonapi (and Reactorcraft,Rotarycraft,Electricraft althought i cant see a crash report with them mentioned) my minecraft wont start up and gives me a short but confusing error i can't solve hence why im posting here. http://pastebin.com/1BtTSBE1 the error is around line 382. ive tried for days to solve this but cant and thankfully i have no lingering issues when removing the mods so it will start again but any idea's on this one as id love to use these mods.

**Comment by ljfa-ag** [comment] 2016-06-25 11:40
Have you tried removing other mods?
Possible suspects: MobiusCore, Dynamic Lights, Galacticraft, TrashSlot, ItemPhysic. Seems like one of these is causing a conflict.

**Comment by ljfa-ag** [comment] 2016-06-25 11:45
Appears to be a duplicate of #989. Which is also a duplicate but with no reference.

**Comment by talianagisan** [comment] 2016-06-25 11:55
i tried removing them and it didnt do anything.

**Comment by Builderb0y** [comment] 2016-06-25 13:18
Update fastcraft.

**Closed as completed** 2016-06-25 17:01 UTC
Labels: Duplicate, Mod Interaction, DragonAPI, Reflection/ASM
