### ISSUE TITLE
Server time out error when opening single player worlds in V25

### ISSUE THREAD

**Issue by LighttronPrime** [ReikaKalseki/Reika_Mods_Issues#2413] opened 2020-04-09 01:56 UTC
I use DragonAPI, Rotarycraft, Reactorcraft, and Void Monster in my personal modpack. Yesterday, I updated your mods to V25, and loaded several worlds without issue. Today however, opening both my survival world and superflat creative testing world resulted in a server timeout error that brought me to the multiplayer loading screen. After two hours of investigation, I discovered that the first time I loaded a world with the V25 mods, no issues occurred, but the second time, it always lead to a server time out error despite not being on a server. The only way I found of preventing this issue was reverting your mods to V24. I have a large modpack with 160+ mods, some of which were written for forge versions that are now severely outdated.. I imagine I'll have to do the grind of removing mods one by one to track down the conflict, but I wanted to see if you had any other advice/suggestions first.

**Comment by MalTeeez** [comment] 2020-04-09 16:33
Maybe a duplicate of #2397, try going into the world folder (save/yourworldsname) and delete modversions.list- try joining now.

**Comment by LighttronPrime** [comment] 2020-04-11 23:15
No, that didn't work. I forgot to mention that the same issue occurs for newly created worlds as well: they load without issue upon creation, but any attempts at reloading lead to a nonsensical server time out error.

**Closed as completed** 2020-04-21 22:55 UTC

**Comment by LighttronPrime** [comment] 2020-04-23 16:49
After a lot of testing, I discovered that using v25 mods alongside Galacticraft caused this issue. I was considering using Advanced Rocketry instead anyways, so this isn't a huge issue, thankfully. I believe that Galacticraft was written for a very outdated forge version, which is likely the root of the issue.
