### ISSUE TITLE
Reactorcraft/Rotarycraft NEI Crash and Manual Crash

### ISSUE THREAD

**Issue by Tyrannical** [ReikaKalseki/Reika_Mods_Issues#534] opened 2016-01-01 20:53 UTC
Crash while reading rotarycraft handbook with reactorcraft installed. (newest versions of dragon/reactor/rotary are used)
http://pastebin.com/yh294WkR

Reactorcraft handbook works fine.

This following crash occurs with rotarycraft and reactorcraft while clicking on coal dust in nei with both installed. This does not crash with just rotarycraft.
http://pastebin.com/dMj4HWjw

The following are 2 more crashing from clicking in nei on rotarycraft dusts. (i forgot which ones)
http://pastebin.com/ME7az2xV
http://pastebin.com/UwRrYjcd

**Comment by ReikaKalseki** [comment] 2016-01-01 21:08
Duplicate of #522, #515, #488

**Closed as completed by ReikaKalseki** 2016-01-01 21:08 UTC
Labels: Duplicate
