### ISSUE TITLE
Aura Pouch Deletes Items

### ISSUE THREAD

**Issue by Rivaryn** [ReikaKalseki/Reika_Mods_Issues#3129] opened 2023-01-02 19:29 UTC
Old behavior (4+ years ago): Items could be stored in the aura pouch like a normal backpack, without issue, in addition to its intended use.
New/Current behavior: Items placed in it are destroyed on UI close, causing item loss which punishes the player unfairly.  Issue occurred on latest known version (31b)
Why this is considered unfair:  Shift-clicking items into the aura pouch doesn't work, leading to experimenting and exploring what can be used with it, which supposedly is part of this mod (exploration, trying things by not having the Lexicon give exact answers).  However, Straight up destroying "incorrect" items with no list of what is valid or not, and no handler to help the player (shift-click being a VERY common one across many mods for what works inside said GUI/machine) punishes this experimentation and exploration, in a serious way.

Steps to reproduce:
Open aura pouch UI in hotbar.
Place Chromaticraft Elemental Manipulator inside (tested with a RED slot)
Pick up aura pouch from hotbar directly, causing UI to close and item to drop.
Pick up aura pouch from world.
Open aura pouch UI.  No Elemental Manipulator inside.

**Comment by Maxwell-lt** [comment] 2023-01-02 19:49
This is a duplicate of #3045

**Closed as completed** 2023-07-03 21:50 UTC
Labels: Duplicate, Falsified/Spurious

**Comment by ReikaKalseki** [comment] 2023-07-03 21:54
And not even reported correctly, either, instead making this a big rant about "punishing experimentation" when it affects *all* items and when the bug is not triggered even invalid items work fine. ![https://i.imgur.com/AVTXheQ.png](https://i.imgur.com/AVTXheQ.png)
