### ISSUE TITLE
AOBD incompatability with Rotarycraft v14b

### ISSUE THREAD

**Issue by Abeticdi** [ReikaKalseki/Reika_Mods_Issues#921] opened 2016-06-03 11:18 UTC
I have been running a private server for a little while now and have been doing my best to update everything and upon updating I found myself getting this error [http://pastebin.com/9TsP1HML](url)
It seems removing AOBD resolves the issue, but until I updated, AOBD and Rotarycraft had been working alongside each other fine.

**Comment by 1Matthias** [comment] 2016-06-03 11:21
This is a duplicate of #919 #902 #906 #914 and #916 and is a know bug with the current version of ABOD. Wait for an update, and please try reading through the recent issues before reporting a new one.

**Closed as completed** 2016-06-03 11:22 UTC
Labels: Duplicate

**Comment by Abeticdi** [comment] 2016-06-03 11:23
I noticed a little late. I had been glancing for a bit and didn't notice it.

**Comment by redelman** [comment] 2016-06-03 15:07
How could you not have noticed it? Any search for AOBD would have turned up
all the duplicates.

**Comment by Abeticdi** [comment] 2016-06-03 15:09
I'm half asleep, haven't spent much time on github in the past, and ended up looking a little late at the closed issues. Basically, I'm an oblivious nitwit sometimes and I have already realized my mistake and closed it realizing it was such.

**Comment by TomeWyrm** [comment] 2016-06-04 03:54
Linking the relevant issue for AOBD: ganymedes01/Another-One-Bites-the-Dust#125
